### Loan Notebook  - General Tab ###
LIQ_Loan_Window = 'JavaWindow("title:=.*Loan.*ctive.*")'
LIQ_Loan_Window_Tab = 'JavaWindow("title:=.*Loan.*ctive.*").JavaTab("tagname:=TabFolder")'
LIQ_Loan_Options_Update ='JavaWindow("title:=.*Loan.*Active").JavaMenu("label:=Options").JavaMenu("label:=Update")'
LIQ_Loan_Options_CostOfFunds = LIQ_Loan_Window + '.JavaMenu("label:=Options").JavaMenu("label:=View Match Funded Cost of Funds")'
LIQ_Loan_File_Exit = 'JavaWindow("title:=.*Loan.*Active").JavaMenu("label:=File").JavaMenu("label:=Exit")'
LIQ_Loan_window_Tab_Updated = 'JavaWindow("title:=.*Loan.*Active.*").JavaTab("tagname:=TabFolder")'
LIQ_Loan_Tab = 'JavaWindow("title:=.*Loan \(.*").JavaTab("tagname:=Int\. Cycle Freq:")'
LIQ_Loan_GlobalOriginal_Amount = 'JavaWindow("title:=.*Loan.*Active.*").JavaEdit("attached text:=Global Original:")'
LIQ_Loan_GlobalCurrent_Amount = 'JavaWindow("title:=.*Loan.*ctive.*").JavaEdit("attached text:=Global Current:")'
LIQ_Loan_IntCycleFreq_Dropdownlist = 'JavaWindow("title:=.*Loan.*Active.*").JavaList("attached text:=Int. Cycle Freq:")'
LIQ_Loan_AccrualTab_Cycles_Table = 'JavaWindow("title:=.*Loan.*ctive.*").JavaTree("attached text:=Cycles:")'
LIQ_Loan_AccrualTab_CurrentPerDiem_Text = 'JavaWindow("title:=.*Loan.*Active.*").JavaEdit("index:=0")'
LIQ_Loan_GeneralTab_AdjustedDueDate_Textfield = 'JavaWindow("title:=.*Loan.*Active.*").JavaEdit("attached text:=Adjusted Due Date:")'
LIQ_Loan_GeneralTab_ActualDueDate_Textfield = 'JavaWindow("title:=.*Loan.*Active.*").JavaEdit("attached text:=Actual Due Date:")'
LIQ_Loan_GeneralTab_RateSettingDueDate_Textfield = 'JavaWindow("title:=.*Loan.*Active.*").JavaEdit("attached text:=Rate Setting Due Date:")'
LIQ_Loan_Options_RepaymentSchedule = 'JavaWindow("title:=.*Loan.*Active.*").JavaMenu("label:=Options").JavaMenu("label:=Repayment Schedule")'
LIQ_Loan_Options_Reprice = 'JavaWindow("title:=.*Loan.*Active").JavaMenu("label:=Options").JavaMenu("label:=Reprice .*")'
LIQ_Loan_InquiryMode_Button = 'JavaWindow("title:=.*Loan.*Active.*").JavaButton("attached text:=Notebook in Inquiry Mode - F7")'    
LIQ_Loan_UpdateMode_Button = 'JavaWindow("title:=.*Loan.*Active.*").JavaButton("attached text:=Notebook in Update Mode - F7")'
LIQ_Loan_RiskType_Text = 'JavaWindow("title:=.*Loan.*Active.*").JavaStaticText("labeled_containers_path:=Tab:General;", "x:=116", "y:=201")'
LIQ_Loan_Currency_Text = 'JavaWindow("title:=.*Loan.*Active.*").JavaStaticText("labeled_containers_path:=Tab:General;Group:Loan Amounts;", "index:=4")'
LIQ_Loan_EffectiveDate = 'JavaWindow("title:=.*Loan.*Active.*").JavaStaticText("labeled_containers_path:=Tab:General;", "index:=4")'
LIQ_Loan_MaturityDate_Text = 'JavaWindow("title:=.*Loan.*Active.*").JavaEdit("labeled_containers_path:=Tab:General;", "index:=0")'
LIQ_Loan_PaymentMode_List = 'JavaWindow("title:=.*Loan.*Active.*").JavaList("attached text:=Payment Mode:")'
LIQ_Loan_PricingOption_Text = 'JavaWindow("title:=.*Loan.*Active.*").JavaStaticText("labeled_containers_path:=Tab:General;", "x:=580", "y:=89")'
LIQ_Loan_Accrue_List = 'JavaWindow("title:=.*Loan.*Active.*").JavaList("attached text:=Accrue:")'
LIQ_Loan_Accounting_PerformOnlineAccrual_Menu = 'JavaWindow("title:=.*Loan.*Active.*").JavaMenu("label:=Accounting").JavaMenu("label:=Perform Online Accrual")'
LIQ_Loan_Accounting_CreateBill_Menu = 'JavaWindow("title:=.*Loan.*Active.*").JavaMenu("label:=Accounting").JavaMenu("label:=Create Bill")'
LIQ_Loan_Accounting_CreatePayoffStatement_Menu = 'JavaWindow("title:=.*Loan.*Active.*").JavaMenu("label:=Accounting").JavaMenu("label:=Create Payoff Statement.*")'
LIQ_Loan_PayoffStmnt_Window = 'JavaWindow("title:=Payoff Statement Request.*","displayed:=1")'   
LIQ_Loan_PayoffStmnt_PayoffDate = 'JavaWindow("title:=Payoff Statement Request.*").JavaEdit("attached text:=Payoff Date:")'
LIQ_Loan_PayoffStmnt_OK_Button = 'JavaWindow("title:=Payoff Statement Request.*").JavaButton("label:=OK")'
LIQ_Loan_AccrualEndDate_Text = 'JavaWindow("title:=.*Loan.*Active.*").JavaEdit("attached text:=Accrual End Date:")'
LIQ_Loan_AnyStatus_Window = 'JavaWindow("title:=.*Loan \(.*")'
LIQ_Loan_AnyStatus_Tab = 'JavaWindow("title:=.*Loan \(.*").JavaTab("tagname:=TabFolder")'
LIQ_Loan_AnyStatus_RatesTab_BaseRate_Field = 'JavaWindow("title:=.*Loan \(.*").JavaEdit("attached text:=Current","index:=0")'
LIQ_Loan_AnyStatus_RatesTab_Spread_Field = 'JavaWindow("title:=.*Loan \(.*").JavaEdit("attached text:=Spread:")'
LIQ_Loan_RepricingFrequency_JavaList = 'JavaWindow("title:=.*Loan.*Active.*").JavaList("attached text:=Repricing Frequency:")'
LIQ_Loan_RepricingDate_Text = 'JavaWindow("title:=.*Loan.*Active.*").JavaStaticText("labeled_containers_path:=Tab:General;", "index:=0")'
LIQ_Loan_Options_LoanChangeTransaction_Menu = 'JavaWindow("title:=.*Loan.*Active.*").JavaMenu("label:=Options").JavaMenu("label:=Loan Change Transaction")'
LIQ_Loan_Queries_FeeActivityLIst_Menu = 'JavaWindow("title:=.*Loan.*Active.*").JavaMenu("label:=Queries").JavaMenu("label:=Fee Activity List")'
LIQ_Loan_CyclesforLoan_ProRateType_RadioButton = 'JavaWindow("title:=Cycles for Loan.*").JavaRadioButton("attached text:=${Pro_Rate}")'
LIQ_Loan_RatesTab_ARRParameters_Button = 'JavaWindow("title:=.*Loan.*ctive.*").JavaButton("attached text:=ARR Parameters")'
LIQ_Loan_ProcessingArea_TextField = 'JavaWindow("title:=.*Loan.*ctive.*").JavaStaticText("x:=129", "y:=79")'
LIQ_Loan_AccrualEndDate_Datefield = LIQ_Loan_Window + '.JavaEdit("attached text:=Accrual End Date:")'
LIQ_Loan_Options_InterestCapitalization = 'JavaWindow("title:=.*Loan.*ctive.*").JavaMenu("label:=Options").JavaMenu("label:=Capitalize Interest")'

### Loan ###
LIQ_FixedRateLoan_Options_Update = 'JavaWindow("title:=Fixed Rate Option Loan.*").JavaMenu("label:=Options").JavaMenu("label:=Update")'
LIQ_FixedRateLoan_Window = 'JavaWindow("title:=Fixed Rate Option Loan.*")'
LIQ_FixedRateLoan_Window_Tab = 'JavaWindow("title:=Fixed Rate Option Loan.*").JavaTab("tagname:=TabFolder")'
LIQ_FixedRateLoan_Window_JavaTree='JavaWindow("title:=Fixed Rate Option Loan.*").JavaTree("attached text:=Drill down to perform Workflow item")'
LIQ_FixedRateLoan_Events_List = 'JavaWindow("title:=Fixed Rate Option Loan.*").JavaTree("attached text:=Select event to view details")'
LIQ_FixedRateLoan_Options_ViewLenderShares = 'JavaWindow("title:=Fixed Rate Option Loan.*").JavaMenu("label:=Options").JavaMenu("label:=View Lender Shares")'
LIQ_Loan_Options_Payment = 'JavaWindow("title:=.*Loan.*Active.*").JavaMenu("label:=Options").JavaMenu("label:=Payment")'
LIQ_Loan_ChoosePayment_Window = 'JavaWindow("title:=Choose a Payment")'
LIQ_Loan_Options_ChargeOff_book_Balance='JavaWindow("title:=.*Loan.*ctive.*").JavaMenu("label:=Options").JavaMenu("label:=Chargeoff Book Balance")'             
LIQ_Loan_ChoosePayment_PrincipalPayment_RadioButton = 'JavaWindow("title:=Choose a Payment").JavaRadioButton("attached text:=Principal Payment")'
LIQ_Loan_ChoosePayment_InterestPayment_RadioButton = 'JavaWindow("title:=Choose a Payment").JavaRadioButton("attached text:=Interest Payment")'
LIQ_Loan_ChoosePayment_PaperClipPayment_RadioButton = 'JavaWindow("title:=Choose a Payment").JavaRadioButton("attached text:=Paper Clip Payment")'
LIQ_Loan_ChoosePayment_PaymentApplication_RadioButton = 'JavaWindow("title:=Choose a Payment").JavaRadioButton("attached text:=Payment Application")'
LIQ_Loan_ChoosePayment_OngoingFeeApplication_RadioButton = 'JavaWindow("title:=Choose a Payment").JavaRadioButton("attached text:=Ongoing Fee Payment")'
LIQ_Loan_ChoosePayment_FeePayment_RadioButton = 'JavaWindow("title:=Choose a Payment").JavaRadioButton("attached text:=Fee Payment")'
LIQ_Loan_ChoosePayment_OK_Button = 'JavaWindow("title:=Choose a Payment").JavaButton("attached text:=OK")'
LIQ_Loan_CyclesforLoan_Window = 'JavaWindow("title:=Cycles for Loan.*")'
LIQ_Loan_CyclesforLoan_ProjectedDue_RadioButton = 'JavaWindow("title:=Cycles for Loan.*").JavaRadioButton("attached text:=Projected Due")'
LIQ_Loan_CyclesforLoan_List = 'JavaWindow("title:=Cycles for Loan.*").JavaTree("attached text:=Choose a cycle to make a payment against")'
LIQ_Loan_CyclesforLoan_OK_Button = 'JavaWindow("title:=Cycles for Loan.*").JavaButton("attached text:=OK")'

### Loan Notebook - Rate Tab ###
LIQ_Loan_BaseRate = 'JavaWindow("title:=.*Loan.*ctive.*").JavaTab("text:=Rates").JavaButton("attached text:=Base Rate:")'
LIQ_Loan_AllInRate = 'JavaWindow("title:=.*Loan.*ctive.*").JavaEdit("attached text:=All-In Rate:")'
LIQ_Loan_RateBasis_Dropdownlist = 'JavaWindow("title:=.*Loan.*Active.*").JavaObject("tagname:=Group", "text:=Interest Rates").JavaList("attached text:=Rate Basis:")'
LIQ_Loan_AnyStatus_AllInRate = 'JavaWindow("title:=.*Loan \(.*").JavaEdit("attached text:=All-In Rate:")'
LIQ_Loan_AnyStatus_RateBasis_Dropdownlist = 'JavaWindow("title:=.*Loan \(.*").JavaObject("tagname:=Group", "text:=Interest Rates").JavaList("attached text:=Rate Basis:")'
LIQ_Loan_AnyStatus_RatesTab_BaseRate_TextField = 'JavaWindow("title:=.*Loan \(.*").JavaEdit("attached text:=Base Rate:")'
LIQ_Loan_Spread_Text = 'JavaWindow("title:=.*Loan.*Active.*").JavaEdit("attached text:=Spread:")'
LIQ_Loan_PenaltySpreadRate_Text = 'JavaWindow("title:=.*Loan.*Active.*").JavaObject("text:=Penalty Spread").JavaEdit("attached text:=Rate:")'
LIQ_Loan_PenaltySpreadStatus_Text = 'JavaWindow("title:=.*Loan.*Active.*").JavaObject("text:=Penalty Spread").JavaStaticText("index:=2")'
LIQ_Loan_BaseRateHistory_Button = 'JavaWindow("title:=.*Loan.*Active.*").JavaObject("text:=Interest Rates").JavaButton("tagname:=History", "index:=0")' 
LIQ_Loan_BaseRateFloorHistory_Button = 'JavaWindow("title:=.*Loan.*Active.*").JavaObject("text:=Interest Rates").JavaButton("tagname:=History", "index:=16")'   
LIQ_Loan_RatesTab_PenaltySpread_Status_OFF = 'JavaWindow("title:=.*Loan.*Active.*").JavaStaticText("labeled_containers_path:=Tab:Rates;Group:Interest Rates;Group:Penalty Spread;","attached text:=OFF")'
LIQ_Loan_RatesTab_BaseRateFloor_TextField = 'JavaWindow("title:=.*Loan.*ctive.*").JavaEdit("attached text:=Base Rate Floor:")'
LIQ_Loan_RatesTab_LegacyBaseRateFloor_TextField = LIQ_Loan_Window + '.JavaTab("attached text:=.*BRF.*").JavaEdit("attached text:=.*BRF.*","index:=3")'
LIQ_Loan_RatesTab_BaseRate_TextField = 'JavaWindow("title:=.*Loan.*ctive.*").JavaEdit("attached text:=Current")'
LIQ_Loan_RatesTab_BaseRateFromPricing_TextField = 'JavaWindow("title:=.*Loan.*ctive.*").JavaEdit("labeled_containers_path:=Tab:Rates;Group:Interest Rates;", "index:=7")'
LIQ_Loan_RatesTab_SpreadAdjustment_TextField = 'JavaWindow("title:=.*Loan.*ctive.*").JavaEdit("attached text:=Spread Adjustment:")'
LIQ_Loan_RatesTab_Spread_Textfield = 'JavaWindow("title:=.*Loan.*ctive.*").JavaEdit("attached text:=Spread:")'
LIQ_Loan_RatesTab_AllInRate_TextField = LIQ_Loan_Window + '.JavaEdit("attached text:=All-In Rate:")'
LIQ_Loan_RatesTab_AllInRateCap_TextField = 'JavaWindow("title:=.*Loan.*Active.*").JavaEdit("index:=4")'
LIQ_Loan_RatesTab_AllInRateFloor_TextField = 'JavaWindow("title:=.*Loan.*Active.*").JavaEdit("index:=5")'
LIQ_Loan_RatesTab_AdditionalSpread_Field = 'JavaWindow("title:=.*Loan.*Active.*").JavaEdit("index:=6")'

### Loan Notebook - Base Rate History ####
LIQ_Loan_BaseRateHistory_Window = 'JavaWindow("title:=.*Loan.*ase.*")'
LIQ_Loan_BaseRateHistory_List = 'JavaWindow("title:=.*Loan.*ase.*").JavaTree("class description:=list")'
LIQ_LoanBaseRateHistory_OK_Button = 'JavaWindow("title:=.*Loan.*ase.*").JavaButton("attached text:=OK")'
LIQ_LoanBaseRateHistory_Delete_Button = 'JavaWindow("title:=.*Loan.*ase.*").JavaButton("attached text:=Delete")'
LIQ_LoanBaseRateHistory_Cancel_Button = 'JavaWindow("title:=.*Loan.*ase.*").JavaButton("attached text:=Cancel")'
LIQ_Loan_RawBaseRateHistory_Button = 'JavaWindow("title:=.*Loan.*ase.*").JavaButton("attached text:=Raw Rate History")'

### Loan Notebook - Raw Base Rate History ###
LIQ_Loan_RawBaseRateHistory_Window = 'JavaWindow("title:=.*Loan.*Raw Base.*")'
LIQ_Loan_RawBaseRateHistory_List = 'JavaWindow("title:=.*Loan.*Raw Base.*").JavaTree("class description:=list")'

### Loan Notebook - Events Tab ###
LIQ_Loan_Events_List = 'JavaWindow("title:=.*Loan.*ctive.*").JavaTree("attached text:=Select event to view details")'
LIQ_Loan_Events_Comment = 'JavaWindow("title:=.*Loan.*Active.*").JavaEdit("attached text:=Comment:")'
LIQ_Loan_Events_ZoomComment_Button = 'JavaWindow("title:=.*Loan.*Active.*").JavaButton("attached text:=Zoom Comment")'
LIQ_Loan_Events_ZoomComment_Field = 'JavaWindow("title:=Event Comments").JavaEdit("tagname:=Text")'
LIQ_Loan_Events_Tab = 'JavaWindow("title:=.*Loan \(.*").JavaTab("tagname:=TabFolder")'
LIQ_Loan_Events_GLEntries_Button = 'JavaWindow("title:=.*Loan.*Active.*").JavaButton("attached text:=GL Entries")'
LIQ_PrincipalPayment_GLEntries_Window = 'JavaWindow("title:=GL Entries For.*Principal Payment")'
LIQ_PrincipalPayment_GLEntries_Table = 'JavaWindow("title:=GL Entries For.*Principal Payment").JavaTree("attached text:=Drill down to view details")'
LIQ_PrincipalPayment_GLEntries_Exit_Button = 'JavaWindow("title:=GL Entries For.*Principal Payment").JavaButton("attached text:=Exit")'  
 
### Loan Notebook - Currency Tab ####
LIQ_Loan_Currency_FXRateAUDtoUSD = 'JavaWindow("title:=.*Loan.*Active.*").JavaObject("text:=F.*X Rate").JavaStaticText("to_class:=JavaStaticText","index:=0")'
LIQ_Loan_Currency_Textbox = 'JavaWindow("title:=Facility Currency.*").JavaEdit("attached text:=AUD to USD Rate:")'
LIQ_Loan_Currency_RateHistory_Window = 'JavaWindow("title:=.* History")'
LIQ_Loan_Currency_Current = 'JavaWindow("title:=.*Loan.*Active.*").JavaStaticText("labeled_containers_path:=Tab:Currency;Group:Amounts in Facility Currency;","index:=3")'

### Loan Notebook - Cost of Funds ###
LIQ_Loan_CostOfFunds_Window = 'JavaWindow("title:=Cost Of Funds.*")'
LIQ_Loan_CostOfFunds_COFARRParameters_Button = LIQ_Loan_CostOfFunds_Window + '.JavaButton("attached text:=COF ARR Parameters")'

### Repayment Schedule Window ###
LIQ_RepaymentSchedule_Window = 'JavaWindow("title:=Repayment Schedule For Loan.*")'
LIQ_RepaymentSchedule_Options_Reschedule = 'JavaWindow("title:=Repayment Schedule For Loan.*").JavaMenu("label:=Options").JavaMenu("label:=Reschedule")'
LIQ_RepaymentSchedule_ScheduleType_Window = 'JavaWindow("title:=Choose a Type of Schedule")'
LIQ_RepaymentSchedule_ScheduleType_PrincipalOnly_RadioButton = 'JavaWindow("title:=Choose a Type of Schedule").JavaRadioButton("attached text:=Principal Only")'
LIQ_RepaymentSchedule_ScheduleType_FPPID_RadioButton = 'JavaWindow("title:=Choose a Type of Schedule").JavaRadioButton("attached text:=Fixed Principal Plus Interest Due")'
LIQ_RepaymentSchedule_ScheduleType_POBM_RadioButton = 'JavaWindow("title:=Choose a Type of Schedule").JavaRadioButton("attached text:=Principal Only With Bullet At Maturity")'
LIQ_RepaymentSchedule_ScheduleType_FPPIDue_RadioButton = 'JavaWindow("title:=Choose a Type of Schedule").JavaRadioButton("attached text:=Fixed Principal Plus Interest Due")'
LIQ_RepaymentSchedule_ScheduleType_FPPI_RadioButton = 'JavaWindow("title:=Choose a Type of Schedule").JavaRadioButton("attached text:=Fixed Payment .*Principal and Interest.*")'
LIQ_RepaymentSchedule_ScheduleType_FlexSchedule_RadioButton = 'JavaWindow("title:=Choose a Type of Schedule").JavaRadioButton("attached text:=Flex Schedule")'
LIQ_RepaymentSchedule_ScheduleType_Prorate_CheckBox = 'JavaWindow("title:=Choose a Type of Schedule").JavaCheckBox("attached text:=Prorate based on Facility Repayment Schedule")'
LIQ_RepaymentSchedule_ScheduleType_OK_Button = 'JavaWindow("title:=Choose a Type of Schedule").JavaButton("attached text:=OK")'
LIQ_RepaymentSchedule_NonBusDayRule_Dropdown = 'JavaWindow("title:=Repayment Schedule For Loan.*").JavaList("tagname:=Combo")'
LIQ_RepaymentSchedule_CurrentSchedule_POBM_Text = 'JavaWindow("title:=Repayment Schedule For Loan.*").JavaObject("tagname:=Group", "text:=Current Schedule - Principal Only with Bullet at Maturity")'
LIQ_RepaymentSchedule_CurrentSchedule_PrincipalOnly_Text = 'JavaWindow("title:=Repayment Schedule For Loan.*").JavaObject("tagname:=Group", "text:=Current Schedule - Principal Only")'
LIQ_RepaymentSchedule_CurrentSchedule_FixedPrincipalPlusInterestDue_Text = 'JavaWindow("title:=Repayment Schedule For Loan.*").JavaObject("tagname:=Group", "text:=Current Schedule - Fixed Principal Plus Interest Due")'
LIQ_RepaymentSchedule_CurrentSchedule_CurrentHostBank_TextField = 'JavaWindow("title:=Repayment Schedule For Loan.*").JavaEdit("attached text:=Current Host Bank:")'
LIQ_RepaymentSchedule_CurrentSchedule_List = 'JavaWindow("title:=Repayment Schedule For Loan.*").JavaTree("attached text:=Nominal Amount:")'
LIQ_RepaymentSchedule_Frequency_JavaTree = 'JavaWindow("title:=Repayment Schedule.*").JavaTree("labeled_containers_path:=Group:Current Schedule.*")'
LIQ_RepaymentSchedule_RepaymentHistory_JavaTree = 'JavaWindow("title:=Repayment Schedule.*").JavaObject("path:=SxSyTree;Shell;").JavaTree("tagname:=Repayment History:")'
LIQ_RepaymentSchedule_Save_Button = 'JavaWindow("title:=Repayment Schedule For Loan.*").JavaButton("attached text:=Save")'
LIQ_RepaymentSchedule_Exit_Button = 'JavaWindow("title:=Repayment Schedule For Loan.*").JavaButton("attached text:=Exit")'
LIQ_RepaymentSchedule_AddUnschTran_Button = 'JavaWindow("title:=Repayment Schedule.*").JavaButton("attached text:=Add Unsch. Tran.")'
LIQ_AddTransaction_Principal_Textfield = 'JavaWindow("title:=Add Transaction").JavaEdit("attached text:=Principal:")'
LIQ_AddTransaction_EffectiveDate_Textfield = 'JavaWindow("title:=Add Transaction").JavaEdit("attached text:=Effective Date:")'
LIQ_AddTransaction_ApplyPrincipalToNextSchedPayment_RadioButton = 'JavaWindow("title:=Add Transaction").JavaRadioButton("attached text:=Apply Principal To Next Scheduled Payment")'
LIQ_AddTransaction_OK_Button = 'JavaWindow("title:=Add Transaction").JavaButton("attached text:=OK")'
LIQ_AddTransaction_InterestDue_Textfield = 'JavaWindow("title:=Add Transaction").JavaEdit("attached text:=Interest Due.*")'
LIQ_RepaymentSchedule_Options_CreateTemporaryPaymentPlan = 'JavaWindow("title:=Repayment Schedule For Loan.*").JavaMenu("label:=Options").JavaMenu("label:=Create Temporary Payment Plan")'
LIQ_RepaymentSchedule_ModifyItem_Button = 'JavaWindow("title:=Repayment Schedule For Loan.*").JavaButton("attached text:=Modify Item.*")'
LIQ_RepaymentSchedule_Options_Resynchronize = 'JavaWindow("title:=Repayment Schedule For Loan.*").JavaMenu("label:=Options").JavaMenu("label:=Resynchronize")'
LIQ_RepaymentSchedule_ResyncSettings_Dropdown = 'JavaWindow("title:=Repayment Schedule For Loan.*").JavaList("attached text:=Resync.*Settings:")'
LIQ_RepaymentSchedule_IncludeInterestPaymentHistory_Checkbox = 'JavaWindow("title:=Repayment Schedule For Loan.*").JavaCheckBox("attached text:=Include Interest Payment History")'
LIQ_RepaymentSchedule_RepaymentScheduleSync_Checkbox = 'JavaWindow("title:=Repayment Schedule For Loan.*").JavaCheckBox("attached text:=Repayment Schedule Sync")'
LIQ_RepaymentSchedule_FlexSchedule_Section = 'JavaWindow("title:=Repayment Schedule For Loan.*").JavaObject("tagname:=Group","text:=Current Schedule - Flex Schedule")'
LIQ_RepaymentSchedule_CurrentFlexSchedule_JavaTree = 'JavaWindow("title:=Repayment Schedule For Loan.*").JavaTree("attached text:=.*Nominal Amount.*")'
LIQ_RepaymentSchedule_ScheduleType_Cancel_Button = 'JavaWindow("title:=Choose a Type of Schedule").JavaButton("attached text:=Cancel")'
LIQ_AddTransaction_SelectInterestAccrual_Button = 'JavaWindow("title:=Add Transaction").JavaButton("label:=Select Interest Accrual Cycle")'
LIQ_AddTransaction_ApplyPrincipalToLastSchedPayment_RadioButton = 'JavaWindow("title:=Add Transaction").JavaRadioButton("attached text:=Apply Principal To Last Scheduled Payment")'
LIQ_RepaymentSchedule_JavaTree = 'JavaWindow("title:=Repayment Schedule For Loan.*").JavaTree("attached text:=Resync. Settings:")'
LIQ_RepaymentSchedule_TransactionNB_Button = 'JavaWindow("title:=Repayment Schedule.*").JavaButton("attached text:=Transaction NB")'
LIQ_RepaymentSchedule_CreatePendingTran_Button = 'JavaWindow("title:=Repayment Schedule.*").JavaButton("attached text:=Create Pending Tran.")'
LIQ_RepaymentSchedule_CurrentSchedule_FixedPayment_List = 'JavaWindow("title:=Repayment Schedule For Loan.*").JavaTree("index:=0")'
LIQ_RepaymentSchedule_CurrentSchedule_Resync_Javatree = 'JavaWindow("title:=Repayment Schedule For Loan.*").JavaTree("attached text:=Resync. Settings:")'
LIQ_RepaymentSchedule_CurrentSchedule_Javatree = 'JavaWindow("title:=.*Repayment Schedule For Loan.*").JavaTree("labeled_containers_path:=.*Current Schedule.*")'
LIQ_AutomaticScheduleSetup_NumberOfCycles_Textfield = 'JavaWindow("title:=Automatic Schedule Setup - Principal Only").JavaEdit("attached text:=No. Cyc. Items:")'
LIQ_AutomaticScheduleSetup_Principal_OK_Button = 'JavaWindow("title:=Automatic Schedule Setup.*","displayed:=1").JavaButton("attached text:=OK")'

###Temporary Repayment Schedule Window###
LIQ_TemporaryRepaymentSchedule_Window = 'JavaWindow("title:=Temporary Repayment Schedule For Loan.*")'
LIQ_TemporaryRepaymentSchedule_Save_Button = 'JavaWindow("title:=Temporary Repayment Schedule For Loan.*").JavaButton("attached text:=Save")'
LIQ_TemporaryRepaymentSchedule_Exit_Button = 'JavaWindow("title:=Temporary Repayment Schedule For Loan.*").JavaButton("attached text:=Exit")'
LIQ_TemporaryRepaymentSchedule_Options_BecomeLegalPaymentPlan = 'JavaWindow("title:=Temporary Repayment Schedule For Loan.*").JavaMenu("label:=Options").JavaMenu("label:=Become Legal Payment Plan")'

### Loan Notebook - General Tab ###
LIQ_LoanNotebook_RepaymentSchedule_Menu = 'JavaWindow("title:=.*Loan.*Active.*").JavaMenu("label:=Options").JavaMenu("label:=Repayment Schedule")' 
LIQ_LoanNotebook_FacilityNotebook_Menu = 'JavaWindow("title:=.*Loan.*Active.*").JavaMenu("label:=Options").JavaMenu("label:=Facility Notebook")'  
LIQ_LoanNotebook_Options_ViewLenderShares = 'JavaWindow("title:=.*Loan.*ctive.*").JavaMenu("label:=Options").JavaMenu("label:=View Lender Shares")'
 
LIQ_Loan_GlobalOriginal_Field = 'JavaWindow("title:=.*Loan.*ctive.*").JavaEdit("attached text:=Global Original:")'
LIQ_Loan_GlobalCurrent_Field = 'JavaWindow("title:=.*Loan.*ctive.*").JavaEdit("attached text:=Global Current:")'
LIQ_Loan_HostBankGross_Field = 'JavaWindow("title:=.*Loan.*ctive.*").JavaEdit("attached text:=Host Bank Gross:")'  
LIQ_Loan_HostBankNet_Field = 'JavaWindow("title:=.*Loan.*ctive.*").JavaEdit("attached text:=Host Bank Net:")' 
LIQ_Loan_Event_JavaTree = 'JavaWindow("title:=.*Loan.*ctive.*").JavaTree("attached text:=Select event to view details")' 
LIQ_LoanNotebook_FileExit_Menu = 'JavaWindow("title:=.*Loan.*Active.*").JavaMenu("label:=File").JavaMenu("label:=Exit")' 
LIQ_Loan_HostBankGross_Amount = 'JavaWindow("title:=.*Loan.*Active.*").JavaEdit("attached text:=Host Bank Gross:")'
LIQ_Loan_HostBankNet_Amount = 'JavaWindow("title:=.*Loan.*Active.*").JavaEdit("attached text:=Host Bank Net:")'
 
### Loan Notebook - Pending Tab ####
LIQ_Loan_PendingItems_Null = 'JavaWindow("title:=.*Loan.*Active.*").JavaTree("attached text:=Pending Transactions","items count:=0")'
LIQ_Loan_PendingTab_JavaTree = 'JavaWindow("title:=.*Loan \(.*").JavaTree("attached text:=Pending Transactions")'
 
### Loan Notebook - Repayment Schedule Window ###
LIQ_RepaymentSchedule_FlexSchedule_JavaTree = 'JavaWindow("title:= Repayment Schedule.*").JavaTree("attached text:=Resync. Settings:")'
LIQ_RepaymentSchedule_CreatePending_Button = 'JavaWindow("title:=.*Repayment Schedule.*").JavaButton("label:=Create Pending Tran.*")'
LIQ_RepaymentSchedule_DeletePending_Button = 'JavaWindow("title:= Repayment Schedule.*").JavaButton("label:=Delete Pending Tran.*")'
LIQ_RepaymentSchedule_Transaction_NB_Button = 'JavaWindow("title:= Repayment Schedule.*").JavaButton("label:=Transaction NB")'
LIQ_RepaymentSchedule_OriginalLoanAmount_Field =    'JavaWindow("title:= Repayment Schedule.*").JavaEdit("attached text:=Original:")' 
LIQ_RepaymentSchedule_CurrentLoanAmount_Field =    'JavaWindow("title:= Repayment Schedule.*").JavaEdit("attached text:=Current:")' 
LIQ_RepaymentSchedule_CurrentHostAmount_Field =    'JavaWindow("title:= Repayment Schedule.*").JavaEdit("attached text:=Current Host Bank:")'
LIQ_MakeSelection_DeleteInterestOnly_RadioButton = 'JavaWindow("title:=Make Selection.*").JavaRadioButton("attached text:=.*Delete Interest Only.*")'
LIQ_RepaymentSchedule_History = 'JavaWindow("title:=Repayment Schedule.*").JavaTree("attached text:=Repayment History:")'
 
### Existing Loan for Facility Window Window ###
LIQ_ExistingLoanForFacility_Window = 'JavaWindow("title:=Existing.* For Facility.*")'
LIQ_ExistingLoanForFacility_Payment_Button = 'JavaWindow("title:=Existing Loans.*").JavaButton("label:=Payment")'
LIQ_ExistingLoanForFacility_Increase_Button = 'JavaWindow("title:=Existing Loans.*").JavaButton("label:=Increase")'
LIQ_ExistingLoanForFacility_CreateRepricing_Button = LIQ_ExistingLoanForFacility_Window + '.JavaButton("label:=Create.*Repricing")'
LIQ_ExistingLoanForFacility_Update_Checkbox = 'JavaWindow("title:=Existing.* For Facility.*").JavaCheckBox("attached text:=Open notebook in update mode")'
LIQ_ExistingLoanForFacility_RemainOpen_Checkbox = 'JavaWindow("title:=Existing.* For Facility.*").JavaCheckBox("attached text:=Remain open after.*")'
LIQ_ExistingLoanForFacility_Tree = 'JavaWindow("title:=Existing.* For Facility.*").JavaTree("attached text:=Drill down to open the notebook")'   
LIQ_ExistingLoanForFacility_ForSpecificDeal_window='JavaWindow("title:=title:=Existing Loans For Facility: BNS2SYN_10092020174708POI/S2TERM10092020184647MMN")'

### Loan Notebook - Repayment Schedule Window ###
LIQ_Payment_PrincipalPayment_RadioButton = 'JavaWindow("title:=Choose a Payment").JavaRadioButton("attached text:=Principal Payment")'
LIQ_Payment_InterestPayment_RadioButton = 'JavaWindow("title:=Choose a Payment").JavaRadioButton("attached text:=Interest Payment")'
LIQ_Payment_OK_Button = 'JavaWindow("title:=Choose a Payment").JavaButton("label:=OK")'

### Automatic Schedule Setup - Fixed Principal Plus Interest Due Window ###
LIQ_AutomaticScheduleFPPID_Window = 'JavaWindow("title:=Automatic Schedule Setup - Fixed Principal Plus Interest Due")'
LIQ_AutomaticScheduleFPPID_Accept_Button = 'JavaWindow("title:=Automatic Schedule Setup - Fixed Principal Plus Interest Due").JavaButton("attached text:=Accept")'
LIQ_AutomaticScheduleFPPID_OK_Button = 'JavaWindow("title:=Automatic Schedule Setup - Fixed Principal Plus Interest Due").JavaButton("attached text:=OK")'
LIQ_AutomaticScheduleFPPID_FixedPrincipalPaymountAmount_Field = 'JavaWindow("title:=Automatic Schedule Setup - Fixed Principal Plus Interest Due","displayed:=1").JavaEdit("index:=2")'

###Automatic Schedule Setup - Principal Only Window###
LIQ_AutomaticSchedulePrincipalOnly_Window = 'JavaWindow("title:=Automatic Schedule Setup - Principal Only")'
LIQ_AutomaticSchedulePrincipalOnly_OK_Button = LIQ_AutomaticSchedulePrincipalOnly_Window + '.JavaButton("attached text:=OK")'
LIQ_AutomaticSchedulePrincipalOnly_Frequency_Dropdown = LIQ_AutomaticSchedulePrincipalOnly_Window + '.JavaObject("text:=Cyclical Schedule Terms").JavaList("tagname:=Combo")'
LIQ_AutomaticSchedulePrincipalOnly_Amount_Input = LIQ_AutomaticSchedulePrincipalOnly_Window + '.JavaObject("text:=Cyclical Schedule Terms").JavaEdit("attached text:=Amount:")'
LIQ_AutomaticSchedulePrincipalOnly_TriggerDate_Input = LIQ_AutomaticSchedulePrincipalOnly_Window + '.JavaObject("text:=Cyclical Schedule Terms").JavaEdit("attached text:=Trigger Date:")'

### Pending Loan Notebook ###
LIQ_Loan_Pending_Window = 'JavaWindow("title:=.*Loan.*Pending.*")'
LIQ_Loan_Pending_Tab = 'JavaWindow("title:=.*Loan.*Pending.*").JavaTab("tagname:=TabFolder")'
LIQ_Loan_Pending_Pending_JavaTree = 'JavaWindow("title:=.*Loan.*Pending.*").JavaTree("attached text:=Pending Transactions")'
LIQ_Loan_Pending_Accrual_JavaTree = 'JavaWindow("title:=.*Loan.*Pending.*").JavaTree("attached text:=Cycles:")'
LIQ_Loan_Pending_RatesTab_BaseRate_TextField = 'JavaWindow("title:=.*Loan.*Pending.*").JavaEdit("attached text:=Base Rate:")'

### Accrual Cycle Detail ###
LIQ_AccrualCycleDetail_Window = 'JavaWindow("title:=Accrual Cycle Detail")'
LIQ_AccrualCycleDetail_PaidToDate_Field = 'JavaWindow("title:=Accrual Cycle Detail").JavaEdit("index:=6")'
LIQ_AccrualCycleDetail_AccruedToDate_Field = 'JavaWindow("title:=Accrual Cycle Detail").JavaEdit("attached text:=Accrued to date:")'
LIQ_AccrualCycleDetail_ProjectedEOCAccrual_Field = 'JavaWindow("title:=Accrual Cycle Detail").JavaEdit("attached text:=Projected EOC accrual:")'
LIQ_AccrualCycleDetail_CycleDue_Field = 'JavaWindow("title:=Accrual Cycle Detail").JavaEdit("attached text:=Cycle due:")'
LIQ_AccrualCycleDetail_LineItems_Button = 'JavaWindow("title:=Accrual Cycle Detail").JavaButton("attached text:=Line Items")'
LIQ_AccrualCycleDetail_SharesOverview_Button = 'JavaWindow("title:=Accrual Cycle Detail").JavaButton("attached text:=Shares Overview")'
LIQ_AccrualCycleDetail_Cancel_Button = 'JavaWindow("title:=Accrual Cycle Detail").JavaButton("attached text:=Cancel")'
LIQ_AccrualCycleDetail_Payments_Button = 'JavaWindow("title:=Accrual Cycle Detail").JavaButton("attached text:=Payments")'
LIQ_AccrualCycleDetail_Payments_Window = 'JavaWindow("title:=Payments")'
LIQ_AccrualCycleDetail_Payments_JavaTree = 'JavaWindow("label:=Payments","enabled:=1").JavaTree("tagname:=Drill Down to view details","enabled:=1")'
LIQ_AccrualCycleDetail_StartDate_StaticText = 'JavaWindow("title:=Accrual Cycle Detail").JavaStaticText("index:=4")'
LIQ_AccrualCycleDetail_EndDate_StaticText = 'JavaWindow("title:=Accrual Cycle Detail").JavaStaticText("index:=5")'
LIQ_AccrualCycleDetail_ActualDueDate_StaticText = 'JavaWindow("title:=Accrual Cycle Detail").JavaStaticText("index:=6")'
LIA_AccrualCycleDetail_CyleSharesOverview_Button = 'JavaWindow("title:=Libor Option.*").JavaButton("attached text:=Cycle Shares Overview")'

### Line Items for ###
LIQ_LineItemsFor_Window = 'JavaWindow("title:=Line Items for .*")'
LIQ_LineItemsFor_JavaTree = 'JavaWindow("title:=Line Items for .*").JavaTree("displayed:=1")'
LIQ_LineItemsFor_Exit_Button = 'JavaWindow("title:=Line Items for .*").JavaButton("attached text:=Exit")'
LIQ_LineItemsFor_BaseRateDetails_Button = 'JavaWindow("title:=Line Items for .*").JavaButton("attached text:=Base Rate Details")'

### Lenders Shares For Window - Loan Notebook ###
LIQ_LenderSharesFor_Window = 'JavaWindow("title:=Shares for.*")'
LIQ_LenderSharesFor_Participants_Javatree= 'JavaWindow("title:=Shares for.*").JavaTree("attached text:=Drill Down for Participation Detail")'
LIQ_LenderSharesFor_Primaries_Javatree = 'JavaWindow("title:=Shares for.*").JavaTree("attached text:=Drill Down for Primary/Assignment Detail")'
LIQ_LenderSharesFor_PartShare_Window = 'JavaWindow("title:=Participation Share")'
LIQ_LenderSharesFor_PartShare_ActualAmt_Field = 'JavaWindow("title:=Participation Share").JavaEdit("attached text:=LENDLEGAL17100 / BLOGGS")'
LIQ_LenderSharesFor_PartShare_ActualAmt_Cancel_Button = 'JavaWindow("title:=Participation Share").JavaButton("attached text:=Cancel")'
LIQ_LenderSharesFor_ParticipantsWithPosition_Javatree= 'JavaWindow("title:=Shares for.*").JavaTree("attached text:=.*${Position}.*")'
LIQ_LenderSharesFor_ParticipationShare_Window = 'JavaWindow("title:=Participation Share")'
LIQ_LenderSharesFor_ParticipationShare_LenderAllInRate_Textfield = 'JavaWindow("title:=Participation Share").JavaEdit("index:=3")'
LIQ_LenderSharesFor_ParticipationShare_Cancel_Button = 'JavaWindow("title:=Participation Share").JavaButton("attached text:=Cancel")'
LIQ_LenderSharesFor_ParticipationShare_OK_Button = 'JavaWindow("title:=.*Shares for.*").JavaButton("attached text:=OK")'

### Servicing Group Accrual Cycle Detail ###
LIQ_ServicingGroupAccrualCycleDetail_Window = 'JavaWindow("title:=Servicing Group Accrual Cycle Detail")'
LIQ_ServicingGroupAccrualCycleDetail_Skims_Button = 'JavaWindow("title:=Servicing Group Accrual Cycle Detail").JavaButton("attached text:=Skims")'
LIQ_ServicingGroupAccrualCycleDetail_LineItems_Button = 'JavaWindow("title:=Servicing Group Accrual Cycle Detail").JavaButton("attached text:=Line Items")'
LIQ_ServicingGroupAccrualCycleDetail_Exit_Button = 'JavaWindow("title:=Servicing Group Accrual Cycle Detail").JavaButton("attached text:=Exit")'

### Servicing Group Line Items For ###
LIQ_ServicingGroupLineItemsFor_Window = 'JavaWindow("title:=Servicing Group Line Items for .*")'
LIQ_ServicingGroupLineItemsFor_JavaTree = 'JavaWindow("title:=Servicing Group Line Items for .*").JavaTree("displayed:=1")'
LIQ_ServicingGroupLineItemsFor_Exit_Button = 'JavaWindow("title:=Servicing Group Line Items for .*").JavaButton("attached text:=Exit")'

### Skims For ###
LIQ_SkimsFor_Window = 'JavaWindow("title:=Skims for.*")'
LIQ_SkimsFor_JavaTree = 'JavaWindow("title:=Skims for.*").JavaTree("attached text:=Drill down to view details")'
LIQ_SkimsFor_Exit_Button = 'JavaWindow("title:=Skims for.*").JavaButton("attached text:=Exit")'

### Skim Line Items For ###
LIQ_SkimLineItemsFor_Window = 'JavaWindow("title:=Skim Line Items for .*")'
LIQ_SkimLineItemsFor_JavaTree = 'JavaWindow("title:=Skim Line Items for .*").JavaTree("displayed:=1")'
LIQ_SkimLineItemsFor_Exit_Button = 'JavaWindow("title:=Skim Line Items for .*").JavaButton("attached text:=Exit")'

### Skim Accrual Cycle Detail ###
LIQ_SkimAccrualCycleDetail_Window = 'JavaWindow("title:=Skim Accrual Cycle Detail")'
LIQ_SkimAccrualCycleDetail_LineItems_Button = 'JavaWindow("title:=Skim Accrual Cycle Detail").JavaButton("attached text:=Line items")'
LIQ_SkimAccrualCycleDetail_Exit_Button = 'JavaWindow("title:=Skim Accrual Cycle Detail").JavaButton("attached text:=Exit")'
LIQ_SkimAccrualCycleDetail_Skim_TextField = 'JavaWindow("title:=Skim Accrual Cycle Detail").JavaStaticText("path:=VerticalAlignableLabel;Shell;","index:=14")'

### Accrual Tab ###
LIQ_Loan_Accrual_JavaTree = 'JavaWindow("title:=.*Loan.*Active.*").JavaTree("attached text:=Cycles:")'

### Lender Shares for Loan Window ###
LIQ_Loan_LenderShares_Window = 'JavaWindow("title:=Shares for.*Loan.*")'
LIQ_Loan_LenderShares_JavaTree = 'JavaWindow("title:=Shares for.*Loan.*").JavaTree("attached text:=Drill Down for Primary/Assignment Detail")'

### Fixed Rate Option Loan ###
LIQ_FixedRateOptionLoan_Tab = 'JavaWindow("title:=.*Fixed Rate Option Loan \(.*").JavaTab("tagname:=Int\. Cycle Freq:")'
LIQ_FixedRateOptionLoan_Event_JavaTree = 'JavaWindow("title:=Fixed Rate Option Loan .*").JavaTree("attached text:=Select event to view details")'

### LIQ Chargeoff Book Balance ###
LIQ_Chargeoff_book_Balance_Window='JavaWindow("title:=.*Loan Chargeoff Book Balance.*")'
LIQ_Chargeoff_Book_Balance_Requested_Amount_TextField='JavaWindow("title:=.*Loan Chargeoff Book Balance.*").JavaEdit("attached text:=Requested:")'
LIQ_Chargeoff_book_Balance_Effective_Date='JavaWindow("title:=.*Loan Chargeoff Book Balance.*").JavaEdit("attached text:=Effective Date:")'
LIQ_Chargeoff_book_Balance_Save_Menu='JavaWindow("title:=.*Loan Chargeoff Book Balance.*").JavaMenu("label:=File").JavaMenu("label:=Save")'
LIQ_Chargeoff_book_Balance_Queries_GLEntries='JavaWindow("title:=.*Loan Chargeoff Book Balance.*").JavaMenu("label:=Queries").JavaMenu("label:=GL Entries")'
LIQ_Gl_Entries_for_Chargeoff_Book_Balance='JavaWindow("label:=GL Entries For Fixed Rate Option Loan Chargeoff Book Balance").JavaButton("label:=Exit")'
LIQ_Chargeoff_book_Balance_GL_Entries_Workflow='JavaWindow("title:=GL Entries For Fixed Rate Option Loan Chargeoff Book Balance").JavaTab("text:=Workflow").JavaTree("attached text:=Drill down to perform Workflow item")'
LIQ_Chargeoff_book_Balance_Tab='JavaWindow("title:=.*Loan Chargeoff Book Balance.*").JavaTab("tagname:=TabFolder")'
LIQ_ChargeOff_book_Balance_Update='JavaWindow("title:=.*Loan Chargeoff Book Balance.*").JavaMenu("label:=Options").JavaMenu("label:=Update")'
LIQ_Fixed_Rate_Options_Update='JavaWindow("title:=.*Loan Chargeoff Book Balance.*").JavaMenu("label:=Options").JavaMenu("label:=Update")'
LIQ_ChargeOff_book_Balance_Workflow='JavaWindow("title:=.*Loan Chargeoff Book Balance.*").JavaTree("attached text:=Drill down to perform Workflow item")'
LIQ_Fixed_RateOptions_Update='JavaWindow("title:=Fixed Rate Option Loan.*").JavaMenu("label:=Options").JavaMenu("label:=Update")'
LIQ_Fixed_Rate_Options_LenderShares='JavaWindow("title:=.*Loan.*Active.*").JavaMenu("label:=Options").JavaMenu("label:=View Lender Shares")'
LIQ_Fixed_Rate_Options_chargeOff_book_Balance='JavaWindow("title:=.*Loan.*Active.*").JavaMenu("label:=Options").JavaMenu("label:=Chargeoff Book Balance")'
LIQ_Chargeoff_Book_Balance_Options_Loan='JavaWindow("title:=.*Loan Chargeoff Book Balance.*").JavaMenu("label:=Options").JavaMenu("label:=Loan Notebook.*")'

### Fixed Rate Option Loan Window ###
LIQ_FixedRateOptionLoan_Window_PerformingStatus = 'JavaWindow("title:=.*Loan.*ctive.*").JavaStaticText("attached text:=${PerformmingStatusToVerify}")'

###LIQ Writeoff Book Balance###
LIQ_WriteOff_Legal_Balance_Windo = 'JavaWindow("title:=.*Loan Writeoff Legal Balance.*")'
LIQ_Writeoff_Legal_Balance_Tab = 'JavaWindow("title:=.*Loan Writeoff Legal Balance.*").JavaTab("tagname:=TabFolder")'
LIQ_Select_WriteOff_Legal_Balance = 'JavaWindow("title:=.*Loan.*Active.*").JavaMenu("label:=Options").JavaMenu("label:=Writeoff Legal Balance")'
LIQ_Writeoff_Legal_Balance_Requested_Field = 'JavaWindow("title:=.*Loan Writeoff Legal Balance.*").JavaEdit("attached text:=Requested:")'
LIQ_Writeoff_Legal_Balance_Effective_Date = 'JavaWindow("title:=.*Loan Writeoff Legal Balance.*").JavaEdit("attached text:=Effective Date:")'
LIQ_Writeoff_Legal_Balance_View_Update_Portfolio_Shares = 'JavaWindow("title:=.*Loan Writeoff Legal Balance.*").JavaMenu("label:=Options").JavaMenu("label:=View/Update Portfolio Shares")'
LIQ_Writeoff_Legal_Balance_Workflow = 'JavaWindow("title:=.*Loan Writeoff Legal Balance.*").JavaTree("attached text:=Drill down to perform Workflow item")'
LIQ_Writeoff_Legal_Balance_Loan_NoteBook = 'JavaWindow("title:=.*Loan Writeoff Legal Balance.*").JavaMenu("label:=Options").JavaMenu("label:=Loan Notebook")'
LIQ_Writeoff_Legal_Balance_InquiryMode_Button = 'JavaWindow("title:=.*Loan Writeoff Legal Balance.*").JavaButton("attached text:=Notebook in Inquiry Mode - F7")'
LIQ_Writeoff_Legal_Balance_LegalAmount = 'JavaWindow("title:=.*Loan Writeoff Legal Balance.*").JavaEdit("index:=2")'
LIQ_Writeoff_Legal_Balance_BookAmount = 'JavaWindow("title:=.*Loan Writeoff Legal Balance.*").JavaEdit("index:=3")'
LIQ_Writeoff_Legal_Balance_PortfolioShares_OK_Button = 'JavaWindow("title:=Shares for.*").JavaButton("attached text:=OK")'

### LIQ Shares For Writeoff Legal Balance ###
LIQ_Shares_Writeoff_LegalBalance_Window='JavaWindow("title:=Shares.*Loan Writeoff Legal Balance.*")'
LIQ_Shares_Writeoff_Legal_Balance_OK_Button='JavaWindow("title:=Shares.*Loan Writeoff Legal Balance.*").JavaButton("label:=OK")'
LIQ_LoanNotebook_PerformingStatus_FullyChargedOff_Text = 'JavaWindow("title:=.*Loan.*Active.*").JavaStaticText("text:=Partially/Fully Charged-Off")'

### Libor Option ###
LIQ_PendingTab_Javatree ='JavaWindow("title:=.*Loan.*Active.*").JavaTree("attached text:=Pending Transactions")'
LIQ_LiborOptionLoan_Window = 'JavaWindow("title:=.*Libor Option Loan .*")'
LIQ_LiborOptionLoan_Tab = 'JavaWindow("title:=.*Libor Option Loan .*").JavaTab("tagname:=TabFolder")'
LIQ_LiborOptionLoan_Event_JavaTree = 'JavaWindow("title:=Libor Option Loan .*").JavaTree("attached text:=Select event to view details")'

### Loan Payment For Discount Loan ###
LIQ_LoanNoteBook_Option_Payment='JavaWindow("title:=.*Loan.*ctive.*").JavaMenu("label:=Options").JavaMenu("label:=Payment")'
LIQ_LoanNoteBook_BorrowerBaseRate='JavaWindow("title:=.*Loan.*ctive.*").JavaEdit("labeled_containers_path:=Tab:Rates;Group:Borrower Rates;")'
LIQ_LoanNotebook_CycleSharesAdjustments='JavaWindow("title:=.*Loan.*ctive.*").JavaButton("attached text:=Cycle Shares Adjustment")'
LIQ_LoanNotebook_Accrual_Tree='JavaWindow("title:=.*Loan.*ctive.*").JavaTree("attached text:=Cycles:")'

### LIQ - Troubled Debt Restructuring Type Change ###
LIQ_LoanNotebook_General_Tab = 'JavaWindow("title:=.*Libor Option Loan.*").JavaTab("tagname:=TabFolder")'
LIQ_Select_TroubledDebtRestructuringTypeChangeTransaction = 'JavaWindow("title:=.*Loan.*Active.*").JavaMenu("label:=Options").JavaMenu("label:=Troubled Debt Restructuring Type Change Transaction")'
LIQ_TroubledDebtRestructuringType_AwaitingSendToApproval_Window = 'JavaWindow("title:=.*Awaiting Send To Approval.*")'
LIQ_TroubledDebtRestructuringType_AwaitingSendToApproval_Tab = 'JavaWindow("title:=.*Awaiting Send To Approval.*").JavaTab("text:=General")'
LIQ_TroubledDebtRestructuringType_dropdown = 'JavaWindow("title:=.*Awaiting Send To Approval.*").JavaList("index:=0")'
LIQ_TroubledDebtRestructuringTypeChange_dropdown = 'JavaWindow("title:=.*Awaiting Send To Approval.*").JavaList("index:=1")'
LIQ_TroubledDebtRestructuringTypeChange_InquiryMode_Button = 'JavaWindow("title:=.*Troubled Debt Restructuring.*").JavaButton("attached text:=Notebook in Inquiry Mode - F7")'
LIQ_TroubledDebtRestructuringTypeChange_Window = 'JavaWindow("title:=Released Troubled Debt Restructuring Type Change Transaction")'
LIQ_TroubledDebtRestructuringTypeChange_Tab = 'JavaWindow("title:=Released Troubled Debt Restructuring Type Change Transaction").JavaTab("tagname:=TabFolder")'
LIQ_TroubledDebtRestructuringTypeChange_Event_List = 'JavaWindow("title:=Released Troubled Debt Restructuring Type Change Transaction").JavaTree("attached text:=Select event to view details")'
LIQ_TroubledDebtRestructuringTypeChange_Options_LoanNotebook = 'JavaWindow("title:=Released Troubled Debt Restructuring Type Change Transaction").JavaMenu("label:=Options").JavaMenu("label:=Loan Notebook")'
LIQ_TroubledDebtRestructuringTypeChange_Codes_Tab_Details_Text = 'JavaWindow("title:=.*Loan.*ctive.*").JavaStaticText("index:=19")'
LIQ_TroubledDebtRestructuringTypeChange_Codes_History_Button = 'JavaWindow("title:=.*Libor Option Loan.*").JavaButton("index:=4", "enabled:=1")'
LIQ_TroubledDebtRestructuringTypeChange_Codes_History_TableCell = 'JavaWindow("title:=.*Troubled Debt Restructuring Type.*History").JavaTree("tagname:=Tree")'
LIQ_TroubledDebtRestructuringTypeChange_Codes_History_Window = 'JavaWindow("title:=.*Troubled Debt Restructuring Type.*History")'
LIQ_TroubledDebtRestructuringType_AwaitingSendToApproval_Workflow_JavaTree = 'JavaWindow("title:=.*Awaiting Send To Approval.*").JavaTree("attached text:=Drill down to perform Workflow item")'

### Inactive Loan Window ####
LIQ_InactiveLoan_Window = 'JavaWindow("title:=.*Loan.*Inactive.*")'
LIQ_InactiveLoan_Tab = 'JavaWindow("title:=.*Loan.*Inactive.*").JavaTab("tagname:=TabFolder")'

###Lenders Shares For Window - Loan Notebook###
LIQ_LenderSharesFor_Window = 'JavaWindow("title:=Shares for.*")'
LIQ_LenderSharesFor_Participants_Javatree = 'JavaWindow("title:=Shares for.*").JavaTree("attached text:=Drill Down for Participation Detail")'
LIQ_LenderSharesFor_PartShare_Window = 'JavaWindow("title:=Participation Share")'
LIQ_LenderSharesFor_PartShare_ActualAmt_Field = 'JavaWindow("title:=Participation Share").JavaEdit("attached text:=LENDLEGAL17100 / BLOGGS")'
LIQ_LenderSharesFor_PartShare_ActualAmt_Cancel_Button = 'JavaWindow("title:=Participation Share").JavaButton("attached text:=Cancel")'
LIQ_Interest_Options_LoanNotebook = 'JavaWindow("title:=.* Interest.*","displayed:=1").JavaMenu("label:=Options").JavaMenu("label:=Loan Notebook")'