### Collateral Management Window
LIQ_CollateralManagement_Window = 'JavaWindow("title:=Collateral Management")'
LIQ_CollateralManagement_List = 'JavaWindow("title:=Collateral Management").JavaList("attached text:=Drill down to select")'
LIQ_CollateralManagement_OK_Button = 'JavaWindow("title:=Collateral Management").JavaButton("attached text:=OK")'

### Collateral Item Selection Window
LIQ_CollateralItemSelection_Window = 'JavaWindow("title:=.*Collateral Item Select.*")'
LIQ_CollateralItemSelection_Type_List = 'JavaWindow("title:=.*Collateral Item Select.*").JavaList("attached text:=Type:")'
LIQ_CollateralItemSelection_SubType_List = 'JavaWindow("title:=.*Collateral Item Select.*").JavaList("attached text:=Subtype:")'
LIQ_CollateralItemSelection_OK_Button = 'JavaWindow("title:=.*Collateral Item Select.*").JavaButton("attached text:=OK")'
LIQ_CollateralItemSelection_Search_Button = 'JavaWindow("title:=.*Collateral Item Select.*").JavaButton("attached text:=Search")'
LIQ_CollateralItemSelection_New_RadioButton = 'JavaWindow("title:=.*Collateral Item Select.*").JavaRadioButton("attached text:=New")'
LIQ_CollateralItemSelection_Existing_RadioButton = 'JavaWindow("title:=.*Collateral Item Select.*").JavaRadioButton("attached text:=Existing")'
LIQ_CollateralItemSelection_IdentifiedBy_Dropdown = 'JavaWindow("title:=.*Collateral Item Select.*").JavaList("attached text:=Identify By:")'
LIQ_CollateralItemSelection_IdentifiedBy_TextField = 'JavaWindow("title:=.*Collateral Item Select.*").JavaEdit("tagname:=Text","index:=1")'

### Collateral Item Window
LIQ_CollateralItem_Window = 'JavaWindow("title:=Collateral Item")'
LIQ_CollateralItem_CusipId_TextField = 'JavaWindow("title:=Collateral Item").JavaEdit("attached text:=CUSIP/ID:")'
LIQ_CollateralItem_Name_TextField = 'JavaWindow("title:=Collateral Item").JavaEdit("attached text:=Name:")'
LIQ_CollateralItem_Description_TextField = 'JavaWindow("title:=Collateral Item").JavaEdit("attached text:=Description:")'
LIQ_CollateralItem_MaturityDate_TextField = 'JavaWindow("title:=Collateral Item").JavaEdit("attached text:=Maturity Date:")'
LIQ_CollateralItem_AdditionalInfo_TextField = 'JavaWindow("title:=Collateral Item").JavaEdit("attached text:=Additional Info:")'
LIQ_CollateralItem_AdvanceRate_TextField = 'JavaWindow("title:=Collateral Item").JavaEdit("index:=5")'
LIQ_CollateralItem_SetPrice_Button = 'JavaWindow("title:=Collateral Item").JavaButton("attached text:=Set Price")'
LIQ_CollateralItem_OK_Button = 'JavaWindow("title:=Collateral Item").JavaButton("attached text:=OK")'
LIQ_CollateralItem_ItemEvents_Button = 'JavaWindow("title:=Collateral Item").JavaButton("attached text:=Item Events")'
LIQ_CollateralItem_MarketCurrency_StaticText = 'JavaWindow("title:=Collateral Item").JavaObject("text:=Price as of.*").JavaStaticText("index:=8")'
LIQ_CollateralItem_MarketPrice_StaticText = 'JavaWindow("title:=Collateral Item").JavaObject("text:=Price as of.*").JavaStaticText("index:=9")'

### Collateral Item Event Window
LIQ_CollateralItemEventsFor_Window = 'JavaWindow("title:=Collateral Item Events For.*")'
LIQ_CollateralItemEventsFor_OK_Button = 'JavaWindow("title:=Collateral Item Events For.*").JavaButton("attached text:=OK")'
LIQ_CollateralItemEventsFor_From_TextField = 'JavaWindow("title:=Collateral Item Events For.*").JavaEdit("index:=0")'
LIQ_CollateralItemEventsFor_To_TextField = 'JavaWindow("title:=Collateral Item Events For.*").JavaEdit("index:=1")'
LIQ_CollateralItemEventsFor_Cancel_Button = 'JavaWindow("title:=Collateral Item Events For.*").JavaButton("attached text:=Cancel")'
LIQ_CollateralItemEventFor_JavaTree = 'JavaWindow("title:=Collateral Item Events For.*").JavaTree("attached text:=Select event to view details")'
LIQ_CollateralItemEventsFor_Exit_Button = 'JavaWindow("title:=Collateral Item Events For.*").JavaButton("attached text:=Exit")'

### Collateral Item List Window
LIQ_CollateralItemList_Window = 'JavaWindow("title:=.*Collateral Item Select.*").JavaWindow("title:=Collateral Item List")'
LIQ_CollateralItemList_JavaTree = 'JavaWindow("title:=.*Collateral Item Select.*").JavaWindow("title:=Collateral Item List").JavaTree("attached text:=Drill down to view detail")'
LIQ_CollateralItemList_Pickup_JavaTree = 'JavaWindow("title:=.*Collateral Item Select.*").JavaWindow("title:=Collateral Item List").JavaTree("attached text:=Please drill down to pick an item.*")'
LIQ_CollateralItemList_Revalue_Button = 'JavaWindow("title:=Collateral Item List").JavaButton("attached text:=Revalue")'

### Collateral Accounts ###
LIQ_CollateralAccounts_Window ='JavaWindow("title:=Collateral Accounts for:.*")'
LIQ_CollateralAccounts_Add_Button = 'JavaWindow("title:=Collateral Accounts for:.*").JavaButton("attached text:=Add")'
LIQ_CollateralAccounts_Exit_Button = 'JavaWindow("title:=Collateral Accounts for:.*").JavaButton("attached text:=Exit")'
LIQ_CollateralAccountsFor_JavaTree = 'JavaWindow("title:=Collateral Accounts for:.*").JavaTree("attached text:=Drill down to select")'
LIQ_CollateralAccountsFor_View_JavaTree = 'JavaWindow("title:=Collateral Accounts for:.*").JavaTree("attached text:=Drill down to view details")'
LIQ_CollateralAccountsFor_OK_Button = 'JavaWindow("title:=Collateral Accounts for:.*").JavaButton("attached text:=OK")'
LIQ_CollateralAccountFor_Window ='JavaWindow("title:=Collateral Account for:.*")'
LIQ_CollateralAccountFor_Notebook_InquiryMode ='JavaWindow("title:=Collateral Account for:.*").JavaButton("attached text:=Notebook in Inquiry Mode - F7")'
LIQ_CollateralAccountFor_Tab ='JavaWindow("title:=Collateral Account for:.*").JavaTab("path:=TabFolder;Shell;")'
LIQ_CollateralAccountFor_Revalue_Button ='JavaWindow("title:=Collateral Account for:.*").JavaButton("attached text:=Revalue")'
LIQ_CollateralAccountFor_MarketValue_StaticText ='JavaWindow("title:=Collateral Account for:.*").JavaObject("text:=Account Values as of.*").JavaStaticText("index:=0")'
LIQ_CollateralAccountFor_EligibleValue_StaticText ='JavaWindow("title:=Collateral Account for:.*").JavaObject("text:=Account Values as of.*").JavaStaticText("index:=3")'
LIQ_CollateralAccountFor_DiscountedEligibleValue_StaticText ='JavaWindow("title:=Collateral Account for:.*").JavaObject("text:=Account Values as of.*").JavaStaticText("index:=4")'
LIQ_CollateralAccountFor_Options_Holdings_Menu = 'JavaWindow("title:=Collateral Account for:.*").JavaMenu("label:=Options").JavaMenu("label:=Holdings")'
LIQ_CollateralAccountFor_Options_Events_Menu = 'JavaWindow("title:=Collateral Account for:.*").JavaMenu("label:=Options").JavaMenu("label:=Events")'
LIQ_CollateralEventsFor_Window ='JavaWindow("title:=Collateral Events For:.*")'
LIQ_CollateralEventsFor_From_DateField ='JavaWindow("title:=Collateral Events For:.*").JavaEdit("index:=0")'
LIQ_CollateralEventsFor_To_DateField ='JavaWindow("title:=Collateral Events For:.*").JavaEdit("index:=1")'
LIQ_CollateralEventsFor_OK_Button ='JavaWindow("title:=Collateral Events For:.*").JavaButton("attached text:=OK")'
LIQ_CollateralEventsFor_Event_JavaTree ='JavaWindow("title:=Collateral Events For:.*").JavaTree("attached text:=Select event to view details")'
LIQ_CollateralEventsFor_Events_Button = 'JavaWindow("title:=Collateral Events For:.*").JavaButton("attached text:=Events")'
LIQ_CollateralEventsFor_Exit_Button = 'JavaWindow("title:=Collateral Events For:.*").JavaButton("attached text:=Exit")'
LIQ_CollateralAccountFor_HideAsOfValues_Checkbox = 'JavaWindow("title:=Collateral Account for:.*").JavaCheckBox("attached text:=Hide.*As.*Of.*Values")'
LIQ_CollateralAccountFor_GrossCollateralAccount = 'JavaWindow("title:=Collateral Account for:.*").JavaStaticText("labeled_containers_path:=Tab:General;Group:Account Values.*","index:=0")'

### Collateral Account Window ###
LIQ_CollateralAccount_Window = 'JavaWindow("title:=Collateral Account for:.*")'
LIQ_CollateralAccount_Name_TextField = 'JavaWindow("title:=Collateral Account for:.*").JavaEdit("index:=0")'
LIQ_CollateralAccount_ReferenceNum_TextField = 'JavaWindow("title:=Collateral Account for:.*").JavaEdit("index:=1")'
LIQ_CollateralAccount_DiscountRate_TextField = 'JavaWindow("title:=Collateral Account for:.*").JavaEdit("index:=2")'
LIQ_CollateralAccount_Currency_List = 'JavaWindow("title:=Collateral Account for:.*").JavaList("index:=0")'
LIQ_CollateralAccount_ExpiryDate_TextField = 'JavaWindow("title:=Collateral Account for:.*").JavaEdit("attached text:=0.00")'
LIQ_CollateralAccount_CollateralContact_Button = 'JavaWindow("title:=Collateral Account for:.*").JavaButton("attached text:=Collateral Contact")'
LIQ_CollateralAccount_Option_Events = 'JavaWindow("title:=Collateral Account for:.*").JavaMenu("label:=Options").JavaMenu("label:=Events")'

### Collateral Events Window ###
LIQ_CollateralEvents_Window = 'JavaWindow("title:=Collateral Events For:.*")'
LIQ_CollateralEvents_From_TextField = 'JavaWindow("title:=Collateral Events For:.*").JavaEdit("index:=0")'
LIQ_CollateralEvents_To_TextField = 'JavaWindow("title:=Collateral Events For:.*").JavaEdit("index:=1")'
LIQ_CollateralEvents_OK_Button = 'JavaWindow("title:=Collateral Events For:.*").JavaButton("attached text:=OK")'
LIQ_CollateralEvents_JavaTree = 'JavaWindow("title:=Collateral Events For:.*").JavaTree("attached text:=Select event to view details")'

### Holding List For Accounts ###
LIQ_HoldingListForCustomer_Window ='JavaWindow("title:=Holding List for Customer:.*")'
LIQ_HoldingListForCustomer_Add_Button = 'JavaWindow("title:=Holding List for Customer:.*").JavaButton("attached text:=Add")'
LIQ_HoldingListForCustomer_Exit_Button = 'JavaWindow("title:=Holding List for Customer:.*").JavaButton("attached text:=Exit")'
LIQ_HoldingListForCustomer_JavaTree = 'JavaWindow("title:=Holding List for Customer:.*").JavaTree("labeled_containers_path:=Group:Holdings.*")'
LIQ_HoldingForAccount_Window ='JavaWindow("title:=.*Holding for Account:.*")'
LIQ_HoldingForAccount_Item_Button = 'JavaWindow("title:=.*Holding for Account:.*").JavaButton("attached text:=Item")'
LIQ_HoldingForAccount_HoldingNumber_TextField = 'JavaWindow("title:=.*Holding for Account:.*").JavaEdit("attached text:=Holding Number:")'
LIQ_HoldingForAccount_Address_Button = 'JavaWindow("title:=.*Holding for Account:.*").JavaButton("attached text:=Address")'
LIQ_HoldingForAccount_Location_List = 'JavaWindow("title:=.*Holding for Account:.*").JavaList("attached text:=Location:")'
LIQ_HoldingForAccount_SetPrice_Button = 'JavaWindow("title:=.*Holding for Account:.*").JavaButton("attached text:=Set Price")'
LIQ_HoldingForAccount_Currency_TextField = 'JavaWindow("title:=.*Holding for Account:.*").JavaEdit("attached text:=Currency:")'
LIQ_HoldingForAccount_UnitPrice_TextField = 'JavaWindow("title:=.*Holding for Account:.*").JavaEdit("attached text:=Unit Price:")'
LIQ_HoldingForAccount_PriceSource_TextField = 'JavaWindow("title:=.*Holding for Account:.*").JavaEdit("attached text:=Price Source:")'
LIQ_HoldingForAccount_PriceDate_TextField = 'JavaWindow("title:=.*Holding for Account:.*").JavaEdit("attached text:=Price Date:")'
LIQ_HoldingForAccount_PriceTime_TextField = 'JavaWindow("title:=.*Holding for Account:.*").JavaEdit("attached text:=Price Time:")'
LIQ_HoldingForAccount_OK_Button = 'JavaWindow("title:=.*Holding for Account:.*").JavaButton("attached text:=OK")'
LIQ_HoldingForAccount_CoverObligor_Button = 'JavaWindow("title:=.*Holding for Account:.*").JavaButton("attached text:=Cover Obligor")'
LIQ_HoldingForAccount_NumberOfUnits_TextField = 'JavaWindow("title:=.*Holding for Account:.*").JavaEdit("attached text:=Number of Units:")'
LIQ_HoldingForAccount_AdvanceRates_TextField = 'JavaWindow("title:=.*Holding for Account:.*").JavaEdit("attached text:=Advance Rate:")'
LIQ_HoldingForAccount_CollateralUnitSize_Combobox = 'JavaWindow("title:=.*Holding for Account:.*").JavaList("attached text:=Collateral Unit Size:")'
LIQ_HoldingForAccount_Item_TextField = 'JavaWindow("title:=.*Holding for Account:.*").JavaEdit("tagname:=Text","index:=3")'
LIQ_HoldingForAccount_CollateralDesc_TextField = 'JavaWindow("title:=.*Holding for Account:.*").JavaEdit("attached text:=Collateral Desc:")'
LIQ_HoldingForAccount_CollateralType_TextField = 'JavaWindow("title:=.*Holding for Account:.*").JavaStaticText("labeled_containers_path:=Group:Collateral Type;","index:=5")'
LIQ_HoldingForAccount_CollateralSubtype_TextField = 'JavaWindow("title:=.*Holding for Account:.*").JavaStaticText("labeled_containers_path:=Group:Subtype;","index:=1")'
LIQ_HoldingForAccount_CustomerShortName_TextField = 'JavaWindow("title:=.*Holding for Account:.*").JavaEdit("tagname:=Text","index:=2")'
LIQ_HoldingForAccount_CustomerID_TextField = 'JavaWindow("title:=.*Holding for Account:.*").JavaStaticText("index:=4")'
LIQ_HoldingForAccount_CommericalRisk_CoverPercentage_TextField = 'JavaWindow("title:=.*Holding for Account:.*").JavaEdit("attached text:=Cover Percentage:","index:=1")'
LIQ_HoldingForAccount_CommericalRisk_Amount_TextField = 'JavaWindow("title:=.*Holding for Account:.*").JavaEdit("attached text:=Amount:","index:=1")'
LIQ_HoldingForAccount_CommericalRisk_MaxInsuredAmount_TextField = 'JavaWindow("title:=.*Holding for Account:.*").JavaEdit("attached text:=Max Insured Amount:","index:=1")'
LIQ_HoldingForAccount_CommericalRisk_Currency_Combobox = 'JavaWindow("title:=.*Holding for Account:.*").JavaList("attached text:=Currency:","index:=1")'
LIQ_HoldingForAccount_TransferRisk_CoverPercentage_TextField = 'JavaWindow("title:=.*Holding for Account:.*").JavaEdit("attached text:=Cover Percentage:","index:=0")'
LIQ_HoldingForAccount_TransferRisk_Amount_TextField = 'JavaWindow("title:=.*Holding for Account:.*").JavaEdit("attached text:=Amount:","index:=0")'
LIQ_HoldingForAccount_TransferRisk_MaxInsuredAmount_TextField = 'JavaWindow("title:=.*Holding for Account:.*").JavaEdit("attached text:=Max Insured Amount:","index:=0")'
LIQ_HoldingForAccount_TransferRisk_Currency_Combobox = 'JavaWindow("title:=.*Holding for Account:.*").JavaList("attached text:=Currency:","index:=0")'
LIQ_HoldingForAccount_Item_Detail_Button = 'JavaWindow("title:=.*Holding for Account:.*").JavaButton("attached text:=Item Detail","index:=0")'
LIQ_HoldingForAccount_CustodianLocation_Button = 'JavaWindow("title:=.*Holding for Account:.*").JavaButton("attached text:=Custodian Location")'
LIQ_HoldingForAccount_Mutual_NumberOfUnits_TextField = 'JavaWindow("title:=.*Holding for Account:.*").JavaObject("path:=Composite;Shell;").JavaEdit("index:=6")'
LIQ_HoldingForAccount_Currency_StaticText = 'JavaWindow("title:=.*Holding for Account:.*").JavaObject("text:=Price as of.*").JavaStaticText("index:=5")'
LIQ_HoldingForAccount_PurchasePrice_StaticText = 'JavaWindow("title:=.*Holding for Account:.*").JavaObject("text:=Price as of.*").JavaStaticText("index:=7")'
LIQ_HoldingForAccount_Events_Button = 'JavaWindow("title:=.*Holding for Account:.*").JavaButton("attached text:=Events")'

### Cover Obligor - Choose An option Window ###
LIQ_CoverObligor_ChooseAnOption_Window = 'JavaWindow("title:=Choose an option")'
LIQ_CoverObligor_ChooseAnOption_ViewObligor_RadioButton = 'JavaWindow("title:=Choose an option").JavaRadioButton("attached text:=View Obligor")'
LIQ_CoverObligor_ChooseAnOption_AddChangeObligor_RadioButton = 'JavaWindow("title:=Choose an option").JavaRadioButton("attached text:=Add/Change Obligor")'
LIQ_CoverObligor_ChooseAnOption_OK_Button = 'JavaWindow("title:=Choose an option").JavaButton("attached text:=OK")'
LIQ_CoverObligor_ChooseAnOption_Cancel_Button = 'JavaWindow("title:=Choose an option").JavaButton("attached text:=Cancel")'

### Address For Holding ###
LIQ_AddressForHolding_Window = 'JavaWindow("title:=.*Address For Holding.*")'
LIQ_AddressForHolding_Line1_TextField = 'JavaWindow("title:=.*Address For Holding.*").JavaEdit("attached text:=Line1:")'
LIQ_AddressForHolding_Line2_TextField = 'JavaWindow("title:=.*Address For Holding.*").JavaEdit("attached text:=Line2:")'
LIQ_AddressForHolding_Line3_TextField = 'JavaWindow("title:=.*Address For Holding.*").JavaEdit("attached text:=Line3:")'
LIQ_AddressForHolding_Line4_TextField = 'JavaWindow("title:=.*Address For Holding.*").JavaEdit("attached text:=Line4:")'
LIQ_AddressForHolding_City_TextField = 'JavaWindow("title:=.*Address For Holding.*").JavaEdit("attached text:=City:")'
LIQ_AddressForHolding_ZipPostalCode_TextField = 'JavaWindow("title:=.*Address For Holding.*").JavaEdit("attached text:=Zip/Postal Code:")'
LIQ_AddressForHolding_Country_List = 'JavaWindow("title:=.*Address For Holding.*").JavaList("attached text:=Country:")'
LIQ_AddressForHolding_State_List = 'JavaWindow("title:=.*Address For Holding.*").JavaList("attached text:=State:")'
LIQ_AddressForHolding_Ok_Button = 'JavaWindow("title:=.*Address For Holding.*").JavaButton("attached text:=OK")'
LIQ_AddressForHolding_Delete_Button = 'JavaWindow("title:=.*Address For Holding.*").JavaButton("attached text:=Delete")'
LIQ_AddressForHolding_Cancel_Button = 'JavaWindow("title:=.*Address For Holding.*").JavaButton("attached text:=Cancel")'

### Set Price For Window ###
LIQ_SetPriceFor_Window = 'JavaWindow("title:=Set Price for.*")'
LIQ_SetPriceFor_MarketQuotationUnitSize_Dropdown = 'JavaWindow("title:=Set Price for.*").JavaList("tagname:=Combo", "index:=1")'
LIQ_SetPriceFor_MarketQuotationNoOfUnits_Dropdown = 'JavaWindow("title:=Set Price for.*").JavaEdit("tagname:=Text", "index:=5")'
LIQ_SetPriceFor_MarketCurrency_Dropdown = 'JavaWindow("title:=Set Price for.*").JavaList("attached text:=.*Currency:")'
LIQ_SetPriceFor_MarketPrice_TextField = 'JavaWindow("title:=Set Price for.*").JavaEdit("attached text:=.*Price:")'
LIQ_SetPriceFor_ExchangeCode_TextField = 'JavaWindow("title:=Set Price for.*").JavaEdit("attached text:=Exchange Code:")'
LIQ_SetPriceFor_PriceSource_TextField = 'JavaWindow("title:=Set Price for.*").JavaEdit("attached text:=Price Source:")'
LIQ_SetPriceFor_PriceDate_TextField = 'JavaWindow("title:=Set Price for.*").JavaEdit("attached text:=Price Date:")'
LIQ_SetPriceFor_PriceTime_TextField = 'JavaWindow("title:=Set Price for.*").JavaEdit("attached text:=Price Time:")'
LIQ_SetPriceFor_OK_Button = 'JavaWindow("title:=Set Price for.*").JavaButton("attached text:=OK")'
LIQ_SetPriceFor_PurchaseCurrency_Dropdown = 'JavaWindow("title:=Set Price for.*").JavaList("attached text:=Currency:")'
LIQ_SetPriceFor_PurchasePrice_TextField = 'JavaWindow("title:=Set Price for.*").JavaEdit("attached text:=.*Price:")'
LIQ_SetPriceFor_PurchaseQuotationNoOfUnits_Dropdown = 'JavaWindow("title:=Set Price for.*").JavaList("attached text:=Quotation Unit Size:")'

### SELECTED ACTION_DEAL, ACTION_FACILITY OR ACTION_OUTSTANDING IS NOT A MEMBER Pop-Up Window ###
LIQ_SelectedDealFacilityOrOutstandingIsNotAMember_PopupWindow = 'JavaWindow("title:=Selected deal, facility or outstanding is not a member")'
LIQ_SelectedDealFacilityOrOutstandingIsNotAMember_CreateGroup_Button = 'JavaWindow("title:=Selected deal, facility or outstanding is not a member").JavaButton("attached text:=Create Group")'

### Collateral for Deal Window ###
LIQ_CollateralForDeal_Window = 'JavaWindow("title:=Collateral for Deal:.*")'
LIQ_CollateralForDeal_CollateralAgent_Button = 'JavaWindow("title:=Collateral for Deal:.*").JavaButton("attached text:=Collateral Agent")'
LIQ_CollateralForDeal_CollateralAgent_Textfield = 'JavaWindow("title:=Collateral for Deal:.*").JavaEdit("index:=2")'
LIQ_CollateralForDeal_CollateralAdministrator_Button = 'JavaWindow("title:=Collateral for Deal:.*").JavaButton("attached text:=Collateral Administrator")'
LIQ_CollateralForDeal_CollateralAdministrator_Textfield = 'JavaWindow("title:=Collateral for Deal:.*").JavaEdit("index:=3")'
LIQ_CollateralForDeal_PercentSecured_Textfield = 'JavaWindow("title:=Collateral for Deal:.*").JavaEdit("attached text:=Percent Secured:")'
LIQ_CollateralForDeal_Threshold_Textfield = 'JavaWindow("title:=Collateral for Deal:.*").JavaEdit("index:=0")'
LIQ_CollateralForDeal_PrimaryCollateralType_Dropdown = 'JavaWindow("title:=Collateral for Deal:.*").JavaList("index:=0")'
LIQ_CollateralForDeal_Currency_Dropdown = 'JavaWindow("title:=Collateral for Deal:.*").JavaList("attached text:=Currency:")'
LIQ_CollateralForDeal_Department_Dropdown = 'JavaWindow("title:=Collateral for Deal:.*").JavaList("attached text:=Department:")'
LIQ_CollateralForDeal_Branch_Dropdown = 'JavaWindow("title:=Collateral for Deal:.*").JavaList("attached text:=Branch:")'
LIQ_CollateralForDeal_AddMember_Button = 'JavaWindow("title:=Collateral for Deal:.*").JavaObject("path:=Composite;Shell;").JavaObject("path:=Group;Composite;Shell;","attached text:=Collateral Group Name:").JavaButton("attached text:=Add Member")'
LIQ_CollateralForDeal_CollateralGroupMember_JavaTree = 'JavaWindow("title:=Collateral for Deal:.*").JavaObject("path:=Composite;Shell;").JavaObject("path:=Group;Composite;Shell;","attached text:=Collateral Group Name:").JavaTree("attached text:=Collateral Group Name:")'
LIQ_CollateralForDeal_AddLink_Button = 'JavaWindow("title:=Collateral for Deal:.*").JavaObject("path:=Composite;Shell;").JavaObject("path:=Group;Composite;Shell;","attached text:=Drill down to view details").JavaButton("attached text:=Add Link")'
LIQ_CollateralForDeal_CollateralAccounts_JavaTree = 'JavaWindow("title:=Collateral for Deal:.*").JavaObject("path:=Composite;Shell;").JavaObject("path:=Group;Composite;Shell;","attached text:=Drill down to view details").JavaTree("attached text:=Drill down to view details")'
LIQ_CollateralForDeal_OK_Button = 'JavaWindow("title:=Collateral for Deal:.*").JavaButton("attached text:=OK")'
LIQ_CollateralForDeal_RemoveMember_Button = 'JavaWindow("title:=Collateral for Deal:.*").JavaObject("path:=Composite;Shell;").JavaObject("path:=Group;Composite;Shell;","attached text:=Collateral Group Name:").JavaButton("attached text:=Remove Member")'

### Collateral Administrator Selection List Window ###
LIQ_CollateralAdministratorSelectionList_Window = 'JavaWindow("title:=Collateral Administrator Selection List")'
LIQ_CollateralAdministratorSelectionList_JavaTree = 'JavaWindow("title:=Collateral Administrator Selection List").JavaTree("attached text:=Search:")'
LIQ_CollateralAdministratorSelectionList_OK_Button = 'JavaWindow("title:=Collateral Administrator Selection List").JavaButton("attached text:=OK")'

### Collateral Group Member Type Window ###
LIQ_CollateralGroupMemberType_Window = 'JavaWindow("title:=Collateral Group Member Type")'
LIQ_CollateralGroupMemberType_OK_Button = 'JavaWindow("title:=Collateral Group Member Type").JavaButton("attached text:=OK")'

### SELECTED ACTION_DEAL, ACTION_FACILITY OR ACTION_OUTSTANDING WILL BE REMOVED Pop-Up Window ###
LIQ_SelectedDealFacilityOrOutstandingWillBeRemoved_PopupWindow = 'JavaWindow("title:=Selected deal, facility or outstanding will be removed")'
LIQ_SelectedDealFacilityOrOutstandingWillBeRemoved_Remove_Button = 'JavaWindow("title:=Selected deal, facility or outstanding will be removed").JavaButton("attached text:=Remove")'

### Collateral vs. Outstandings ###
LIQ_Collateral_Outstandings_LineItems_JavaTree = 'JavaWindow("title:=Collateral vs\. Outstandings").JavaTree("displayed:=1")'