### Payment Notices ###
LIQ_Notice_PaymentIntentNotice_Window = 'JavaWindow("title:=.* Payment Notice Group.*")'
LIQ_Notice_PaymentIntentNotice_Exit_Button = 'JavaWindow("title:=.* Payment Notice Group.*").JavaButton("attached text:=Exit")' 
LIQ_Notice_PaymentIntentNotice_Information_Table = 'JavaWindow("title:=.* Payment Notice Group.*", "displayed:=1").JavaTree("attached text:=Drill down to mark notices")'
LIQ_Notice_PaymentIntentNotice_Send_Button = 'JavaWindow("title:=.* Payment Notice Group.*").JavaButton("attached text:=Send")'
LIQ_Notice_PaymentIntentNotice_EditHighlightedNotice_Button = 'JavaWindow("title:=.* Payment Notice Group.*").JavaButton("attached text:=Edit Highlighted Notices")'
LIQ_Notice_PaymentIntentNotice_Edit_Window = 'JavaWindow("title:=.* Payment Notice created.*")'
LIQ_Notice_PaymentIntentNotice_Edit_Email = 'JavaWindow("title:=.* Payment Notice created.*").JavaEdit("attached text:=E-mail:")'

### Intent Notices ####
LIQ_IntentNotice_Window = 'JavaWindow("title:=.* Notice Group.*", "displayed:=1")'
LIQ_IntentNotice_Exit_Button = 'JavaWindow("title:=.* Notice Group.*", "displayed:=1").JavaButton("attached text:=Exit")' 
LIQ_IntentNotice_Information_Table = 'JavaWindow("title:=.* Notice Group.*", "displayed:=1").JavaTree("attached text:=Drill down to mark notices")'
LIQ_IntentNotice_Send_Button = 'JavaWindow("title:=.* Notice Group.*", "displayed:=1").JavaButton("attached text:=Send")'
LIQ_IntentNotice_EditHighlightedNotice_Button = 'JavaWindow("title:=.* Notice Group.*", "displayed:=1").JavaButton("attached text:=Edit Highlighted Notices")'
LIQ_IntentNotice_Edit_Window = 'JavaWindow("title:=.* Notice created.*")'
LIQ_IntentNotice_Edit_Email = 'JavaWindow("title:=.* Notice created.*").JavaEdit("attached text:=E-mail:")' 

### Notice ###
LIQ_Notice_Exit_Button = 'JavaWindow("title:=.* Notice.*", "displayed:=1").JavaButton("attached text:=Exit")'
LIQ_Notice_Information_Table = 'JavaWindow("title:=.* Notice.*", "displayed:=1").JavaTree("attached text:=Drill down to mark notices")'
LIQ_Notice_Send_Button = 'JavaWindow("title:=.* Notice.*").JavaButton("attached text:=Send")'
LIQ_Notice_EditHighlightedNotice_Button = 'JavaWindow("title:=.* Notice Group.*").JavaButton("attached text:=.*Highlighted Notices")'
LIQ_Notice_IntentNotice_Window = 'JavaWindow("title:=.* Payment Notice created.*")'
LIQ_Notice_IntentNotice_Email = 'JavaWindow("title:=.* Payment Notice created.*").JavaEdit("attached text:=E-mail:")'

### Payment Window ####
LIQ_Payment_Window = 'JavaWindow("title:=.* .* Payment .*")'
LIQ_Payment_Options_Cashflow = 'JavaWindow("title:=.* .* Payment .*").JavaMenu("label:=Options").JavaMenu("label:=Cashflow")'
LIQ_Payment_Options_PaperClipNotebook = 'JavaWindow("title:=.* .* Payment .*").JavaMenu("label:=Options").JavaMenu("label:=Paper Clip Notebook")'
LIQ_Payment_Queries_GLEntries = 'JavaWindow("title:=.* .* Payment .*").JavaMenu("label:=Queries").JavaMenu("label:=GL Entries")'
LIQ_Payment_EffectiveDate_Textfield = 'JavaWindow("title:=.* .* Payment .*").JavaEdit("attached text:=Effective Date:")'
LIQ_Payment_File_Save = 'JavaWindow("title:=.* .* Payment .*").JavaMenu("label:=File").JavaMenu("label:=Save")'    
LIQ_Payment_CashflowFromBorrower_RadioButton ='JavaWindow("title:=.* .* Payment .*").JavaRadioButton("attached text:=From Borrower")'
LIQ_Payment_CashflowFromAgent_RadioButton ='JavaWindow("title:=.* Payment.*").JavaRadioButton("attached text:=From Agent")'
LIQ_Payment_AwaitingApproval_Status_Window = 'JavaWindow("title:=.*Payment .*Awaiting Approval.*")'
LIQ_Payment_Released_Status_Window = 'JavaWindow("title:=.*Payment .*Released.*")'
LIQ_Payment_WorkflowItems_Release_Null = 'JavaWindow("title:=.* .* Payment .*").JavaTree("attached text:=.*Workflow .*", "items count:=0")'
LIQ_Payment_PrincipalRequestedAmt_Textfield = 'JavaWindow("title:=.* .* Payment .*").JavaEdit("attached text:=Requested:")'
LIQ_Payment_ProjectedCycleDue_Amount = 'JavaWindow("title:=.* .* Payment .*").JavaEdit("tagname:=Text", "x:=231", "y:=84")'
LIQ_Payment_WorkflowItems = 'JavaWindow("title:=.* .* Payment .*").JavaTree("attached text:=.*Workflow .*")'
LIQ_Payment_Events_JavaTree = 'JavaWindow("title:=.* Payment .*").JavaTree("attached text:=Select event to view details")'
LIQ_Payment_Tab = 'JavaWindow("title:=.* .* Payment.*").JavaTab("class description:=tab")'
LIQ_Payment_Options_Payment = 'JavaWindow("title:=.* Payment.*").JavaMenu("label:=Queries").JavaMenu("label:=GL Entries")'
LIQ_Payment_GLEntries_Window = 'JavaWindow("title:=GL Entries.*")'
LIQ_Payment_GLEntries_Exit_Button = 'JavaWindow("title:=GL Entries.*").JavaButton("attached text:=Exit")'
LIQ_Payment_RequestedAmount_Textfield = 'JavaWindow("title:=.* Payment.*", "displayed:=1").JavaEdit("labeled_containers_path:=.*Amounts.*", "index:=0")'
LIQ_Payment_CycleDue_Amount = 'JavaWindow("title:=.* Payment.*").JavaEdit("tagname:=Text", "x:=231", "y:=84")'
LIQ_Payment_Alias_Text = 'JavaWindow("title:=.* .* Payment .*").JavaStaticText("index:=3")'

### Interest Payment Notebook ###
LIQ_InterestPayment_Window = 'JavaWindow("title:=.* Interest Payment.*")'
LIQ_InterestPayment_EffectiveDate_Textfield = 'JavaWindow("title:=.* Interest Payment.*").JavaEdit("attached text:=Effective Date:")'
LIQ_InterestPayment_FileSave_Menu = 'JavaWindow("title:=.* Interest Payment.*").JavaMenu("label:=File").JavaMenu("label:=Save")'
LIQ_InterestPayment_FileExit_Menu = 'JavaWindow("title:=.* Interest Payment.*").JavaMenu("label:=File").JavaMenu("label:=Exit")'
LIQ_InterestPayment_CurrentCycDue_Text = 'JavaWindow("title:=.* Interest Payment.*").JavaEdit("tagname:=Text","labeled_containers_path:=Tab:General;Group: Amounts ;","index:=3")'
LIQ_InterestPayment_RequestedAmount_Textfield = 'JavaWindow("title:=.* Interest Payment.*").JavaEdit("tagname:=Text","labeled_containers_path:=Tab:General;Group: Amounts ;","index:=0")'
LIQ_InterestPayment_DueDate_TextField = 'JavaWindow("title:=.* Interest Payment.*").JavaStaticText("labeled_containers_path:=Tab:General;Group:Cycle;","index:=5")'
LIQ_InterestPayment_StartDate_TextField = 'JavaWindow("title:=.* Interest Payment.*").JavaStaticText("labeled_containers_path:=Tab:General;Group:Cycle;","index:=3")'
LIQ_InterestPayment_EndDate_TextField = 'JavaWindow("title:=.* Interest Payment.*").JavaStaticText("labeled_containers_path:=Tab:General;Group:Cycle;","index:=4")'
LIQ_InterestPayment_Tab = 'JavaWindow("title:=.* Interest Payment.*").JavaTab("toolkit class:=.*TabFolder")'
LIQ_InterestPayment_GLEntries = 'JavaWindow("title:=.* Interest Payment.*").JavaMenu("label:=Queries").JavaMenu("label:=GL Entries")'
LIQ_InterestPayment_Pending_Tab= 'JavaWindow("title:=.* Interest Payment.*","displayed:=1").JavaTab("tagname:=TabFolder")'
LIQ_InterestPayment_WorkflowItems_AwaitingSend_List = 'JavaWindow("title:=.* Interest Payment.*","displayed:=1").JavaTree("attached text:=Drill down to perform Workflow item")'
LIQ_InterestPayment_Cashflow_Ok_Button = 'JavaWindow("title:=Cashflows For.*").JavaButton("attached text:=OK")'
LIQ_InterestPayment_Events_Tree = 'JavaWindow("title:=.* Interest Payment.*","displayed:=1").JavaTree("attached text:=Select event to view details")'
LIQ_InterestPayment_Cashflow = 'JavaWindow("title:=.* Interest Payment.*").JavaMenu("label:=Options").JavaMenu("label:=Cashflow")'

### Reverse Interest Payment ###
LIQ_ReverseInterestPayment_Window = 'JavaWindow("title:=.*Reverse Interest Payment.*")'
LIQ_ReverseInterestPayment_FileSave_Menu = 'JavaWindow("title:=.*Reverse Interest Payment.*").JavaMenu("label:=File").JavaMenu("label:=Save")'
LIQ_ReverseInterestPayment_Requested_Textfield = 'JavaWindow("title:=.*Reverse Interest Payment.*").JavaEdit("labeled_containers_path:=Tab:General;Group: Amounts ;","index:=0")'
LIQ_ReverseInterestPayment_EffectiveDate_Textfield = 'JavaWindow("title:=.*Reverse Interest Payment.*").JavaEdit("attached text:=Effective Date:")'
LIQ_ReverseInterestPayment_Comment_TextArea = 'JavaWindow("title:=.*Reverse Interest Payment.*").JavaEdit("attached text:=Comment:")'