### Make Selection Window ###
LIQ_MakeSelection_Window = 'JavaWindow("title:=Make Selection")'
LIQ_MakeSelection_OK_Button = 'JavaWindow("title:=Make Selection").JavaButton("label:=OK")'
LIQ_MakeSelection_Cancel_Button = 'JavaWindow("title:=Make Selection").JavaButton(label:=Cancel)'
LIQ_MakeSelection_Deal_RadioButton = 'JavaWindow("title:=Make Selection").JavaObject("tagname:=Group","text:=Choices").JavaRadioButton("attached text:=Deal.*")'
LIQ_MakeSelection_LenderSharesAdjustment_RadioButton = 'JavaWindow("title:=Make Selection").JavaObject("tagname:=Group","text:=Choices").JavaRadioButton("label:=Lender Shares Adjustment")'
LIQ_MakeSelection_ServicingGroupChange_RadioButton = 'JavaWindow("title:=Make Selection").JavaObject("tagname:=Group","text:=Choices").JavaRadioButton("label:=Servicing Group Change")'
LIQ_MakeSelection_PortfolioTransfer_RadioButton = 'JavaWindow("title:=Make Selection").JavaObject("tagname:=Group","text:=Choices").JavaRadioButton("label:=Portfolio Transfer")'
LIQ_MakeSelection_PortfolioSettledDiscount_RadioButton = 'JavaWindow("title:=Make Selection").JavaObject("tagname:=Group","text:=Choices").JavaRadioButton("label:=Portfolio Settled Discount Change")'
LIQ_MakeSelection_PortfolioTradeDate_RadioButton = 'JavaWindow("title:=Make Selection").JavaObject("tagname:=Group","text:=Choices").JavaRadioButton("label:=Portfolio Trade Date Discount Change")'
LIQ_MakeSelection_PortfolioAssignableChange_RadioButton = 'JavaWindow("title:=Make Selection").JavaObject("tagname:=Group","text:=Choices").JavaRadioButton("label:=Portfolio Assignable Change")'
LIQ_MakeSelection_PortfolioDeferredPLChange_RadioButton = 'JavaWindow("title:=Make Selection").JavaObject("tagname:=Group","text:=Choices").JavaRadioButton("label:=Portfolio Deferred P/L Change")'
LIQ_MakeSelection_PortfolioDeferredPLIndicator_RadioButton = 'JavaWindow("title:=Make Selection").JavaObject("tagname:=Group","text:=Choices").JavaRadioButton("label:=Portfolio Deferred P/L Indicator Change")'
LIQ_MakeSelection_PortfolioTransactionCost_RadioButton = 'JavaWindow("title:=Make Selection").JavaObject("tagname:=Group","text:=Choices").JavaRadioButton("label:=Portfolio Transaction Cost Adjustment")'

### Share Adjustment in Facility Window ###
LIQ_ShareAdjustment_Window = 'JavaWindow("title:=Share Adjustment.*")'
LIQ_ShareAdjustment_Tab = 'JavaWindow("title:=Share Adjustment.*").JavaTab("tagname:=TabFolder")'
LIQ_ShareAdjustment_EffectiveDate_Textfield = 'JavaWindow("title:=Share Adjustment.*").JavaEdit("attached text:=Effective Date:")'
LIQ_ShareAdjustment_BuySellPrice_Textfield = 'JavaWindow("title:=Share Adjustment.*").JavaEdit("attached text:=.*Buy/Sell Price:")'
LIQ_ShareAdjustment_Comment_Textfield = 'JavaWindow("title:=Share Adjustment.*").JavaEdit("attached text:=Comment:")'
LIQ_ShareAdjustment_Workflow_Tree = 'JavaWindow("title:=Share Adjustment.*").JavaTree("attached text:=Drill down to perform Workflow item")'
LIQ_ShareAdjustment_File_Save = 'JavaWindow("title:=Share Adjustment.*").JavaMenu("label:=File").JavaMenu("label:=Save")'
LIQ_ShareAdjustment_File_Exit = 'JavaWindow("title:=Share Adjustment.*").JavaMenu("label:=File").JavaMenu("label:=Exit")'
LIQ_ShareAdjustment_Options_ViewUpdateLenderShares = 'JavaWindow("title:=Share Adjustment.*").JavaMenu("label:=Options").JavaMenu("label:=View/Update Lender Shares")'
LIQ_ShareAdjustment_AffectsOutstanding_Checkbox = 'JavaWindow("title:=Share Adjustment.*").JavaCheckBox("attached text:=Affects Outstandings")'
LIQ_ShareAdjustment_DealName_Text ='JavaWindow("title:=Share Adjustment.*").JavaStaticText("index:=7")'
LIQ_ShareAdjustment_FacilityName_Text = 'JavaWindow("title:=Share Adjustment.*").JavaStaticText("x:=140","y:=28")'
LIQ_ShareAdjustment_AmendmentNumber_Text = 'JavaWindow("title:=Share Adjustment.*").JavaStaticText("index:=11")'
LIQ_ShareAdjustmentInFacility = 'JavaWindow("title:=Shares for .*")'
LIQ_ShareAdjustment_Options_FacilityNotebook = 'JavaWindow("title:=Shares for .*").JavaMenu("label:=Options").JavaMenu("label:=Facility Notebook")'
LIQ_ShareAdjustment_Facility_Window = 'JavaWindow("title:=Facility -.*")'
LIQ_ShareAdjustment_Ok_Button = 'JavaWindow("title:=Shares for .*").JavaButton("attached text:=OK")'
LIQ_ShareAdjustment_JavaTree = 'JavaWindow("title:=.*${Notebook_Window}.*","displayed:=1").JavaTree("to_description:=JavaTree")'

### Shares For (Currency) Share Adjustment in Facility Window ###
LIQ_SharesFor_Window = 'JavaWindow("title:=Shares for.*")'
LIQ_SharesFor_Primaries_Tree = 'JavaWindow("title:=Shares for.*").JavaObject("tagname:=Group","text:=Primaries/Assignees").JavaTree("attached text:=Drill Down for Primary/Assignment Detail")'
LIQ_SharesFor_Participants_Tree = 'JavaWindow("title:=Shares for.*").JavaObject("tagname:=Group","text:=Participants").JavaTree("attached text:=Drill Down for Participation Detail")'
LIQ_SharesFor_HostBankShares_Tree = 'JavaWindow("title:=Shares for.*").JavaObject("tagname:=Group","text:=Host bank shares").JavaTree("attached text:=Drill Down for Portfolio Shares")'
LIQ_SharesFor_HostBankShares_ExpenseCode_Tree='JavaWindow("title:=.*The Bank of Nova Scotia.*").JavaTree("attached text:=Drill down to view details")'
LIQ_SharesFor_OK_Button = 'JavaWindow("title:=Shares for.*").JavaButton("label:=OK")'
LIQ_SharesFor_Cancel_Button = 'JavaWindow("title:=Shares for.*").JavaButton("label:=Cancel")'
LIQ_SharesFor_ActualTotal_Text = 'JavaWindow("title:=Shares for.*").JavaObject("tagname:=Group","text:=Primaries/Assignees").JavaEdit("attached text:=Actual Total:")'
LIQ_SharesFor_ActualNetAllTotal_Text = 'JavaWindow("title:=Shares for.*").JavaObject("tagname:=Group","text:=Host bank shares").JavaEdit("attached text:=Actual Net All Total:")'
LIQ_SharesFor_LenderNotebook_Button = 'JavaWindow("title:=Shares for.*").JavaObject("tagname:=Group","text:=Primaries/Assignees").JavaButton("label:=Lender Notebook")'
LIQ_SharesFor_Comment_Button = 'JavaWindow("title:=Shares for.*").JavaButton("attached text:=Comment")'

### Host Bank Shares For Window ###
LIQ_HostBankShareFor_Window = 'JavaWindow("title:=Host Bank Share for.*")'
LIQ_HostBankShareFor_BranchPortfolioExpenseCode_Tree = 'JavaWindow("title:=Host Bank Share for.*").JavaTree("attached text:=Drill down to view/edit")'
LIQ_HostBankShareFor_BranchPortfolioExpenseCode_Details_Tree = 'JavaWindow("title:=Host Bank Share for.*").JavaTree("attached text:=Drill down to view details")'
LIQ_HostBankShareFor_BranchPortfolioExpenseCode_EmptyTree = 'JavaWindow("title:=Host Bank Share for.*").JavaTree("items count:=0")'
LIQ_HostBankShareFor_OK_Button = 'JavaWindow("title:=Host Bank Share for.*").JavaButton("label:=OK")'
LIQ_HostBankShareFor_Cancel_Button = 'JavaWindow("title:=Host Bank Share for.*").JavaButton("label:=Cancel")'
LIQ_HostBankShareFor_AddPortfolio_Button = 'JavaWindow("title:=Host Bank Share for.*").JavaButton("label:=Add Portfolio/Expense Code")'
LIQ_HostBankShareFor_SumOfPortfolioShares_Text = 'JavaWindow("title:=Host Bank Share for.*").JavaEdit("attached text:=Sum of Portfolio Shares:")'

### Portfolio Share Edit Window ###
LIQ_PortfolioShareEdit_Window = 'JavaWindow("title:=Portfolio Share Edit")'
LIQ_PortfolioShareEdit_Adjustment_Textfield = 'JavaWindow("title:=Portfolio Share Edit").JavaEdit("index:=0")'
LIQ_PortfolioShareEdit_OK_Button = 'JavaWindow("title:=Portfolio Share Edit").JavaButton("label:=OK")'
LIQ_PortfolioShareEdit_Cancel_Button = 'JavaWindow("title:=Portfolio Share Edit").JavaButton("label:=Cancel")'
LIQ_PortfolioShareEdit_WriteoffLegalAmount_Textfield='JavaWindow("title:=Portfolio Share Edit").JavaEdit("index:=8")'
LIQ_PortfolioShareEdit_NewBalance_Text='JavaWindow("title:=Portfolio Share Edit").JavaEdit("index:=1")'
LIQ_PortfolioShareEdit_LegalAmount_Text='JavaWindow("title:=Portfolio Share Edit").JavaEdit("index:=0")'
LIQ_PortfolioShareEdit_BookAmount_Text='JavaWindow("title:=Portfolio Share Edit").JavaEdit("index:=1")'
LIQ_PortfolioShareEdit_NonBookAmount_Text='JavaWindow("title:=Portfolio Share Edit").JavaEdit("index:=2")'
LIQ_PortfolioShareEdit_ChargedoffBookAmount_Text='JavaWindow("title:=Portfolio Share Edit").JavaEdit("index:=3")'

### Comment Edit Window ###
LIQ_CommentEdit_Window = 'JavaWindow("title:=Comment Edit")'
LIQ_CommentEdit_Comment_Text = 'JavaWindow("title:=Comment Edit").JavaEdit("attached text:=Comment:")'
LIQ_CommentEdit_OK_Button = 'JavaWindow("title:=Comment Edit").JavaButton("attached text:=OK")'

### Share Adjustment Window ###
LIQ_ShareAdjustment_DealName ='JavaWindow("title:=Share Adjustment.*").JavaStaticText("x:=140","y:=0")'
LIQ_ShareAdjustment_FacilityName = 'JavaWindow("title:=Share Adjustment.*").JavaStaticText("x:=140","y:=28")'
LIQ_ShareAdjustment_AmendmentNO = 'JavaWindow("title:=Share Adjustment.*").JavaStaticText("x:=383","y:=83")'
LIQ_ShareAdjustmentInFacility = 'JavaWindow("title:=Shares for .*")'
LIQ_ShareAdjustment_Options_FacilityNotebook = 'JavaWindow("title:=Shares for .*").JavaMenu("label:=Options").JavaMenu("label:=Facility Notebook")'
LIQ_ShareAdjustment_Facility_Window = 'JavaWindow("title:=Facility -.*")'
LIQ_ShareAdjustment_Ok_Button = 'JavaWindow("title:=Shares for .*").JavaButton("attached text:=OK")'