### Accrual Shares Adjustment Window ###
LIQ_AccrualSharesAdjustment_Window = 'JavaWindow("title:=Accrual Shares Adjustment -.*")'
LIQ_AccrualSharesAdjustment_Window_Tab = 'JavaWindow("title:=Accrual Shares Adjustment -.*").JavaTab("tagname:=TabFolder")'
LIQ_AccrualSharesAdjustment_WorkflowAction_JavaTree = 'JavaWindow("title:=Accrual Shares Adjustment -.*").JavaTree("attached text:=Drill down to perform Workflow item")'
LIQ_AccrualSharesAdjustment_RequestedAmount_TextField = 'JavaWindow("title:=Accrual Shares Adjustment -.*").JavaEdit("attached text:=${Accrual_Currency}","index:=0")'
LIQ_AccrualSharesAdjustment_EffectiveDate_TextField = 'JavaWindow("title:=Accrual Shares Adjustment -.*").JavaEdit("attached text:=Effective Date:")'
LIQ_AccrualSharesAdjustment_Comment_TextField = 'JavaWindow("title:=Accrual Shares Adjustment -.*").JavaEdit("attached text:=Comment:")'
LIQ_AccrualSharesAdjustment_FileSave_Menu = 'JavaWindow("title:=Accrual Shares Adjustment -.*").JavaMenu("label:=File").JavaMenu("label:=Save")'
LIQ_AccrualSharesAdjustment_FileExit_Menu = 'JavaWindow("title:=Accrual Shares Adjustment -.*").JavaMenu("label:=File").JavaMenu("label:=Exit")'
LIQ_AccrualSharesAdjustment_Options_ViewUpdateLenderShares = 'JavaWindow("title:=Accrual Shares Adjustment -.*").JavaMenu("label:=Options").JavaMenu("label:=View/Update Lender Shares")'
LIQ_AccrualSharesAdjustment_CycleDue_TextField = 'JavaWindow("title:=Accrual Shares Adjustment -.*").JavaEdit("tagname:=Text", "index:=5")'
LIQ_AccrualSharesAdjustment_Queries_GLEntries = 'JavaWindow("title:=Accrual Shares Adjustment -.*").JavaMenu("label:=Queries").JavaMenu("label:=GL Entries")'
LIQ_AccrualSharesAdjustment_InquiryMode_Button = 'JavaWindow("title:=Accrual Shares Adjustment -.*").JavaButton("attached text:=Notebook in Inquiry Mode.*")'
LIQ_AccrualSharesAdjustment_UpdateMode_Button = 'JavaWindow("title:=Accrual Shares Adjustment -.*").JavaButton("attached text:=Notebook in Update Mode - F7")'