###Existing Standby Letter of Credit for Deal Window###
LIQ_ExistingStandbyLettersOfCredit_Window = 'JavaWindow("title:=Existing Standby Letters of Credit.*")'
LIQ_ExistingStandbyLettersOfCredit_Tree = 'JavaWindow("title:=Existing Standby Letters of Credit.*").JavaTree("attached text:=Drill down to open the notebook")'
LIQ_ExistingStandbyLettersOfCreditUpdate_Checkbox = 'JavaWindow("title:=Existing Standby Letters of Credit.*").JavaCheckBox("attached text:=Open notebook in update mode")'
LIQ_ExistingStandbyLettersOfRemainOpen_Checkbox = 'JavaWindow("title:=Existing Standby Letters of Credit.*").JavaCheckBox("attached text:=Remain open after.*")'
LIQ_ExistingLettersofCredit_Window = 'JavaWindow("title:=Existing Standby Letters of Credit.*")'
LIQ_ExistingLettersofCredit_LettersofCredit_List = 'JavaWindow("title:=Existing Standby Letters of Credit.*").JavaTree("attached text:=Drill down to open the notebook")'
LIQ_ExistingStandbyLettersOfCredit_Decrease_Button = 'JavaWindow("title:=Existing Standby Letters of Credit.*").JavaButton("attached text:=Decrease")'

###SBLC/Guarantee Notebook###
LIQ_SBLCGuarantee_Window = 'JavaWindow("title:=.*Letter of Credit.*")'
LIQ_SBLCGuarantee_Tab = 'JavaWindow("title:=.*Letter of Credit.*").JavaTab("tagname:=TabFolder")'
LIQ_SBLCGuarantee_InquiryMode_Button = 'JavaWindow("title:=.*Letter of Credit.*").JavaButton("label:=.*Inquiry Mode.*")'
LIQ_SBLCGuarantee_UpdateMode_Button = 'JavaWindow("title:=.*Letter of Credit.*").JavaButton("label:=.*Update Mode.*")'
LIQ_SBLCGuarantee_Payments_FeesOnLenderShares = 'JavaWindow("title:=.*Letter of Credit.*").JavaMenu("label:=Payments").JavaMenu("label:=Fees On Lender shares")'
LIQ_SBLCGuarantee_Payments_FeesOnIssuingBankShares = 'JavaWindow("title:=Standby Letter of Credit.*").JavaMenu("label:=Payments").JavaMenu("label:=Fees on Issuing Bank Shares")'
LIQ_SBLCGuarantee_Payments_Type = 'JavaWindow("title:=.*Letter of Credit.*").JavaMenu("label:=Payments").JavaMenu("label:=${PaymentType}")'
LIQ_SBLCGuarantee_Alias_StaticText = 'JavaWindow("title:=.*Letter of Credit.*").JavaStaticText("x:=164","y:=122")'
LIQ_SBLCGuarantee_GlobalOriginal_StaticText = 'JavaWindow("title:=.*Letter of Credit.*").JavaObject("tagname:=Group","text:=Amounts").JavaEdit("attached text:=Global Original:")'
LIQ_SBLCGuarantee_Rate_StaticText = 'JavaWindow("title:=.*Letter of Credit.*").JavaObject("tagname:=Group","text:=Fee on Lender Shares").JavaEdit("text:=.*%.*")'
LIQ_SBLCGuarantee_RateBasis_Combobox = 'JavaWindow("title:=.*Letter of Credit.*").JavaObject("tagname:=Group","text:=Fee on Lender Shares").JavaList("attached text:=Rate Basis:")'
LIQ_SBLCGuarantee_CycleFrequency_Combobox = 'JavaWindow("title:=.*Letter of Credit.*").JavaObject("tagname:=Group","text:=Fee on Lender Shares").JavaObject("tagname:=Group","text:=Accrual Rules").JavaList("attached text:=Cycle Frequency:")'
LIQ_SBLCGuarantee_StartDate_StaticText = 'JavaWindow("title:=.*Letter of Credit.*").JavaObject("tagname:=Group","text:=Fee on Lender Shares").JavaObject("tagname:=Group","text:=Accrual Rules").JavaEdit("attached text:=Start Date:")'
LIQ_SBLCGuarantee_EffectiveDate_StaticText = 'JavaWindow("title:=.*Letter of Credit.*").JavaStaticText("x:=569","y:=157")'
LIQ_SBLCGuarantee_AccrualRule_Dropdown = 'JavaWindow("title:=.*Letter of Credit.*").JavaList("labeled_containers_path:=.*Fee on Lender Shares.*Group.*Accrual Rules.*","text:=Pay in Arrears")'
LIQ_SBLCGuarantee_FacingRate_StaticText = 'JavaWindow("title:=Standby Letter of Credit.*").JavaObject("tagname:=Group","text:=Fee on Issuing Bank Shares").JavaEdit("text:=.*%.*")'
LIQ_SBLCGuarantee_FacingRateBasis_Combobox = 'JavaWindow("title:=Standby Letter of Credit.*").JavaObject("tagname:=Group","text:=Fee on Issuing Bank Shares").JavaList("attached text:=Rate Basis:")'
LIQ_SBLCGuarantee_Workflow_JavaTree = 'JavaWindow("title:=Standby Letter of Credit.*").JavaTree("attached text:=Drill down to perform Workflow item")'
LIQ_SBLCGuarantee_FeeOnIssuingBankShares_JavaTree = 'JavaWindow("title:=Standby Letter of Credit.*").JavaTree("attached text:=Drill down to view details","labeled_containers_path:=.*Fee on Issuing Bank Shares.*")'
LIQ_SBLCGuarantee_Save = 'JavaWindow("title:=.*Standby Letter of Credit.*").JavaMenu("label:=File").JavaMenu("label:=Save")'
LIQ_SBLCGuarantee_RequestedAmount = 'JavaWindow("title:=.*Standby Letter of Credit.*").JavaEdit("attached text:=Requested:")'
LIQ_SBLCGurantee_ExpiryDate = 'JavaWindow("title:=.*Standby Letter of Credit.*").JavaEdit("attached text:=Entered Expiry:")'
LIQ_SBLCGuarantee_EffectiveDate = 'JavaWindow("title:=.*Standby Letter of Credit.*").JavaEdit("attached text:=Effective Date:")'
LIQ_SBLCGuarantee_FeeOnLenderShares_Enable_CheckBox = 'JavaWindow("title:=.*Standby Letter of Credit.*").JavaCheckBox("attached text:=Enable","labeled_containers_path:=Tab:Rates;Group:Fee on Lender Shares;")'
LIQ_SBLCGuarantee_FeeOnLenderShares_Type_ComboBox = 'JavaWindow("title:=.*Standby Letter of Credit.*").JavaList("index:=0","labeled_containers_path:=Tab:Rates;Group:Fee on Lender Shares;")'
LIQ_SBLCGuarantee_FeeOnLenderShares_AccrualRules_StartDate = 'JavaWindow("title:=.*Standby Letter of Credit.*").JavaEdit("labeled_containers_path:=Tab:Rates;Group:Fee on Lender Shares;Group:Accrual Rules;","index:=4")'
LIQ_SBLCGuarantee_SeparateAccrualRules_CheckBox =  'JavaWindow("title:=.*Standby Letter of Credit.*").JavaCheckBox("label:=Separate Accrual Rules")'
LIQ_SBLCGuarantee_FeeOnIssuingBankShares_Enable_Checkbox = 'JavaWindow("title:=.*Standby Letter of Credit.*").JavaCheckBox("labeled_containers_path:=Tab:Rates;Group:Fee on Issuing Bank Shares;","attached text:=Enable")'
LIQ_SBLCGUarantee_FeeOnLenderShares_AccrualDate_CycleFrequency_ComboBox = 'JavaWindow("title:=.*Standby Letter of Credit.*").JavaList("labeled_containers_path:=Tab:Rates;Group:Fee on Lender Shares;Group:Accrual Rules;","attached text:=Cycle Frequency:")'
LIQ_SBLCGuarantee_AddBeneficiary_Buttton = 'JavaWindow("title:=.*Standby Letter of Credit.*").JavaButton("attached text:=Add Ben\.")'
LIQ_SBLCGuarantee_PreferredRemittanceInstruction_Button = 'JavaWindow("title:=.*Standby Letter of Credit.*").JavaButton("attached text:=Preferred Remittance Instructions\.\.\.")'
LIQ_SBLCGuarantee_BeneficiaryList_JavaTree = 'JavaWindow("title:=.*Standby Letter of Credit.*").JavaTree("attached text:=Drill down to set Servicing Group")'
LIQ_SBLCGuarantee_Options_UpdateIssuiingBankShares = 'JavaWindow("title:=.*Standby Letter of Credit.*").JavaMenu("label:=Options").JavaMenu("label:=View/Update Issuing Bank Shares")'
LIQ_SBLCGuarantee_FeeOnIssuingBankShares_Accrual_ComboBox = 'JavaWindow("title:=.*Standby Letter of Credit.*").JavaList("index:=0","labeled_containers_path:=Tab:Rates;Group:Fee on Issuing Bank Shares;Group:Accrual Rules;")'
LIQ_SBLCGuarantee_Accrual_JavaTree = 'JavaWindow("title:=.*Standby Letter of Credit.*Active").JavaTree("labeled_containers_path:=Tab:Accrual;Group:.*${AccrualType}.*;")'

LIQ_SBLCGuarantee_Window_Tab = 'JavaWindow("title:=.*Letter of Credit.").JavaTab("tagname:=TabFolder")'
LIQ_SBLCGuarantee_FrontingUsageFee_CycleList = 'JavaWindow("title:=.*Letter of Credit.").JavaObject("tagname:=Group", "text:=.* Fee (.*BG.*)").JavaTree("attached text:=Drill down to view details")'
LIQ_SBLCGuarantee_CycleSharesAdjustment_Button = 'JavaWindow("title:=.*Letter of Credit.").JavaObject("tagname:=Group", "text:=.* Fee (.*BG.*)").JavaButton("attached text:=Cycle Shares Adjustment")'
LIQ_SBLCGuarantee_UpdateMode_Button = 'JavaWindow("title:=.*Letter of Credit.").JavaButton("attached text:=Notebook in Update Mode - F7")'
LIQ_SBLCGuarantee_InquiryMode_Button = 'JavaWindow("title:=.*Letter of Credit.").JavaButton("attached text:=Notebook in Inquiry Mode - F7")'

### Accrual Tab ####
LIQ_BankGuarantee_SBLCIssuanceRate_JavaTree = 'JavaWindow("title:=Standby Letter of Credit.*").JavaObject("text:=SBLC Issuance Rate.*").JavaTree("attached text:=Drill down to view details")'
LIQ_BankGuarantee_SBLCFacing_JavaTree = 'JavaWindow("title:=Standby Letter of Credit.*").JavaObject("text:=SBLC Facing.*").JavaTree("attached text:=Drill down to view details")'
LIQ_SBLCGuarantee_IssuanceCycleSharesAdjustment_Button = 'JavaWindow("title:=Standby Letter of Credit.*").JavaObject("text:=SBLC Issuance Rate.*").JavaButton("attached text:=Cycle Shares Adjustment")'
LIQ_SBLCGuarantee_IssuanceCycleSharesOverview_Button = 'JavaWindow("title:=.*Standby Letter of Credit.*ctive.*").JavaObject("text:=LC Periodic Commission.*").JavaButton("attached text:=Cycle Shares Overview")'

###Cycles for Bank Guarantee/Letter of Credit/Synd Fronted Bank Window###
LIQ_CyclesForBankGuarantee_Window = 'JavaWindow("title:=Cycles for.*")'
LIQ_CyclesForBankGuarantee_Prorate_RadioButton = 'JavaWindow("title:=Cycles for.*").JavaRadioButton("label:=")'
LIQ_CyclesForBankGuarantee_ProjectedDue_RadioButton = 'JavaWindow("title:=Cycles for.*").JavaRadioButton("label:=Projected Due")'
LIQ_CyclesForBankGuarantee_Tree = 'JavaWindow("title:=Cycles for.*").JavaTree("attached text:=Choose a cycle to make a payment against")'

###Issuance Fee Payment Notebook###
LIQ_IssuanceFeePaymentNotebook_Window = 'JavaWindow("title:=Bank Guarantee/Letter of Credit/Synd Fronted Bank Issuance Fee Payment.*")'
LIQ_IssuanceFeePaymentNotebook_EffectiveDate_Field = 'JavaWindow("title:=Bank Guarantee/Letter of Credit/Synd Fronted Bank Issuance Fee Payment.*").JavaEdit("attached text:=Effective Date:")'
LIQ_IssuanceFeePaymentNotebook_File_Save = 'JavaWindow("title:=Bank Guarantee/Letter of Credit/Synd Fronted Bank Issuance Fee Payment.*").JavaMenu("label:=File").JavaMenu("label:=Save")'
LIQ_IssuanceFeePaymentNotebook_Tab = 'JavaWindow("title:=Bank Guarantee/Letter of Credit/Synd Fronted Bank Issuance Fee Payment.*").JavaTab("tagname:=TabFolder")'
LIQ_IssuanceFeePaymentNotebook_Workflow_Tree = 'JavaWindow("title:=Bank Guarantee/Letter of Credit/Synd Fronted Bank Issuance Fee Payment.*").JavaTree("attached text:=Drill down to perform Workflow item")'
LIQ_IssuanceFeePaymentNotebook_Options_Cashflow = 'JavaWindow("title:=Bank Guarantee/Letter of Credit.*Issuance Fee Payment.*").JavaMenu("label:=Options").JavaMenu("label:=Cashflow")'
LIQ_IssuanceFeePaymentNotebook_File_Exit = 'JavaWindow("title:=Bank Guarantee/Letter of Credit.*Issuance Fee Payment.*").JavaMenu("label:=File").JavaMenu("label:=Exit")'

###Facing Fee Payment###
LIQ_FacinFeePaymentNotebook_EffectiveDate_Field = 'JavaWindow("title:=.*Facing Fee Payment.*").JavaEdit("attached text:=Effective Date:")'
LIQ_FacinFeePaymentNotebook_ProjectedCycleDue_Field = 'JavaWindow("title:=.*Facing Fee Payment.*").JavaEdit("index:=3")'
LIQ_FacinFeePaymentNotebook_RequestedAmount_Field = 'JavaWindow("title:=.*Facing Fee Payment.*").JavaEdit("index:=2")'
LIQ_FacinFeePaymentNotebook_Workflow_JavaTree = 'JavaWindow("title:=.*Facing Fee Payment.*").JavaTree("attached text:=Drill down to perform Workflow item")'
LIQ_FacinFeePaymentNotebook_Window = 'JavaWindow("title:=.*Facing Fee Payment.*")'
LIQ_FacinFeePaymentNotebook_File_Save = 'JavaWindow("title:=.*Facing Fee Payment.*").JavaMenu("label:=File").JavaMenu("label:=Save")'
LIQ_FacinFeePaymentNotebook_Tab = 'JavaWindow("title:=.*Facing Fee Payment.*").JavaTab("tagname:=TabFolder")'
LIQ_FacinFeePaymentNotebook_Options_Reverse_Payment = 'JavaWindow("title:=.*Facing Fee Payment.*").JavaMenu("label:=Options").JavaMenu("label:=Reverse Payment")'

###Reverse Facing Fee Payment###
LIQ_ReverseFacingFeePaymentNotebook_Window = 'JavaWindow("title:=.*Reverse Facing Fee Payment.*")'
LIQ_ReverseFacingFeePaymentNotebook_Tab = 'JavaWindow("title:=.*Reverse Facing Fee Payment.*").JavaTab("tagname:=TabFolder")'
LIQ_ReverseFacingFeePaymentNotebook_Workflow_JavaTree = 'JavaWindow("title:=.*Reverse Facing Fee Payment.*").JavaTree("attached text:=Drill down to perform Workflow item")'


###Issuance Fee Payment - Generate Intent Notices Window###
LIQ_SBLCGuaranteeFeePaymentGroup_Window = 'JavaWindow("title:=SBLC/Guarantee Fee Payment Group created by.*")'
LIQ_SBLCGuaranteeFeePaymentGroup_Tree = 'JavaWindow("title:=SBLC/Guarantee Fee Payment Group created by.*").JavaTree("attached text:=Drill down to mark notices")'
LIQ_SBLCGuaranteeFeePaymentGroup_Edit_Button = 'JavaWindow("title:=SBLC/Guarantee Fee Payment Group created by.*").JavaButton("label:=Edit Highlighted Notices")'
LIQ_SBLCGuaranteeFeePaymentGroup_Exit_Button = 'JavaWindow("title:=SBLC/Guarantee Fee Payment Group created by.*").JavaButton("label:=Exit")'
LIQ_SBLCGuaranteeFeePaymentGroup_Notice_Window = 'JavaWindow("title:=SBLC/Guarantee Fee Payment created by.*")'
LIQ_SBLCGuaranteeFeePaymentGroup_File_Preview = 'JavaWindow("title:=SBLC/Guarantee Fee Payment Group created by.*").JavaMenu("label:=File").JavaMenu("label:=Preview")'

###New SBLC/Guarantee Issuance Notebook###
###General Tab###
LIQ_SBLCIssuance_Window = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*","displayed:=1")'
LIQ_SBLCIssuance_Tab = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*","displayed:=1").JavaTab("to_description:=JavaTab")'
LIQ_SBLCIssuance_JavaTree = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*","displayed:=1").JavaTree("attached text:=Drill down to.*")'
LIQ_SBLCIssuance_Requested_TextField = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*","displayed:=1").JavaEdit("attached text:=Requested:")'
LIQ_SBLCIssuance_EffectiveDate_TextField = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*","displayed:=1").JavaEdit("attached text:=Effective Date:")'
LIQ_SBLCIssuance_EnteredExpiry_TextField = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*","displayed:=1").JavaEdit("attached text:=Entered Expiry:")'
LIQ_SBLCIssuance_FinalExpiry_TextField = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*","displayed:=1").JavaEdit("attached text:=Final Expiry Date:")'
LIQ_SBLCIssuance_ExpiryDate_TextField = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*","displayed:=1").JavaEdit("attached text:=Entered Expiry:")'
LIQ_SBLCIssuance_AdjustedExpiryDate_TextField = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*","displayed:=1").JavaEdit("attached text:=Adjusted Expiry:")'
LIQ_SBLCIssuance_Sublimit_Button = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*","displayed:=1").JavaButton("attached text:=Sublimit:")'
LIQ_SBLCIssuance_Sublimit_Label = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*","displayed:=1").JavaStaticText("class description:=static_text","index:=1")'
LIQ_SBLCIssuance_RiskType_TextField = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*","displayed:=1").JavaEdit("class description:=edit","index:=1")'
LIQ_SBLCIssuance_RiskType_Button = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*","displayed:=1").JavaButton("attached text:=Risk Type:")'
LIQ_SBLCIssuance_Reinstatable_Checkbox = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*","displayed:=1").JavaCheckBox("attached text:=Reinstatable")'
LIQ_SBLCIssuance_AutoReduceOnExpiry_Checkbox = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*","displayed:=1").JavaCheckBox("attached text:=Auto-Reduce on Expiry")'
LIQ_SBLCIssuance_AutomaticallyExtend_Checkbox = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*","displayed:=1").JavaCheckBox("attached text:=Automatically Extend")'
LIQ_SBLCIssuance_ContractID_TextField = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*","displayed:=1").JavaEdit("attached text:=Contract ID:")'
LIQ_SBLCIssuance_PastDueGraceDays_TextField = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*","displayed:=1").JavaEdit("attached text:=Past Due Grace Days:")'
LIQ_SBLCIssuance_PerformingStatus_List = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*","displayed:=1").JavaList("attached text:=Performing Status:")'
LIQ_SBLCIssuance_SelectSublimit_Window = 'JavaWindow("title:=Select Sublimit","displayed:=1")'
LIQ_SBLCIssuance_SelectSublimit_JavaTree = 'JavaWindow("title:=Select Sublimit","displayed:=1").JavaTree("attached text:=Drill down to select")'
LIQ_SBLCIssuance_SelectSublimit_OK_Button = 'JavaWindow("title:=Select Sublimit","displayed:=1").JavaButton("attached text:=OK")'
LIQ_SBLCIssuance_SelectRiskType_Window = 'JavaWindow("title:=Select Risk Type","displayed:=1")'
LIQ_SBLCIssuance_SelectRiskType_JavaTree = 'JavaWindow("title:=Select Risk Type","displayed:=1").JavaTree("attached text:=Drill down to select")'
LIQ_SBLCIssuance_SelectRiskType_OK_Button = 'JavaWindow("title:=Select Risk Type","displayed:=1").JavaButton("attached text:=OK")'
LIQ_SBLCIssuance_AccrualRules_Pay_Dropdown = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*").JavaList("index:=5")'
LIQ_SBLCIssuance_AdjustextExpiry_TextField = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*","displayed:=1").JavaEdit("attached text:=Adjusted Expiry:")' 

###Rates Tab###
LIQ_SBLCIssuance_Rates_Tab = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*","displayed:=1").JavaTab("tagname:=TabFolder")'
LIQ_SBLCIssuance_Rates_SeparateAccrualRules_Checkbox = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*").JavaCheckbox("label:=Separate Accrual Rules")'
LIQ_SBLCIssuance_FeeOnLenderShares_AccrualRules_CycleFrequency_Dropdown = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*").JavaList("attached text:=Cycle Frequency:","labeled_containers_path:=.*Fee on Lender Shares.*")'
LIQ_SBLCIssuance_FeeOnLenderShares_PricingFormula_Button = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*","displayed:=1").JavaObject("tagname:=Group","text:=Fee on Lender Shares.*").JavaButton("label:=Pricing Formula.*")'
LIQ_SBLCIssuance_FeeOnIssuingBankShares_PricingFormula_Button = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*","displayed:=1").JavaObject("tagname:=Group","text:=Fee on Issuing Bank Shares.*").JavaButton("label:=Pricing Formula.*")'
LIQ_SBLCIssuance_FeeOnLenderShares_PricingFormula_OK_Button = 'JavaWindow("title:=Pricing Formula.*","displayed:=1").JavaButton("label:=OK.*")'
LIQ_SBLCIssuance_FeeOnIssuingBankShares_PricingFormula_OK_Button = 'JavaWindow("title:=Pricing Formula.*","displayed:=1").JavaButton("label:=OK.*")'
LIQ_SBLCIssuance_FeeOnLenderShares_PricingFormula_Window = 'JavaWindow("title:=Pricing Formula.*","displayed:=1")'
LIQ_SBLCIssuance_FeeOnIssuingBankShares_PricingFormula_Window = 'JavaWindow("title:=Pricing Formula.*","displayed:=1")'
LIQ_SBLCIssuance_FeeOnLenderShares_PricingFormula_Label = 'JavaWindow("title:=Pricing Formula.*","displayed:=1").JavaEdit("tagname:=icon")'
LIQ_SBLCIssuance_FeeOnIssuingBankShares_PricingFormula_Label = 'JavaWindow("title:=Pricing Formula.*","displayed:=1").JavaEdit("tagname:=icon")'
LIQ_SBLCIssuance_FeeOnLenderShares_EnableCheckbox = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*").JavaObject("tagname:=Group","text:=Fee on Lender Shares.*").JavaCheckbox("label:=Enable.*")'
LIQ_SBLCIssuance_FeeOnLenderShares_Type_Dropdown = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*","displayed:=1").JavaObject("tagname:=Group","text:=Fee on Lender Shares.*").JavaList("attached text:=Type.*")'
LIQ_SBLCIssuance_FeeOnLenderShares_Flat_Checkbox = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*","displayed:=1").JavaObject("tagname:=Group","text:=Fee on Lender Shares.*").JavaCheckbox("attached text:=Flat")'
LIQ_SBLCIssuance_FeeOnLenderShares_Rate_TextField = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*","displayed:=1").JavaObject("tagname:=Group","text:=Fee on Lender Shares.*").JavaEdit("attached text:=Rate:")'
LIQ_SBLCIssuance_FeeOnLenderShares_MinimumAmount_TextField = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*","displayed:=1").JavaObject("tagname:=Group","text:=Fee on Lender Shares.*").JavaEdit("attached text:=Minimum Amount:")'
LIQ_SBLCIssuance_FeeOnLenderShares_RateBasis_Dropdown = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*","displayed:=1").JavaObject("tagname:=Group","text:=Fee on Lender Shares.*").JavaList("attached text:=Rate Basis:")'
LIQ_SBLCIssuance_FeeOnLenderShares_StartDate_TextField = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*","displayed:=1").JavaObject("tagname:=Group","text:=Fee on Lender Shares.*").JavaEdit("attached text:=Start Date:")'
LIQ_SBLCIssuance_FeeOnLenderShares_CycleFrequency_Dropdown = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*","displayed:=1").JavaObject("tagname:=Group","text:=Fee on Lender Shares.*").JavaList("attached text:=Cycle Frequency:")'
LIQ_SBLCIssuance_FeeOnLenderShares_ActualDueDate_TextField = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*","displayed:=1").JavaObject("tagname:=Group","text:=Fee on Lender Shares.*").JavaEdit("attached text:=Actual Due Date:")'
LIQ_SBLCIssuance_FeeOnLenderShares_AdjustedDueDate_TextField = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*","displayed:=1").JavaObject("tagname:=Group","text:=Fee on Lender Shares.*").JavaEdit("attached text:=Adjusted Due Date:")'
LIQ_SBLCIssuance_FeeOnLenderShares_EndDate_TextField = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*","displayed:=1").JavaObject("tagname:=Group","text:=Fee on Lender Shares.*").JavaEdit("attached text:=End Date:")'
LIQ_SBLCIssuance_FeeOnLenderShares_PaymentScheme_Dropdown = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*","displayed:=1").JavaObject("tagname:=Group","text:=Fee on Lender Shares.*").JavaList("class description:=list","index:=2")'
LIQ_SBLCIssuance_FeeOnLenderShares_SynchronizeBilling_Checkbox = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*","displayed:=1").JavaObject("tagname:=Group","text:=Fee on Lender Shares.*").JavaCheckbox("attached text:=Synchronize Billing")'
LIQ_SBLCIssuance_FeeOnLenderShares_ActualDueDateRule_Dropdown = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*","displayed:=1").JavaObject("tagname:=Group","text:=Fee on Lender Shares.*").JavaList("attached text:=Rule:")'
LIQ_SBLCIssuance_FeeOnLenderShares_AdjustedDueDateRule_TextField = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*","displayed:=1").JavaObject("tagname:=Group","text:=Fee on Lender Shares.*").JavaEdit("attached text:=Rule:")'
LIQ_SBLCIssuance_FeeOnLenderShares_ToTheAdjustedDate_RadioButton = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*","displayed:=1").JavaObject("tagname:=Group","text:=Fee on Lender Shares.*").JavaRadioButton("attached text:=to the adjusted due date")'
LIQ_SBLCIssuance_FeeOnLenderShares_ThruTheAdjustedDate_RadioButton = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*","displayed:=1").JavaObject("tagname:=Group","text:=Fee on Lender Shares.*").JavaRadioButton("attached text:=thru the adjusted due date")'
LIQ_SBLCIssuance_FeeOnLenderShares_ToTheActualDueDate_RadioButton = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*","displayed:=1").JavaObject("tagname:=Group","text:=Fee on Lender Shares.*").JavaRadioButton("attached text:=to the actual due date")'
LIQ_SBLCIssuance_FeeOnLenderShares_ThruTheActualDueDate_RadioButton = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*","displayed:=1").JavaObject("tagname:=Group","text:=Fee on Lender Shares.*").JavaRadioButton("attached text:=thru the actual due date")'

LIQ_SBLCIssuance_FeeOnIssuingBankShares_EnableCheckbox = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*").JavaObject("tagname:=Group","text:=Fee on Issuing Bank Shares").JavaCheckbox("label:=Enable.*")'
LIQ_SBLCIssuance_FeeOnIssuingBankShares_Type_Dropdown = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*","displayed:=1").JavaObject("tagname:=Group","text:=Fee on Issuing Bank Shares").JavaList("attached text:=Type.*")'
LIQ_SBLCIssuance_FeeOnIssuingBankShares_Flat_Checkbox = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*","displayed:=1").JavaObject("tagname:=Group","text:=Fee on Issuing Bank Shares").JavaCheckbox("attached text:=Flat")'
LIQ_SBLCIssuance_FeeOnIssuingBankShares_Rate_TextField = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*","displayed:=1").JavaObject("tagname:=Group","text:=Fee on Issuing Bank Shares").JavaEdit("attached text:=Rate:")'
LIQ_SBLCIssuance_FeeOnIssuingBankShares_MinimumAmount_TextField = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*","displayed:=1").JavaObject("tagname:=Group","text:=Fee on Issuing Bank Shares").JavaEdit("attached text:=Minimum Amount:")'
LIQ_SBLCIssuance_FeeOnIssuingBankShares_RateBasis_Dropdown = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*","displayed:=1").JavaObject("tagname:=Group","text:=Fee on Issuing Bank Shares").JavaList("attached text:=Rate Basis:")'
LIQ_SBLCIssuance_FeeOnIssuingBankShares_StartDate_TextField = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*","displayed:=1").JavaObject("tagname:=Group","text:=Fee on Issuing Bank Shares").JavaEdit("attached text:=Start Date:")'
LIQ_SBLCIssuance_FeeOnIssuingBankShares_CycleFrequency_Dropdown = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*","displayed:=1").JavaObject("tagname:=Group","text:=Fee on Issuing Bank Shares").JavaList("attached text:=Cycle Frequency:")'
LIQ_SBLCIssuance_FeeOnIssuingBankShares_ActualDueDate_TextField = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*","displayed:=1").JavaObject("tagname:=Group","text:=Fee on Issuing Bank Shares").JavaEdit("attached text:=Actual Due Date:")'
LIQ_SBLCIssuance_FeeOnIssuingBankShares_AdjustedDueDate_TextField = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*","displayed:=1").JavaObject("tagname:=Group","text:=Fee on Issuing Bank Shares").JavaEdit("attached text:=Adjusted Due Date:")'
LIQ_SBLCIssuance_FeeOnIssuingBankShares_EndDate_TextField = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*","displayed:=1").JavaObject("tagname:=Group","text:=Fee on Issuing Bank Shares").JavaEdit("attached text:=End Date:")'
LIQ_SBLCIssuance_FeeOnIssuingBankShares_PaymentScheme_Dropdown = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*","displayed:=1").JavaObject("tagname:=Group","text:=Fee on Issuing Bank Shares").JavaList("class description:=list","index:=2")'
LIQ_SBLCIssuance_FeeOnIssuingBankShares_SynchronizeBilling_Checkbox = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*","displayed:=1").JavaObject("tagname:=Group","text:=Fee on Issuing Bank Shares").JavaCheckbox("attached text:=Synchronize Billing")'
LIQ_SBLCIssuance_FeeOnIssuingBankShares_ActualDueDateRule_Dropdown = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*","displayed:=1").JavaObject("tagname:=Group","text:=Fee on Issuing Bank Shares").JavaList("attached text:=Rule:")'
LIQ_SBLCIssuance_FeeOnIssuingBankShares_AdjustedDueDateRule_TextField = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*","displayed:=1").JavaObject("tagname:=Group","text:=Fee on Issuing Bank Shares").JavaEdit("attached text:=Rule:")'
LIQ_SBLCIssuance_FeeOnIssuingBankShares_ToTheAdjustedDate_RadioButton = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*","displayed:=1").JavaObject("tagname:=Group","text:=Fee on Issuing Bank Shares").JavaRadioButton("attached text:=to the adjusted due date")'
LIQ_SBLCIssuance_FeeOnIssuingBankShares_ThruTheAdjustedDate_RadioButton = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*","displayed:=1").JavaObject("tagname:=Group","text:=Fee on Issuing Bank Shares").JavaRadioButton("attached text:=thru the adjusted due date")'
LIQ_SBLCIssuance_FeeOnIssuingBankShares_ToTheActualDueDate_RadioButton = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*","displayed:=1").JavaObject("tagname:=Group","text:=Fee on Issuing Bank Shares").JavaRadioButton("attached text:=to the actual due date")'
LIQ_SBLCIssuance_FeeOnIssuingBankShares_ThruTheActualDueDate_RadioButton = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*","displayed:=1").JavaObject("tagname:=Group","text:=Fee on Issuing Bank Shares").JavaRadioButton("attached text:=thru the actual due date")'
LIQ_SBLCIssuance_FeeOnIssuingBankShares_AccrualRules_CycleFrequency_Dropdown = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*").JavaList("attached text:=Cycle Frequency:","labeled_containers_path:=.*Fee on Issuing Bank Shares.*")'

###Banks Tab###
LIQ_SBLCIssuance_Banks_Tab = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*","displayed:=1").JavaTab("tagname:=TabFolder")'
LIQ_SBLCIssuance_Beneficiaries_Add_Button = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*","displayed:=1").JavaObject("tagname:=Group","text:=Beneficiaries:.*").JavaButton("label:=Add Ben..*")'
LIQ_SBLCIssuance_CustomerSelect_Window = 'JavaWindow("title:=Customer Select.*","displayed:=1")'
LIQ_SBLCIssuance_CustomerSelect_TextField = 'JavaWindow("title:=Customer Select.*","displayed:=1").JavaEdit("tagname:=Text.*")'
LIQ_SBLCIssuance_CustomerSelect_OK_Button = 'JavaWindow("title:=Customer Select.*","displayed:=1").JavaButton("label:=OK.*")'
LIQ_SBLCIssuance_Beneficiaries_Customer_Record_JavaTree = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*","displayed:=1").JavaObject("tagname:=Group","text:=Beneficiaries:.*").JavaTree("attached text:=Drill down to.*")'
LIQ_SBLCIssuance_AdvisingBank_Add_Button = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*","displayed:=1").JavaButton("attached text:=Add Adv\.")'
LIQ_SBLCIssuance_PreferredRemittanceInstruction = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*","displayed:=1").JavaButton("attached text:=Preferred Remittance Instructions.*")'

LIQ_SBLCIssuance_Save_Submenu = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*","displayed:=1").JavaMenu("label:=File").JavaMenu("label:=Save")'
LIQ_SBLCIssuance_Warning_Yes = 'JavaWindow("title:=Warning.*","displayed:=1").JavaButton("label:=Yes.*")'

LIQ_SBLCIssuance_Workflow_Tab = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*","displayed:=1").JavaTab("tagname:=TabFolder")'
LIQ_SBLCIssuance_GenerateIntentNotices_ListItem = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*","displayed:=1").JavaTree("attached text:=Drill down to.*")'
LIQ_SBLCIssuance_SendToApproval_ListItem = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*","displayed:=1").JavaTree("attached text:=Drill down to.*")'
LIQ_SBLCIssuance_Release_ListItem = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*","displayed:=1").JavaTree("attached text:=Drill down to.*")'
LIQ_SBLCIssuance_Warning_Yes_Button = 'JavaWindow("title:=Warning.*","displayed:=1").JavaButton("label:=Yes.*")'
LIQ_SBLCIssuance_Question_Yes_Button = 'JavaWindow("title:=Question.*","displayed:=1").JavaButton("label:=Yes.*")'
LIQ_SBLCIssuance_Workflow_ListItem = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*","displayed:=1").JavaTree("attached text:=Drill down to.*")'


LIQ_SBLCIssuance_Codes_Purpose = 'JavaWindow("title:=New Bank Guarantee.*","displayed:=1").JavaList("attached text:=Purpose.*")'

LIQ_SBLC_Intent_Notice_Window = 'JavaWindow("title:=SBLC/Guarantee Issuance Intent Notice Group.*","displayed:=1")'
LIQ_SBLC_EditHighlightedNotice_Button = 'JavaWindow("title:=SBLC/Guarantee Issuance Intent Notice Group.*","displayed:=1").JavaButton("label:=Edit Highlighted Notice.*")'
LIQ_SBLC_Intent_Notice_List = 'JavaWindow("title:=SBLC/Guarantee Issuance Intent Notice Group.*","displayed:=1").JavaTree("attached text:=Drill down to.*")'
LIQ_SBLC_Intent_Notice_Exit_Button = 'JavaWindow("title:=SBLC/Guarantee Issuance Intent Notice Group.*","displayed:=1").JavaButton("label:=Exit.*")'

#### Rate Setting Notice Group
LIQ_RateSettingNoticeGroup_EditHighlightedNotice_Button = 'JavaWindow("title:=Rate Setting Notice Group.*","displayed:=1").JavaButton("label:=Edit Highlighted Notice.*")'
LIQ_RateSetting_Notice_Email_Window = 'JavaWindow("title:=Rate Setting Notice created.*","displayed:=1")'
LIQ_RateSetting_Notice_FileMenu_PreviewMenu = 'JavaWindow("title:=Rate Setting Notice created.*","displayed:=1").JavaMenu("index:=0").JavaMenu("label:=Preview")'
LIQ_RateSettingNoticeGroup_Exit_Button = 'JavaWindow("title:=Rate Setting Notice Group.*","displayed:=1").JavaButton("label:=Exit.*")'


#### Interest Payment Notice
LIQ_InterestPayment_Notice_FileMenu_PreviewMenu = 'JavaWindow("title:=Interest Payment Notice created.*","displayed:=1").JavaMenu("index:=0").JavaMenu("label:=Preview")'
LIQ_InterestPayment_Notice_Email_Window = 'JavaWindow("title:=Interest Payment Notice created.*","displayed:=1")'
LIQ_InterestPayment_Notice_Exit_Button = 'JavaWindow("title:=Interest Payment Notice Group created.*","displayed:=1").JavaButton("label:=Exit.*")'


LIQ_SBLC_Intent_Notice_FileMenu_PreviewMenu = 'JavaWindow("title:=SBLC/Guarantee Issuance Intent Notice created.*","displayed:=1").JavaMenu("index:=0").JavaMenu("label:=Preview")'
LIQ_SBLC_Intent_Notice_Email_Window = 'JavaWindow("title:=SBLC/Guarantee Issuance Intent Notice created.*","displayed:=1")'
LIQ_SBLC_Intent_Notice_Customer_TextField = 'JavaWindow("title:=SBLC/Guarantee Issuance Intent Notice created.*","displayed:=1").JavaEdit("text:=JORDAN BRAND INC")'
LIQ_SBLC_Intent_Notice_Status_Label = 'JavaWindow("title:=SBLC/Guarantee Issuance Intent Notice created.*","displayed:=1").JavaObject("tagname:=Group","text:=Status").JavaStaticText("text:=Awaiting release")'


LIQ_SBLC_NoticePreview_FileMenu_ExitMenu = 'JavaWindow("title:=Notice Preview.*","displayed:=1").JavaMenu("index:=0").JavaMenu("label:=Exit")'

LIQ_SBLCIssuance_Events_Tab = 'JavaWindow("title:=Standby Letter of Credit.*","displayed:=1").JavaTab("tagname:=TabFolder")'
LIQ_SBLCIssuance_Events_ListItem = 'JavaWindow("title:=Standby Letter of Credit.*","displayed:=1").JavaTree("attached text:=Select event.*")'

LIQ_SBLCIssuance_SBLCNotebook_Submenu = 'JavaWindow("title:=New Bank Guarantee.*","displayed:=1").JavaMenu("label:=Options").JavaMenu("label:=SBLC Notebook")'
LIQ_SBLC_Window = 'JavaWindow("title:=Standby Letter of Credit.*","displayed:=1")'
LIQ_SBLC_PerformOnlineAccrual_Submenu = 'JavaWindow("title:=SBLC.*","displayed:=1").JavaMenu("label:=Accounting").JavaMenu("label:=Perform Online Accrual")'

LIQ_SBLC_UpdateMode_Button = 'JavaWindow("title:=Bank Guarantee.*","displayed:=1").JavaButton("label:=Notebook in Inquiry Mode.*")'

LIQ_SBLC_Warning_Yes_Button = 'JavaWindow("title:=Warning.*","displayed:=1").JavaButton("label:=Yes.*")'
LIQ_SBLC_InformationalMessage_OK_Button = 'JavaWindow("title:=Informational Message.*","displayed:=1").JavaButton("label:=OK.*")'

LIQ_SBLC_DealName_Label = 'JavaWindow("title:=SBLC.*","displayed:=1").JavaStaticText("attached text:=T_EVERSBLC1 BIDEAL.*")'
LIQ_SBLC_Facility_Label = 'JavaWindow("title:=SBLC.*","displayed:=1").JavaStaticText("attached text:=T_EVER 3MM.*")'
LIQ_SBLC_PerformingStatus_Label = 'JavaWindow("title:=SBLC.*","displayed:=1").JavaStaticText("label:=Accrual.*")'

LIQ_SBLC_Rates_Tab = 'JavaWindow("title:=Standby Letter of Credit.*","displayed:=1").JavaTab("tagname:=TabFolder")'
LIQ_SBLC_Rates_StartDate = 'JavaWindow("title:=Standby Letter of Credit.*","displayed:=1").JavaObject("tagname:=Group","text:=Fee on Lender Shares.*").JavaObject("tagname:=Group","text:=Accrual Rules.*").JavaEdit("attached text:=Start Date:")'
LIQ_SBLC_Events_Tab = 'JavaWindow("title:=Standby Letter of Credit.*","displayed:=1").JavaTab("tagname:=TabFolder")'
LIQ_SBLC_Accrual_Tab = 'JavaWindow("title:=Standby Letter of Credit.*","displayed:=1").JavaTab("tagname:=TabFolder")'
LIQ_SBLC_Fee_JavaTree = 'JavaWindow("title:=Standby Letter of Credit.*","displayed:=1").JavaObject("tagname:=Group","text:=Issuance Fee.*").JavaTree("tagname:=Drill down to.*")'
LIQ_SBLC_InquiryMode_Button = 'JavaWindow("title:=Standby Letter of Credit.*").JavaButton("label:=.*Inquiry Mode.*")'

LIQ_NewSBLCIssuance_Workflow_Tab = 'JavaWindow("title:=New Standby Letter of Credit.*Issuance.*","displayed:=1").JavaTab("tagname:=TabFolder")'
LIQ_NewSBLC_PerformOnlineAccrual_Menu = 'JavaWindow("title:=Standby Letter of Credit.*","displayed:=1").JavaMenu("label:=Accounting").JavaMenu("label:=Perform Online Accrual")'


LIQ_Pending_SBLC_Window = 'JavaWindow("title:=Pending SBLC/Guarantee.*","displayed:=1")'
LIQ_Pending_SBLC_JavaTree = 'JavaWindow("title:=Pending SBLC/Guarantee.*","displayed:=1").JavaTree("attached text:=Drill down to.*")'

LIQ_Existing_Standby_Letters = 'JavaWindow("title:=Existing Standby Letters.*","displayed:=1")'
LIQ_Existing_Standby_Letters_JavaTree = 'JavaWindow("title:=Existing Standby Letters.*","displayed:=1").JavaTree("attached text:=Drill down to.*")'
LIQ_Bank_Guarantee_Window = 'JavaWindow("title:=Bank Guarantee.*","displayed:=1")'
LIQ_Bank_Guarantee_Update_Button = 'JavaWindow("title:=Bank Guarantee.*","displayed:=1").JavaButton("label:=Notebook in Inquiry Mode.*")'
LIQ_Bank_Guarantee_Draw_Tab = 'JavaWindow("title:=Bank Guarantee.*","displayed:=1").JavaTab("tagname:=TabFolder")'

LIQ_Bank_Guarantee_Create_Button = 'JavaWindow("title:=Bank Guarantee.*","displayed:=1").JavaObject("tagname:=Group","text:=Draws.*").JavaButton("label:=Create.*")'

LIQ_Generic_OneLiner_Warning_Window = 'JavaWindow("title:=Warning.*","displayed:=1").JavaEdit("attached text:=WARNING", "height:=68")' 
LIQ_Generic_MultiLine_Warning_Window = 'JavaWindow("title:=Warning.*","displayed:=1").JavaEdit("attached text:=WARNING", "height:=84")'
LIQ_Generic_RichText_Warning_Window = 'JavaWindow("title:=Warning.*","displayed:=1").JavaEdit("attached text:=WARNING", "height:=100")'
LIQ_Generic_Multiline_Richtext_Warning_Window = 'JavaWindow("title:=Warning.*","displayed:=1").JavaEdit("attached text:=WARNING", "height:=132")'
LIQ_Generic_OneLiner_Warning_Yes_Button = 'JavaWindow("title:=Warning.*","displayed:=1").JavaButton("label:=Yes.*")'
LIQ_Generic_Question_Window = 'JavaWindow("title:=Question.*","displayed:=1").JavaEdit("attached text:=QUESTION","height:=68")'
LIQ_Generic_Question_Yes_Button = 'JavaWindow("title:=Question.*","displayed:=1").JavaButton("label:=Yes.*")'
LIQ_Generic_InformationalMessage_Window = 'JavaWindow("title:=Informational Message.*","displayed:=1")'


### Bank Guarantee ###
LIQ_BankGuarantee_Window = 'JavaWindow("title:=Standby Letter of Credit.*")'
LIQ_BankGuarantee_Draw_Tab = 'JavaWindow("title:=Standby Letter of Credit.*").JavaTab("tagname:=TabFolder")'
LIQ_BankGuarantee_AvailableToDraw = 'JavaWindow("title:=Standby Letter of Credit.*").JavaEdit("index:=0")'
LIQ_BankGuarantee_DrawnButNotPaid = 'JavaWindow("title:=Standby Letter of Credit.*").JavaEdit("index:=1")'
LIQ_BankGuarantee_Create_Button = 'JavaWindow("title:=Standby Letter of Credit.*").JavaButton("attached text:=Create")'
LIQ_BankGuarantee_Draw_JavaTree = 'JavaWindow("title:=Standby Letter of Credit.*").JavaTree("attached text:=Drill down to edit draw")'
LIQ_BankGuarantee_InquiryMode_Button = 'JavaWindow("title:=Standby Letter of Credit.*").JavaButton("attached text:=Notebook in Inquiry Mode - F7")'
LIQ_BankGuarantee_Delete_Button = 'JavaWindow("title:=Standby Letter of Credit.*").JavaButton("attached text:=Delete")'
LIQ_BankGuarantee_PendingTab_JavaTree = 'JavaWindow("title:=Standby Letter of Credit.*").JavaTree("attached text:=Pending Transactions")'
LIQ_BankGuarantee_Accrual_JavaTree = 'JavaWindow("title:=Standby Letter of Credit.*").JavaTab("text:=Accrual").JavaTree("labeled_containers_path:=.*Issuance Fee.*")'
LIQ_BankGuarantee_Accrual_SBLCFacing_JavaTree = 'JavaWindow("title:=Standby Letter of Credit.*").JavaTab("text:=Accrual").JavaTree("labeled_containers_path:=.*SBLC Facing.*")'
LIQ_BankGuarantee_RequestedAmount_Field = 'JavaWindow("title:=Standby Letter of Credit.*").JavaEdit("index:=0","enabled:=1","tagname:=Text","labeled_containers_path:=.*Group.*Amounts.*")'
LIQ_ActiveSBLC_Rates_Tab = 'JavaWindow("title:=Standby Letter of Credit.*","displayed:=1").JavaTab("tagname:=TabFolder")'
LIQ_ActiveSBLC_Rates_StartDate = 'JavaWindow("title:=Standby Letter of Credit.*","displayed:=1").JavaObject("tagname:=Group","text:=Fee on Lender Shares.*").JavaObject("tagname:=Group","text:=Accrual Rules.*").JavaEdit("attached text:=Start Date:")'
LIQ_ActiveSBLC_Accrual_Tab = 'JavaWindow("title:=Bank Guarantee.*","displayed:=1").JavaTab("tagname:=TabFolder")'
LIQ_SBLC_PerformOnlineAccrual_Menu = 'JavaWindow("title:=Standby Letter of Credit.*","displayed:=1").JavaMenu("label:=Accounting").JavaMenu("label:=Perform Online Accrual")'
LIQ_ActiveSBLC_InquiryMode_Button = 'JavaWindow("title:=Standby Letter of Credit.*").JavaButton("attached text:=Notebook in Inquiry Mode - F7")'
LIQ_ActiveSBLC_FrontinUsageFee_JavaTree = 'JavaWindow("title:=Bank Guarantee.*","displayed:=1").JavaObject("tagname:=Group","text:=Fronting Usage Fee.*").JavaTree("tagname:=Drill down to.*")'
LIQ_ActiveSBLC_IssuanceFee_JavaTree = 'JavaWindow("title:=Bank Guarantee.*","displayed:=1").JavaObject("tagname:=Group","text:=Issuance Fee.*").JavaTree("tagname:=Drill down to.*")'
LIQ_BankGuarantee_AccrualCCY_Text = 'JavaWindow("title:=Bank Guarantee.*").JavaList("attached text:=Accrual Currency:")'
LIQ_BankGuarantee_FeeType_Dropdown = 'JavaWindow("title:=Bank Guarantee.*").JavaObject("tagname:=Group","text:=Fee on Lender Shares.*").JavaList("attached text:=Type:")'
LIQ_ActiveSBLC_Rates_EndDate = 'JavaWindow("title:=Bank Guarantee.*","displayed:=1").JavaObject("tagname:=Group","text:=Fee on Lender Shares.*").JavaObject("tagname:=Group","text:=Accrual Rules.*").JavaEdit("attached text:=End Date:")'
LIQ_ActiveSBLC_Rates_AdjustedDueDate = 'JavaWindow("title:=Bank Guarantee.*","displayed:=1").JavaObject("tagname:=Group","text:=Fee on Lender Shares.*").JavaObject("tagname:=Group","text:=Accrual Rules.*").JavaEdit("attached text:=Adjusted Due Date:")'
LIQ_ActiveSBLC_Currency_Text = 'JavaWindow("title:=Bank Guarantee.*").JavaStaticText("index:=0","enabled:=1","labeled_containers_path:=Tab:General;Group:Amounts;", "Index:=4")'
LIQ_ActiveSBLC_RiskType_Text = 'JavaWindow("title:=Bank Guarantee.*").JavaEdit("enabled:=1","labeled_containers_path:=Tab:General;", "index:=0")'
LIQ_ActiveSBLC_EffectiveDate_Text = 'JavaWindow("title:=Bank Guarantee.*").JavaStaticText("x:=569", "index:=157")'
LIQ_Active_AdjustextExpiry_Text = 'JavaWindow("title:=Bank Guarantee.*").JavaEdit("attached text:=Adjusted Expiry:")' 
LIQ_ActiveSBLC_HostBankGross_Text = 'JavaWindow("title:=Bank Guarantee.*").JavaEdit("attached text:=Host Bank Gross:")'
LIQ_ActiveSBLC_HostBankNet_Text = 'JavaWindow("title:=Bank Guarantee.*").JavaEdit("attached text:=Host Bank Net:")'
LIQ_ActiveSBLC_GlobalOriginal_Text = 'JavaWindow("title:=Bank Guarantee.*").JavaEdit("attached text:=Global Original:")'
LIQ_ActiveSBLC_GlobalCurrent_Text = 'JavaWindow("title:=Bank Guarantee.*").JavaEdit("attached text:=Global Current:")'
LIQ_Active_Beneficiaries_JavaTree = 'JavaWindow("title:=Bank Guarantee.*").JavaTree("attached text:=Drill down to set Servicing Group", "labeled_containers_path:=Tab:Banks;Group:Beneficiaries:;")'

### Cycles for SBLC ###
LIQ_CyclesForSBLC_Window = 'JavaWindow("title:=Cycles for Standby Letter of Credit.*")'
LIQ_CyclesForSBLC_Thru_Checkbox = 'JavaWindow("title:=Cycles for Standby Letter of Credit.*").JavaCheckBox("attached text:=thru:")'
LIQ_CyclesForSBLC_Thru_TextField = 'JavaWindow("title:=Cycles for Standby Letter of Credit.*").JavaEdit("index:=0")'
LIQ_CyclesForSBLC_OK_Button = 'JavaWindow("title:=Cycles for Standby Letter of Credit.*").JavaButton("attached text:=OK")'

### SBLC Issuance Fee Payment ###
LIQ_SBLCIssuanceFeePayment_Window = 'JavaWindow("title:=Standby Letter of Credit Issuance Fee Payment.*")'
LIQ_SBLCIssuanceFeePayment_Tab = 'JavaWindow("title:=Standby Letter of Credit Issuance Fee Payment.*").JavaTab("index:=0")'
LIQ_SBLCIssuanceFeePayment_EffectiveDate_TextField = 'JavaWindow("title:=Standby Letter of Credit Issuance Fee Payment.*").JavaEdit("attached text:=Effective Date:")'
LIQ_SBLCIssuanceFeePayment_Workflow_JavaTree = 'JavaWindow("title:=Standby Letter of Credit Issuance Fee Payment.*").JavaTree("attached text:=Drill down to perform Workflow item")'

### SBLC Facing Fee Payment ###
LIQ_SBLCFacingFeePayment_Window = 'JavaWindow("title:=Standby Letter of Credit Facing Fee Payment.*")'
LIQ_SBLCFacingFeePayment_Tab = 'JavaWindow("title:=Standby Letter of Credit Facing Fee Payment.*").JavaTab("index:=0")'
LIQ_SBLCFacingFeePayment_EffectiveDate_TextField = 'JavaWindow("title:=Standby Letter of Credit Facing Fee Payment.*").JavaEdit("attached text:=Effective Date:")'
LIQ_SBLCFacingFeePayment_Workflow_JavaTree = 'JavaWindow("title:=Standby Letter of Credit Facing Fee Payment.*").JavaTree("attached text:=Drill down to perform Workflow item")'

### Notice Window ###
LIQ_NoticeGroup_EditHighlightedNotice_Button = 'JavaWindow("title:=.*${Notice_Window}.*","displayed:=1").JavaButton("label:=Edit Highlighted Notice.*")'
LIQ_Notice_Email_Window = 'JavaWindow("title:=.*${Notice_Window}.*","displayed:=1")'
LIQ_Notice_Email_Created_Window = 'JavaWindow("title:=.*${Notice_Window} created.*","displayed:=1")'
LIQ_NoticeGroup_Table = 'JavaWindow("title:=.*${Notice_Window}.*","displayed:=1").JavaTree("attached text:=Drill down to.*")'

###LIQ SBLC Loan Locators ###
LIQ_ExistingSBLCForFacility_Window = 'JavaWindow("title:=Existing.*Standby Letters.*")'
LIQ_ExistingSBLCForFacility_Tree = 'JavaWindow("title:=Existing.*Standby Letters.*").JavaTree("attached text:=Drill down to open the notebook")'  

LIQ_ExistingSBLC_Window = 'JavaWindow("title:=.*Standby Letter of Credit.*")'
LIQ_ExistingSBLC_Tab = 'JavaWindow("title:=.*Standby Letter of Credit.*").JavaTab("to_description:=JavaTab")'
LIQ_ExistingSBLC_Events_JavaTree = 'JavaWindow("title:=.*Standby Letter of Credit.*").JavaTree("attached text:=Select event to view details")'
LIQ_ExistingSBLC_Options_Increase = 'JavaWindow("title:=.*Standby Letter of Credit.*").JavaMenu("label:=Options").JavaMenu("label:=Increase")'
LIQ_ExistingSBLC_Increase_Window = 'JavaWindow("title:=.*Standby Letter of Credit.*Increase.*")'
LIQ_ExistingSBLC_Increase_File_Save = 'JavaWindow("title:=.*Standby Letter of Credit.*Increase.*").JavaMenu("label:=File").JavaMenu("label:=Save")'
LIQ_ExistingSBLC_Increase_RequestedAmount_Text = 'JavaWindow("title:=.*Standby Letter of Credit.*Increase.*").JavaEdit("attached text:=Requested:")'
LIQ_ExistingSBLC_Increase_EffectiveDate_Text = 'JavaWindow("title:=.*Standby Letter of Credit.*Increase.*").JavaEdit("attached text:=Effective Date:")'
LIQ_ExistingSBLC_Increase_Reason_Text = 'JavaWindow("title:=.*Standby Letter of Credit.*Increase.*").JavaEdit("attached text:=Reason:")'
LIQ_ExistingSBLC_InquiryMode_Button = 'JavaWindow("title:=.*Standby Letter of Credit.*").JavaButton("attached text:=Notebook in Inquiry Mode.*")'
LIQ_ExistingSBLC_GlobalCurrent_Text = 'JavaWindow("title:=.*Standby Letter of Credit.*").JavaEdit("attached text:=Global Current:")'
LIQ_ExistingSBLC_Increase_NonLoan_Text = 'JavaWindow("title:=.*Standby Letter of Credit.*Increase.*").JavaEdit("attached text:=Non-Loan:")'

LIQ_ExistingSBLC_Options_Decrease = 'JavaWindow("title:=.*Standby Letter of Credit.*").JavaMenu("label:=Options").JavaMenu("label:=Decrease")'
LIQ_ExistingSBLC_Decrease_Window = 'JavaWindow("title:=.*Standby Letter of Credit.*Decrease.*")'
LIQ_ExistingSBLC_Decrease_File_Save = 'JavaWindow("title:=.*Standby Letter of Credit.*Decrease.*").JavaMenu("label:=File").JavaMenu("label:=Save")'
LIQ_ExistingSBLC_Decrease_RequestedAmount_Text = 'JavaWindow("title:=.*Standby Letter of Credit.*Decrease.*").JavaEdit("attached text:=Requested:")'
LIQ_ExistingSBLC_Decrease_EffectiveDate_Text = 'JavaWindow("title:=.*Standby Letter of Credit.*Decrease.*").JavaEdit("attached text:=Effective Date:")'
LIQ_ExistingSBLC_Decrease_Reason_Text = 'JavaWindow("title:=.*Standby Letter of Credit.*Decrease.*").JavaEdit("attached text:=Reason:")'
LIQ_ExistingSBLC_Decrease_NonLoan_Text = 'JavaWindow("title:=.*Standby Letter of Credit.*Decrease.*").JavaEdit("attached text:=Non-Loan:")'

### SBLC - For Lender Shares Assignment ###
LIQ_SBLCGurantee_SharesFor_Window = 'JavaWindow("title:=Shares for.*Issuing Banks of New Standby Letter of Credit.*")'
LIQ_SBLCGurantee_SharesFor_Options = 'JavaWindow("title:=Shares for.*Issuing Banks of New Standby Letter of Credit.*").JavaMenu("label:=Options").JavaMenu("label:=Add Contractual Servicing Group Share")'
LIQ_SBLCGuarantee_NewShare_JavaTree = 'JavaWindow("text:=New Share").JavaTree("attached text:=Select a issuing bank\\servicing group")'
LIQ_SBLCGurantee_SharesFor_NewShares_Windows = 'JavaWindow("text:=New Share")'
LIQ_SBLCGuarantee_SharesFor_OK_Button = 'JavaWindow("text:=New Share").JavaButton("attached text:=OK")'
LIQ_SBLCGuarantee_Amount_TextField = 'JavaWindow("text:=New Share").JavaEdit("attached text:=Amount:")'
LIQ_SBLCGuarantee_NewShare_OK_Button = 'JavaWindow("text:=New Share").JavaButton("attached text:=OK")'
LIQ_SBLCGuarantee_SharesFor_ListOfLenders_JavaTree = 'JavaWindow("title:=Shares for.*Issuing Banks of New Standby Letter of Credit.*").JavaTree("attached text:=Drill Down for Primary/Assignment Detail")'
LIQ_SBLCGuarantee_ServicingGroupShareFor_Window = 'JavaWindow("text:=Servicing Group Share for:.*")'
LIQ_SBLCGuarantee_ServicingGroupShareFor_ActualAmount = 'JavaWindow("text:=Servicing Group Share for:.*").JavaEdit("attached text:=Actual Amount:")'
LIQ_SBLCGuarantee_ServicingGroupShareFor_OK_JavaButton = 'JavaWindow("text:=Servicing Group Share for:.*").JavaButton("attached text:=OK")'
LIQ_SBLCGuarantee_SharesFor_PortfolioShares_JavaTree = 'JavaWindow("title:=Shares for.*Issuing Banks of New Standby Letter of Credit.*").JavaTree("attached text:=Drill Down for Portfolio Shares")'
LIQ_SBLCGuarantee_PortfolioShareEdit_Window = 'JavaWindow("title:=Portfolio Share Edit")'
LIQ_SBLCGuarantee_PortfolioShareEdit_LegalTextField = 'JavaWindow("title:=Portfolio Share Edit").JavaEdit("attached text:=Legal:")'
LIQ_SBLCGuarantee_PortfolioShareEdit_OK_JavaButton = 'JavaWindow("title:=Portfolio Share Edit").JavaButton("attached text:=OK")'
LIQ_SBLCGuarantee_HostBankShareFor_Window = 'JavaWindow("text:=Host Bank Share for:.*")'
LIQ_SBLCGuarantee_HostBankShareFor_Portfolio_JavaTree = 'JavaWindow("text:=Host Bank Share for:.*").JavaTree("attached text:=Drill down to view/edit")'
LIQ_SBLCGuarantee_HostBankShareFor_OK_JavaButton = 'JavaWindow("title:=Host Bank Share for:.*").JavaButton("attached text:=OK")'
LIQ_SBLCGurantee_SharesFor_CommentButton = 'JavaWindow("title:=Shares for.*Issuing Banks of New Standby Letter of Credit.*").JavaButton("attached text:=Comment")'
LIQ_SBLCGurantee_SharesFor_OKButton = 'JavaWindow("title:=Shares for.*Issuing Banks of New Standby Letter of Credit.*").JavaButton("attached text:=OK")'
LIQ_SBLCGuarantee_SharesFor_CancelButton = 'JavaWindow("title:=Shares for.*").JavaButton("attached text:=Cancel")'
LIQ_SBLCGuarantee_SharesFor_ActualNetAllTotal = 'JavaWindow("title:=Shares for.*").JavaEdit("attached text:=Actual Net All Total.*")'