### Bankers Acceptances Notebook ###
LIQ_BaseRateDetails_Window = 'JavaWindow("title:=Base Rate Details.*")'
LIQ_BaseRateDetails_JavaTree = 'JavaWindow("title:=Base Rate Details.*").JavaTree("attached text:=Calc Method:.*")'
LIQ_BaseRateDetails_Exit_Button = 'JavaWindow("title:=Base Rate Details.*").JavaButton("attached text:=Exit")'
LIQ_BaseRateDetails_Export_Button = 'JavaWindow("title:=Base Rate Details.*").JavaButton("attached text:=Export")'
LIQ_BaseRateDetails_CalcRate_TextField = 'JavaWindow("title:=Base Rate Details.*").JavaEdit("attached text:=Calc Rate:.*")'
LIQ_BaseRateDetails_LookbackDays_TextField = 'JavaWindow("title:=Base Rate Details.*").JavaEdit("attached text:=Lookback Days:.*")'
LIQ_BaseRateDetails_LockOutDays_TextField = 'JavaWindow("title:=Base Rate Details.*").JavaEdit("attached text:=Lockout Days:.*")'
LIQ_BaseRateDetails_CompoundingRate_TextField = 'JavaWindow("title:=Base Rate Details.*").JavaEdit("index:=3")'
LIQ_BaseRateDetails_CalcMethod_TextField = 'JavaWindow("title:=Base Rate Details.*").JavaEdit("attached text:=Calc Method:.*")'