### Payment Application Selection ###
LIQ_PaymentApplicationSelection_Window = 'JavaWindow("title:=Payment Application Selection")'
LIQ_PaymentApplicationSelection_OK_Button = 'JavaWindow("title:=Payment Application Selection").JavaButton("attached text:=OK")'
LIQ_PaymentApplicationSelection_Cancel_Button = 'JavaWindow("title:=Payment Application Selection").JavaButton("attached text:=Cancel")'
LIQ_PaymentApplicationSelection_SearchBy_Combobox = 'JavaWindow("title:=Payment Application Selection").JavaList("attached text:=Search By:")'
LIQ_PaymentApplicationSelection_SearchItem_TextField = 'JavaWindow("title:=Payment Application Selection").JavaEdit("tagname:=Text")'

### Payments ###
LIQ_Payments_Window = 'JavaWindow("title:=Payments for.*")'
LIQ_Payments_JavaTree = 'JavaWindow("title:=Payments for.*").JavaTree("attached text:=N")'
LIQ_Payments_Payoff_Checkbox = 'JavaWindow("title:=Payments for.*").JavaCheckBox("attached text:=Payoff")'
LIQ_Payments_WaiversApply_Checkbox = 'JavaWindow("title:=Payments for.*").JavaCheckBox("attached text:=Waivers Apply")'
LIQ_Payments_Create_Button = 'JavaWindow("title:=Payments for.*").JavaButton("attached text:=Create")'
LIQ_Payments_CreateApprove_Button = 'JavaWindow("title:=Payments for.*").JavaButton("attached text:=Create and Approve")'
LIQ_Payments_CreateRelease_Button = 'JavaWindow("title:=Payments for.*").JavaButton("attached text:=Create and Release")'
LIQ_Payments_Cancel_Button = 'JavaWindow("title:=Payments for.*").JavaButton("attached text:=Cancel")'
LIQ_Payments_DuePrincipal_TextField = 'JavaWindow("title:=Payments for.*").JavaEdit("x:=103", "y:=31")'
LIQ_Payments_DueInterest_TextField = 'JavaWindow("title:=Payments for.*").JavaEdit("x:=103", "y:=57")'
LIQ_Payments_DueFees_TextField = 'JavaWindow("title:=Payments for.*").JavaEdit("x:=103", "y:=82")'
LIQ_Payments_DueLateCharges_TextField = 'JavaWindow("title:=Payments for.*").JavaEdit("x:=103", "y:=107")'
LIQ_Payments_AmountField = 'JavaWindow("title:=Payments for.*").JavaEdit("attached text:=Amount:","x:=152","y:=6")'
LIQ_Payments_Currency_Dropdown = 'JavaWindow("title:=Payments for.*").JavaList("attached text:=CCY:")'
LIQ_Payments_TotalDue = 'JavaWindow("title:=Payments for.*").JavaEdit("attached text:=Total:")'
LIQ_Payments_EffectiveDate ='JavaWindow("title:=Payments for.*").JavaEdit("attached text:=Effective Date:")'

### Full Prepayment Fee ###
LIQ_FullPrepaymentFee_Window = 'JavaWindow("title:=.*Full Prepayment Fee.*")'
LIQ_FullPrepaymentFee_File_Exit = 'JavaWindow("title:=.*Full Prepayment Fee.*").JavaMenu("label:=File").JavaMenu("label:=Exit")'
LIQ_FullPrepaymentFee_JavaTab = 'JavaWindow("title:=.*Full Prepayment Fee.*").JavaTab("tagname:=TabFolder")'
LIQ_FullPrepaymentFee_JavaTree = 'JavaWindow("title:=.*Full Prepayment Fee.*").JavaTree("attached text:=Drill down to perform Workflow item")'
LIQ_FullPrepaymentFee_Options_LenderShares = 'JavaWindow("title:=.*Full Prepayment Fee.*").JavaMenu("label:=Options").JavaMenu("label:=View / Update Lender Shares")'
LIQ_FullPrepaymentFee_RequestedAmount_Textfield = 'JavaWindow("title:=.*Full Prepayment Fee.*").JavaEdit("attached text:=Requested Amount:")'
LIQ_FullPrepaymentFee_DistributeToLenders_RadioButton = 'JavaWindow("title:=.*Full Prepayment Fee.*").JavaRadioButton("attached text:=Distribute To Lenders")'

### Payment Application Paper Clip ###
LIQ_PaymentApplicationPaperClip_Window = 'JavaWindow("title:=.*Payment Application Paper Clip.*")'
LIQ_PaymentApplicationPaperClip_EffectiveDate = 'JavaWindow("title:=.*Payment Application Paper Clip.*").JavaEdit("attached text:=Effective Date:")'

### Create Cashflow Payment ###
LIQ_Payment_Options_ViewUpdateLenderShares = 'JavaWindow("title:=.* Payment.*","displayed:=1").JavaMenu("label:=Options").JavaMenu("label:=View/Update Lender Shares")'
LIQ_Payment_WorkflowItems = 'JavaWindow("title:=.* Payment.*","displayed:=1").JavaTree("attached text:=.*Workflow .*")'
LIQ_Interest_WorkflowItems = 'JavaWindow("title:=.* Interest.*","displayed:=1").JavaTree("attached text:=.*Workflow .*")'
LIQ_Payment_Cashflows_Window = 'JavaWindow("title:=Cashflows .* Payment.*","displayed:=1")'
LIQ_Payment_Cashflows_Queries_GLEntries = 'JavaWindow("title:=Cashflows .* Payment.*","displayed:=1").JavaMenu("label:=Queries").JavaMenu("label:=GL Entries")'
LIQ_Payment_Cashflows_List  = 'JavaWindow("title:=Cashflows .* Payment.*","displayed:=1").JavaTree("attached text:=Drill down to view/change details")'
LIQ_Payment_Cashflows_OK_Button = 'JavaWindow("title:=Cashflows .* Payment.*","displayed:=1").JavaButton("attached text:=OK")'
LIQ_Payment_Cashflows_RemittanceDesc_None_StaticText = 'JavaWindow("title:=Cashflows .* Payment.*").JavaStaticText("attached text:=None")'
LIQ_Payment_Cashflows_RemittanceDesc_RTGS_StaticText = 'JavaWindow("title:=Cashflows .* Payment.*").JavaStaticText("attached text:=.*RTGS.*")'
LIQ_Payment_Cashflows_RemittanceDesc_IMT_StaticText = 'JavaWindow("title:=Cashflows .* Payment.*").JavaStaticText("attached text:=.*IMT.*")'
LIQ_Payment_Cashflows_DetailsforCashflow_Window = 'JavaWindow("title:=Details for Cashflow.*")'
LIQ_Payment_Cashflows_DetailsforCashflow_SelectRI_Button = 'JavaWindow("title:=Details for Cashflow.*").JavaButton("attached text:=Select Remittance Instructions")'
LIQ_Payment_Cashflows_DetailsforCashflow_IMTDetail_Button = 'JavaWindow("title:=Details for Cashflow.*").JavaButton("attached text:=IMT Detail")'
LIQ_Payment_Cashflows_DetailsforCashflow_Exit_Button = 'JavaWindow("title:=Details for Cashflow.*").JavaButton("attached text:=Exit")'
LIQ_Payment_Cashflows_DetailsforCashflow_OK_Button = 'JavaWindow("title:=Details for Cashflow.*").JavaButton("attached text:=OK")'
LIQ_Payment_Cashflows_ChooseRemittance_Window = 'JavaWindow("title:=Choose Remittance Instructions")'
LIQ_Payment_Cashflows_ChooseRemittance_List = 'JavaWindow("title:=Choose Remittance Instructions").JavaTree("attached text:=Drill down to view details")'
LIQ_Payment_Cashflows_ChooseRemittance_OK_Button = 'JavaWindow("title:=Choose Remittance Instructions").JavaButton("attached text:=OK")'
LIQ_Payment_Cashflows_SetToDoIt_Button = 'JavaWindow("title:=Cashflows .* Payment.*").JavaButton("attached text:=Set Selected Item To.*Do It.*")'
LIQ_Payment_Cashflows_SetUndoIt_Button = 'JavaWindow("title:=Cashflows .* Payment.*").JavaButton("attached text:=Set Selected Item To.*Undo It.*")'
LIQ_Payment_Cashflows_ViewOutgoingIMTMessages_Window = 'JavaWindow("title:=View Outgoing IMT Messages")'
LIQ_Payment_Cashflows_ViewOutgoingIMTMessages_Cancel_Button = 'JavaWindow("title:=View Outgoing IMT Messages").JavaButton("attached text:=Cancel")'
LIQ_Payment_Cashflows_Options_MarkAllToRelease = 'JavaWindow("title:=Cashflows .*").JavaMenu("label:=Options").JavaMenu("label:=Mark All To Release")'
LIQ_Payment_Cashflow_HostBankCash_JavaEdit = 'JavaWindow("title:=Cashflows .* Ongoing Fee Payment.*").JavaStaticText("to_class:=JavaStaticText","index:=28")'
LIQ_Payment_Queries_GLEntries_Cashflow = 'JavaWindow("title:=Cashflows .* Ongoing Fee Payment.*").JavaMenu("label:=Queries").JavaMenu("label:=GL Entries")'
LIQ_Payment_Cashflows_ChooseRemittance_CustomInstructions_CheckBox = 'JavaWindow("title:=Choose Remittance Instructions").JavaCheckBox("attached text:=Custom Instructions")'
LIQ_Payment_Cashflows_ChooseRemittance_Details_Button = 'JavaWindow("title:=Choose Remittance Instructions").JavaButton("attached text:=Details")'
LIQ_Payment_Cashflows_RemittanceInstructionsDetail_Window = 'JavaWindow("title:=Remittance Instructions Detail--Type:.*")'
LIQ_Payment_Cashflows_RemittanceInstructionsDetail_Tab = 'JavaWindow("title:=Remittance Instructions Detail--Type:.*").JavaTab("tagname:=TabFolder")'
LIQ_Payment_Cashflows_RemittanceInstructionsDetail_Method_List = 'JavaWindow("title:=Remittance Instructions Detail--Type:.*").JavaList("attached text:=Method:")'
LIQ_Payment_Cashflows_RemittanceInstructionsDetail_Description_Field = 'JavaWindow("title:=Remittance Instructions Detail--Type:.*").JavaEdit("attached text:=Description:")'
LIQ_Payment_Cashflows_RemittanceInstructionsDetail_FileSave_Menu = 'JavaWindow("title:=Remittance Instructions Detail--Type:.*").JavaMenu("label:=File").JavaMenu("label:=Save")'
LIQ_Payment_Cashflows_RemittanceInstructionsDetail_FileExit_Menu = 'JavaWindow("title:=Remittance Instructions Detail--Type:.*").JavaMenu("label:=File").JavaMenu("label:=Exit")'
LIQ_Payment_Cashflow_HostBankCashNet_Amount = 'JavaWindow("title:=Cashflows .* Payment.*").JavaStaticText("to_class:=JavaStaticText","index:=28")'
LIQ_Payment_Cashflow_IncompleteCashfromBorrower_Amount = 'JavaWindow("title:=Cashflows .* Payment.*").JavaStaticText("to_class:=JavaStaticText","index:=26")'
LIQ_Payment_Cashflow_IncompleteCashtoLender_Amount = 'JavaWindow("title:=Cashflows .* Payment.*").JavaStaticText("to_class:=JavaStaticText","index:=27")'
LIQ_Payment_Queries_GLEntries_Cashflow = 'JavaWindow("title:=Cashflows .* Payment.*").JavaMenu("label:=Queries").JavaMenu("label:=GL Entries")'
LIQ_Payment_Queries_GLEntries_Menu = 'JavaWindow("title:=.* Payment.*").JavaMenu("label:=Queries").JavaMenu("label:=GL Entries")'