### Trade Entry Window ###
LIQ_TradeEntry_Window = 'JavaWindow("title:=Trade Entry")'
LIQ_TradeEntry_File_Exit = 'JavaWindow("title:=Trade Entry").JavaMenu("label:=File").JavaMenu("label:=Exit")'
LIQ_TradeEntry_File_Save = 'JavaWindow("title:=Trade Entry").JavaMenu("label:=File").JavaMenu("label:=Save")'
LIQ_TradeEntry_HostEntity_Dropdown = 'JavaWindow("title:=Trade Entry").JavaList("attached text:=Host Entity.*")'
LIQ_TradeEntry_HostLocation_Dropdown = 'JavaWindow("title:=Trade Entry").JavaList("attached text:=Host Location.*")'
LIQ_TradeEntry_BuySell_Dropdown = 'JavaWindow("title:=Trade Entry").JavaList("attached text:=Buy/Sell.*")'
LIQ_TradeEntry_LenderShareType_Dropdown = 'JavaWindow("title:=Trade Entry").JavaList("attached text:=Lender Share Type.*")'
LIQ_TradeEntry_RiskBook_Dropdown = 'JavaWindow("title:=Trade Entry").JavaList("index:=4")'
LIQ_TradeEntry_Deal_Dropdown = 'JavaWindow("title:=Trade Entry").JavaList("attached text:=Deal.*")'
LIQ_TradeEntry_CounterpartyInstitution_Button = 'JavaWindow("title:=Trade Entry").JavaButton("attached text:=Counterparty Institution.*")'
LIQ_TradeEntry_CounterpartyTrader_Dropdown = 'JavaWindow("title:=Trade Entry").JavaList("index:=7")'
LIQ_TradeEntry_AssignmentFeeDecision_Dropdown = 'JavaWindow("title:=Trade Entry").JavaList("attached text:=Assignment Fee Decision.*")'
LIQ_TradeEntry_LegalTradeDate_Textbox = 'JavaWindow("title:=Trade Entry").JavaEdit("attached text:=Legal Trade Date.*")'
LIQ_TradeEntry_ExpectedCloseDate_Textbox = 'JavaWindow("title:=Trade Entry").JavaEdit("attached text:=Expected Close Date.*")'
LIQ_TradeEntry_PortfolioAllocationBranch_Dropdown = 'JavaWindow("title:=Trade Entry").JavaList("index:=10")'
LIQ_TradeEntry_TotalCommitment_Textbox = 'JavaWindow("title:=Trade Entry").JavaEdit("attached text:=Total Commitment.*")'
LIQ_TradeEntry_ProrateFacilities_Button = 'JavaWindow("title:=Trade Entry").JavaButton("attached text:=Prorate Facilities.*")'
LIQ_TradeEntry_Facilities_JavaTree = 'JavaWindow("title:=Trade Entry").JavaTree("attached text:=Drill down to update.*")'

### Facility Trade Entry Window###
LIQ_FacilityTradeEntry_Window = 'JavaWindow("title:=Facility Trade Entry")'
LIQ_FacilityTradeEntry_Branch_JavaTree = 'JavaWindow("title:=Facility Trade Entry").JavaTree("tagname:=Branch.*")'
LIQ_FacilityTradeEntry_Ok_Button = 'JavaWindow("title:=Facility Trade Entry").JavaButton("attached text:=OK.*")'