### Initial Drawdown Notebook ###
LIQ_InitialDrawdown_File_Exit = 'JavaWindow("title:=.*Initial Drawdown.*","displayed:=1").JavaMenu("label:=File").JavaMenu("label:=Exit")'
LIQ_InitialDrawdown_Options_InterestCapitalization = 'JavaWindow("title:=.*Initial Drawdown.*","displayed:=1").JavaMenu("label:=Options").JavaMenu("label:=Interest Capitalization.*")'
LIQ_InitialDrawdown_Options_CapitalizeInterest = 'JavaWindow("title:=.*Loan.*Active","displayed:=1").JavaMenu("label:=Options").JavaMenu("label:=Capitalize Interest.*")'
LIQ_InitialDrawdown_Options_Payments = 'JavaWindow("title:=.*Loan.*Active","displayed:=1").JavaMenu("label:=Options").JavaMenu("label:=Payment.*")'
LIQ_InitialDrawdown_Options_LoanNotebook = 'JavaWindow("title:=.*Initial Drawdown.*","displayed:=1").JavaMenu("label:=Options").JavaMenu("label:=Loan Notebook.*")'
LIQ_InitialDrawdown_Options_UpfrontFreeFromBorrower = 'JavaWindow("title:=.*Initial Drawdown.*").JavaMenu("label:=Options").JavaMenu("label:=Upfront Fee From Borrower.*")'
LIQ_InitialDrawdown_Window = 'JavaWindow("title:=.*Initial Drawdown.*")'
LIQ_InitialDrawdown_Tab = 'JavaWindow("title:=.*Initial Drawdown.*","displayed:=1").JavaTab("toolkit class:=.*TabFolder")'
LIQ_InitialDrawdown_Inquiry_Button = 'JavaWindow("title:=.*Initial Drawdown.*","displayed:=1").JavaButton("attached text:=Notebook in Inquiry Mode - F7.*")'
LIQ_InitialDrawdown_WorkflowAction = 'JavaWindow("title:=.*Initial Drawdown.*","displayed:=1").JavaTree("attached text:=Drill down to perform Workflow item")'
LIQ_InitialDrawdown_AwaitingRelease_Status_Window = 'JavaWindow("title:=.*Initial Drawdown.*Awaiting Release.*","displayed:=1")'
LIQ_InitialDrawdown_Options_Cashflow = 'JavaWindow("title:=.*Initial Drawdown.*").JavaMenu("label:=Options").JavaMenu("label:=Cashflow")'
LIQ_InitialDrawdown_Options_FacilityNotebook = 'JavaWindow("title:=.*Initial Drawdown .*").JavaMenu("label:=Options").JavaMenu("label:=Facility Notebook")'
LIQ_InitialDrawdown_Options_RepaymentSchedule = 'JavaWindow("title:=.*Initial Drawdown .*").JavaMenu("label:=Options").JavaMenu("label:=Repayment Schedule")' 
LIQ_InitialDrawdown_Options_CostOfFunds = 'JavaWindow("title:=.*Initial Drawdown .*").JavaMenu("label:=Options").JavaMenu("label:=View/Update Match Funded Cost of Funds")' 
LIQ_InitialDrawdown_AwaitingApproval_Status_Window = 'JavaWindow("title:=.*Initial Drawdown .*Awaiting Approval.*")'
LIQ_InitialDrawdown_AwaitingRateApproval_Status_Window = 'JavaWindow("title:=.*Initial Drawdown .*Awaiting Rate Approval.*")'
LIQ_InitialDrawdown_Released_Status_Window = 'JavaWindow("title:=.*Initial Drawdown .*Released.*")'
LIQ_InitialDrawdown_File_Save = 'JavaWindow("title:=.*Initial Drawdown.*").JavaMenu("label:=File").JavaMenu("label:=Save")'
LIQ_InitialDrawdown_Options_Facility = 'JavaWindow("title:=.*Initial Drawdown.*").JavaMenu("label:=Options").JavaMenu("label:=Facility Notebook")'
LIQ_InitialDrawdown_Options_OutstandingServicingGroupDetails = 'JavaWindow("title:=.*Initial Drawdown.*").JavaMenu("label:=Options").JavaMenu("label:=Outstanding Servicing Group Details")'
LIQ_InitialDrawdown_Options_ViewOrUpdateLenderShares = 'JavaWindow("title:=.*Initial Drawdown.*").JavaMenu("label:=Options").JavaMenu("label:=View/Update Lender Shares")'
LIQ_Loan_Options_OutstandingServicingGroupDetails = 'JavaWindow("title:=.*Loan.*Active").JavaMenu("label:=Options").JavaMenu("label:=Outstanding Servicing Group Details")'
LIQ_InitialDrawdown_Options_MatchFundedCostOfFunds = 'JavaWindow("title:=.*Loan.*Active").JavaMenu("label:=Options").JavaMenu("label:=View Match Funded Cost of Funds")' 
LIQ_InitialDrawdown_Alias_TextField = 'JavaWindow("title:=.*Initial Drawdown.*").JavaEdit("attached text:=Alias:")'
LIQ_InitialDrawdown_PricingOption_List = 'JavaWindow("title:=.*Initial Drawdown.*").JavaList("attached text:=Pricing Option:")'
LIQ_InitialDrawdown_Borrower_List = 'JavaWindow("title:=.*Initial Drawdown.*").JavaList("attached text:=Borrower:")'
LIQ_InitialDrawdown_Currency_List = 'JavaWindow("title:=.*Initial Drawdown.*").JavaList("attached text:=Currency:")'
LIQ_InitialDrawdown_Ok_Button = 'JavaWindow("title:=.*Initial Drawdown.*").JavaButton("attached text:=OK")'


### Quick Repricing ###
LIQ_QuickRepricing_Window = 'JavaWindow("text:=.*Quick Repricing.*")'
LIQ_QuickRepricing_Tab = 'JavaWindow("text:=.*Quick Repricing.*").JavaTab("tagname:=TabFolder")'
LIQ_QuickRepricing_JavaTree = 'JavaWindow("text:=.*Quick Repricing.*").JavaTree("attached text:=Drill down to perform Workflow item")'

###Cost of Funds###
LIQ_CostOfFunds_JavaTree = 'JavaWindow("title:=.*Cost Of Funds .*").JavaTree("tagname:=Tree")'
LIQ_CostOfFunds_ViewAccrual_Button = 'JavaWindow("title:=.*Cost Of Funds .*").JavaButton("label:=View Accrual")' 
LIQ_CostOfFunds_COFPricingFormula_Button = 'JavaWindow("title:=.*Cost Of Funds .*").JavaButton("label:=COF Pricing Formula")'
LIQ_CostOfFunds_COFBaseRateHistory_Button = 'JavaWindow("title:=.*Cost Of Funds .*").JavaButton("label:=COF Base Rate History")'
LIQ_CostOfFunds_COFSpreadHistory_Button = 'JavaWindow("title:=.*Cost Of Funds .*").JavaButton("label:=COF Spread History")' 
LIQ_CostOfFunds_Accrual_Window = 'JavaWindow("title:=Cost Of Funds Accrual:")'
LIQ_CostOfFunds_Accrual_JavaTree = 'JavaWindow("title:=Cost Of Funds Accrual:").JavaTree("tagname:=Drill down to see details")'
LIQ_CostOfFunds_COFAccrualCycleDetail_Window = 'JavaWindow("title:=Cost Of Funds Accrual Cycle Detail")'
LIQ_CostOfFunds_COFAccrualCycleDetail_LineItems_Button = 'JavaWindow("title:=Cost Of Funds Accrual Cycle Detail").JavaButton("text:=&Line Items")'
LIQ_CostOfFunds_COFLineItems_Window = 'JavaWindow("title:=Cost Of Funds Line Items .*")'
LIQ_CostOfFunds_COFLineItems_JavaTree = 'JavaWindow("title:=Cost Of Funds Line Items .*").JavaTree("tagname:=Tree")'
LIQ_CostOfFunds_Cycles_Window = 'JavaWindow("title:=Choose a cycle")'
LIQ_CostOfFunds_Cycles_JavaTree = 'JavaWindow("title:=Choose a cycle").JavaTree("tagname:=Drill down to select a cycle")'
LIQ_CostOfFunds_Cycles_OK_Button = 'JavaWindow("title:=Choose a cycle").JavaButton("text:=&OK")'

### General Tab ###
LIQ_InitialDrawdown_ActualAmt_Textfield  = 'JavaWindow("title:=.*Initial Drawdown.*").JavaEdit("attached text:=Actual Amt:")'
LIQ_InitialDrawdown_RequestedAmt_Textfield  = 'JavaWindow("title:=.*Initial Drawdown.*").JavaEdit("attached text:=Requested Amt:")'
LIQ_InitialDrawdown_EffectiveDate_Datefield  = 'JavaWindow("title:=.*Initial Drawdown.*").JavaEdit("attached text:=Effective Date:")'
LIQ_InitialDrawdown_Repricing_Dropdownlist  = 'JavaWindow("title:=.*Initial Drawdown.*").JavaList("attached text:=Repricing Frequency:")'
LIQ_InitialDrawdown_IntCycleFreq_Dropdownlist  = 'JavaWindow("title:=.*Initial Drawdown.*").JavaList("attached text:=Int\. Cycle Freq:")'
LIQ_InitialDrawdown_MaturityDate_Datefield  = 'JavaWindow("title:=.*Initial Drawdown.*").JavaEdit("attached text:=Maturity Date:")'
LIQ_InitialDrawdown_ActualDueDate_Datefield  = 'JavaWindow("title:=.*Initial Drawdown.*").JavaEdit("attached text:=Actual Due Date:")'
LIQ_InitialDrawdown_RepricingDate_Datefield  = 'JavaWindow("title:=.*Initial Drawdown.*").JavaEdit("attached text:=Repricing Date:")'
LIQ_InitialDrawdown_AccrualEndDate_Datefield = 'JavaWindow("title:=.*Initial Drawdown.*").JavaEdit("attached text:=Accrual End Date:")'
LIQ_InitialDrawdown_AdjustedDueDate_Datefield = 'JavaWindow("title:=.*Initial Drawdown.*").JavaEdit("attached text:=Adjusted Due Date:")'
LIQ_InitialDrawdown_Accrue_Dropdown = 'JavaWindow("title:=.*Initial Drawdown.*").JavaList("attached text:=Accrue:")'
LIQ_InitialDrawdown_RequestedCCY_StaticDropdown = 'JavaWindow("title:=.*Initial Drawdown .*").JavaList("attached text:=Requested CCY:")'
LIQ_InitialDrawdown_ActualCCY_StaticText = 'JavaWindow("title:=.*Initial Drawdown .*").JavaObject("tagname:=Group","text:=Amounts").JavaStaticText("index:=4")'
LIQ_InitialDrawdown_RepaymentScheduleSync_Checkbox = 'JavaWindow("title:=.*Initial Drawdown.*").JavaCheckbox("attached text:=Repayment Schedule Sync")'
LIQ_InitialDrawdown_InterestDueUponRepricing_Checkbox = 'JavaWindow("title:=.*Initial Drawdown.*").JavaCheckBox("attached text:=Interest Due Upon Repricing")'
LIQ_InitialDrawdown_Accrue_Dropdownlist  = 'JavaWindow("title:=.*Initial Drawdown.*").JavaList("attached text:=Accrue:")'
LIQ_InitialDrawdown_RiskType_Button = 'JavaWindow("title:=.*Initial Drawdown.*").JavaButton("attached text:=Risk Type:")'
LIQ_InitialDrawdown_Sublimit_Button = 'JavaWindow("title:=.*Initial Drawdown .*").JavaButton("attached text:=Sublimit:")'
LIQ_InitialDrawdown_SelectRiskType_Window = 'JavaWindow("title:=Select Risk Type")'
LIQ_InitialDrawdown_SelectRiskType_JavaTree = 'JavaWindow("title:=Select Risk Type").JavaTree("attached text:=Drill down to select")'
LIQ_InitialDrawdown_SelectRiskType_OK_Button = 'JavaWindow("title:=Select Risk Type").JavaButton("attached text:=OK")'
LIQ_InitialDrawdown_SetRateJavaTree = 'JavaWindow("title:=.*Initial Drawdown.*").JavaTree("attached text:=Select event to view details.*")'
LIQ_InitialDrawdown_Calendar_AddButton = 'JavaWindow("title:=.*Initial Drawdown.*").JavaButton("attached text:=Add.*")'
LIQ_InitialDrawdown_Calendar_HolidayCalendar_Window = 'JavaWindow("title:=Holiday Calendar.*")'
LIQ_InitialDrawdown_Calendar_HolidayCalendar = 'JavaWindow("title:=Holiday Calendar.*").JavaList("attached text:=Calendar.*")'
LIQ_InitialDrawdown_Calendar_BorrowerIntentNotice_CheckBox = 'JavaWindow("title:=Holiday Calendar.*").JavaCheckbox("attached text:=Borrower Intent Notice.*")'
LIQ_InitialDrawdown_Calendar_FXRateSettingNotice_CheckBox = 'JavaWindow("title:=Holiday Calendar.*").JavaCheckbox("attached text:=FX Rate Setting Notice.*")'
LIQ_InitialDrawdown_Calendar_InterestRateSettingNotice_CheckBox = 'JavaWindow("title:=Holiday Calendar.*").JavaCheckbox("attached text:=Interest Rate Setting Notice.*")'
LIQ_InitialDrawdown_Calendar_EffectiveDate_CheckBox = 'JavaWindow("title:=Holiday Calendar.*").JavaCheckbox("attached text:=Effective Date.*")'
LIQ_InitialDrawdown_Calendar_PaymentAdviceDates_CheckBox = 'JavaWindow("title:=Holiday Calendar.*").JavaCheckbox("attached text:=Payment Advice Dates.*")'
LIQ_InitialDrawdown_Calendar_Billing_CheckBox = 'JavaWindow("title:=Holiday Calendar.*").JavaCheckbox("attached text:=Billing.*")'
LIQ_InitialDrawdown_Calendar_HolidayCalendar_OkButton = 'JavaWindow("title:=Holiday Calendar.*").JavaButton("attached text:=OK.*")'
LIQ_InitialDrawdown_Calendar_JavaTree = 'JavaWindow("title:=.*Initial Drawdown.*").JavaTree("attached text:=Drill down for details.*")'
LIQ_InitialDrawdown_Calendar_DeleteButton = 'JavaWindow("title:=.*Initial Drawdown.*").JavaButton("attached text:=Delete.*")'
LIQ_InitialDrawdown_Sublimit_Window = 'JavaWindow("title:=Select Sublimit","displayed:=1")'
LIQ_InitialDrawdown_Sublimit_JavaTree = 'JavaWindow("title:=Select Sublimit","displayed:=1").JavaTree("attached text:=Drill down to select")'
LIQ_InitialDrawdown_Sublimit_OK_Button = 'JavaWindow("title:=Select Sublimit","displayed:=1").JavaButton("attached text:=OK")'
LIQ_InitialDrawdown_RiskType_Window = 'JavaWindow("title:=Select Risk Type","displayed:=1")'
LIQ_InitialDrawdown_RiskType_JavaTree = 'JavaWindow("title:=Select Risk Type","displayed:=1").JavaTree("attached text:=Drill down to select")'
LIQ_InitialDrawdown_RiskType_OK_Button = 'JavaWindow("title:=Select Risk Type","displayed:=1").JavaButton("attached text:=OK")'

### Rates Tab ###
LIQ_InitialDrawdown_RatesTab_ARRParameters_Button = 'JavaWindow("title:=.*Initial Drawdown.*").JavaButton("attached text:=ARR Parameters")'
LIQ_InitialDrawdown_BaseRate_Button = 'JavaWindow("title:=.*Initial Drawdown.*").JavaButton("attached text:=Base Rate:")'
LIQ_InitialDrawdown_BorrowerBaseRate_Textfield = 'JavaWindow("label:=Set Base Rate").JavaEdit("attached text:=Borrower Base Rate:")'
LIQ_InitialDrawdown_BaseRate_Textfield = 'JavaWindow("label:=Set Base Rate").JavaEdit("abs_x:=388","abs_y:=349")'
LIQ_InitialDrawdown_SetBaseRate_OK_Button = 'JavaWindow("label:=Set Base Rate").JavaButton("attached text:=OK")'
LIQ_InitialDrawdown_BorrowerBaseRate_Field = 'JavaWindow("title:=Set Base Rate.*").JavaEdit("index:=0")'
LIQ_InitialDrawdown_Spread_Current_Text = 'JavaWindow("title:=.*Initial Drawdown .*").JavaObject("tagname:=Group","text:=Interest Rates").JavaEdit("index:=6")'
LIQ_InitialDrawdown_InterestRateIsFloating_Checkbox = 'JavaWindow("title:=.*Initial Drawdown .*").JavaCheckBox("attached text:=Interest Rate is Floating")'
LIQ_InitialDrawdown_SpreadAdjustmentApplies_Checkbox = 'JavaWindow("title:=.*Initial Drawdown .*").JavaCheckBox("attached text:=Spread Adjustment Applies")'
LIQ_InitialDrawdown_SpreadAdjustment_Current_TextField = 'JavaWindow("title:=.*Initial Drawdown .*").JavaObject("tagname:=Group","text:=Interest Rates").JavaEdit("index:=2")'
LIQ_InitialDrawdown_SpreadAdjustment_Button = 'JavaWindow("title:=.*Initial Drawdown .*").JavaButton("attached text:=.*Spread Adj.*")'
LIQ_InitialDrawdown_PctOfRateFormula_Button = 'JavaWindow("title:=.*Initial Drawdown .*").JavaButton("attached text:=Pct of Rate Formula:*")'
LIQ_InitialDrawdown_PctOfRateFormulaUsage_Button = 'JavaWindow("title:=.*Initial Drawdown .*").JavaButton("attached text:=Pct of Rate Formula Usage:*")'
LIQ_InitialDrawdown_AllInRateCap_TextField = 'JavaWindow("title:=.*Initial Drawdown .*").JavaEdit("index:=4")'
LIQ_InitialDrawdown_AllInRateFloor_TextField = 'JavaWindow("title:=.*Initial Drawdown .*").JavaEdit("index:=3")'
LIQ_InitialDrawdown_AllInRateCap_Button = 'JavaWindow("title:=.*Initial Drawdown .*").JavaObject("tagname:=Group", "text:=Interest Rates").JavaButton("index:=2")'
LIQ_InitialDrawdown_AllInRateFloor_Button = 'JavaWindow("title:=.*Initial Drawdown .*").JavaObject("tagname:=Group", "text:=Interest Rates").JavaButton("index:=1")'
LIQ_InitialDrawdown_AllInRate = 'JavaWindow("title:=.*Initial Drawdown .*").JavaEdit("attached text:=All-In Rate:")'
LIQ_InitialDrawdown_AllInRateFromPricing_Text = 'JavaWindow("title:=.*Initial Drawdown.*").JavaObject("tagname:=Group", "text:=Interest Rates").JavaEdit("x:=191","y:=187")'
LIQ_InitialDrawdown_BaseRateFloor_Button = 'JavaWindow("title:=.*Initial Drawdown .*").JavaObject("tagname:=Group", "text:=Interest Rates").JavaButton("index:=8")'
LIQ_InitialDrawdown_PenaltySpreadStatus_Rate_Button = 'JavaWindow("title:=.*Initial Drawdown.*").JavaButton("attached text:=Rate:")'
LIQ_InitialDrawdown_PenaltySpreadStatus_Status_Button = 'JavaWindow("title:=.*Initial Drawdown.*").JavaButton("attached text:=Status:")'
LIQ_InitialDrawdown_AcceptBaseRate = 'JavaWindow("title:=Set Base Rate.*").JavaButton("attached text:=Accept Rate from Pricing.*")'
LIQ_InitialDrawdown_BaseRateFromPricing_Text = 'JavaWindow("title:=Set Base Rate.*").JavaEdit("attached text:=Base Rate from Pricing:")'
LIQ_InitialDrawdown_BaseRate_Current_Text = 'JavaWindow("title:=.*Initial Drawdown.*").JavaObject("tagname:=Group","text:=Interest Rates").JavaEdit("index:=7")'
LIQ_InitialDrawdown_SpreadRate_Button = 'JavaWindow("title:=.*Initial Drawdown.*").JavaButton("attached text:=Spread:")'
LIQ_InitialDrawdown_AdditionalSpread_Current_Text = 'JavaWindow("title:=.*Initial Drawdown .*").JavaObject("tagname:=Group","text:=Interest Rates").JavaEdit("index:=2")'
LIQ_InitialDrawdown_RateBasis_Dropdownlist = 'JavaWindow("title:=.*Initial Drawdown.*").JavaObject("tagname:=Group", "text:=Interest Rates").JavaList("attached text:=Rate Basis:")'
LIQ_InitialDrawdown_SpreadRate_TextField = 'JavaWindow("title:=Override Spread").JavaEdit("attached text:=Spread Override:")'
LIQ_InitialDrawdown_SpreadAdjustment_TextField = 'JavaWindow("title:=Set Spread Adjustment Rate").JavaEdit("tagname:=Text")'
LIQ_InitialDrawdown_SpreadAdjustment_OK_Button = 'JavaWindow("title:=Set Spread Adjustment Rate").JavaButton("attached text:=OK")'
LIQ_InitialDrawdown_SpreadRate_OKButton = 'JavaWindow("title:=Override Spread").JavaButton("attached text:=OK")'
LIQ_InitialDrawdown_PenaltySpread_SpreadRate_Textfield = 'JavaWindow("title:=.*Initial Drawdown.*").JavaObject("text:=Penalty Spread").JavaEdit("index:=0")'
LIQ_InitialDrawdown_AcceptRateFromInterpolation = 'JavaWindow("title:=Set Base Rate.*").JavaButton("attached text:=Accept Rate from Interpolation.*")'
LIQ_InitialDrawdown_PIKRate_Button = 'JavaWindow("title:=.*Initial Drawdown.*").JavaButton("attached text:=PIK Rate:")'

### Codes Tab ###
LIQ_InitialDrawdown_Codes_TreasuryReportingArea_Dropdownlist = 'JavaWindow("title:=.*Initial Drawdown.*").JavaList("tagname:=OTHER - All Other Loans", "index:=0")'
LIQ_InitialDrawdown_Codes_Purpose_Dropdownlist = 'JavaWindow("title:=.*Initial Drawdown.*").JavaList("tagname:=OTHER - All Other Loans", "index:=1")'
LIQ_InitialDrawdown_Codes_PledgeCode_Dropdownlist = 'JavaWindow("title:=.*Initial Drawdown.*").JavaList("attached text:=Pledge Codes:")'
LIQ_InitialDrawdown_Codes_ConsolidationType_Dropdownlist = 'JavaWindow("title:=.*Initial Drawdown.*").JavaList("attached text:=Overage Rule:")'
LIQ_InitialDrawdown_Codes_UnscheduledPrincipalApplicationMethod_Dropdownlist  = 'JavaWindow("title:=.*Initial Drawdown.*").JavaList("labeled_containers_path:=Tab:Codes;", "attached text:=.*Interest.*")'
LIQ_InitialDrawdown_Codes_MissedPaymentsPrincipal_Dropdownlist = 'JavaWindow("title:=.*Initial Drawdown.*").JavaList("labeled_containers_path:=Tab:Codes;Group:MissedPayments;", "attached text:=Principal.*")'
LIQ_InitialDrawdown_Codes_MissedPaymentsInterest_Dropdownlist = 'JavaWindow("title:=.*Initial Drawdown.*").JavaList("labeled_containers_path:=Tab:Codes;Group:MissedPayments;", "attached text:=.*Interest.*")'

### Penalty Spread Editor ###
LIQ_InitialDrawdown_PenaltySpreadEditor_Window = 'JavaWindow("title:=Penalty Spread Editor")'
LIQ_InitialDrawdown_PenaltySpreadEditor_PenaltySpead_Textfield = 'JavaWindow("title:=Penalty Spread Editor").JavaEdit("attached text:=Penalty Spread:")'
LIQ_InitialDrawdown_PenaltySpreadEditor_PenaltySpread_OK_Button = 'JavaWindow("title:=Penalty Spread Editor").JavaButton("attached text:=OK")'
LIQ_InitialDrawdown_PenaltyStatusEditor_Window = 'JavaWindow("title:=Penalty Status Editor")'
LIQ_InitialDrawdown_PenaltyStatusEditor_Status_Dropdown = 'JavaWindow("title:=Penalty Status Editor").JavaList("index:=0")'
LIQ_InitialDrawdown_PenaltyStatusEditor_OK_Button = 'JavaWindow("title:=Penalty Status Editor").JavaButton("attached text:=OK")'

### For Rate Setting Notices ###
LIQ_Notice_RateSettingNotice_Window = 'JavaWindow("title:=.* Rate .* Notice Group.*")'
LIQ_Notice_RateSettingNotice_Exit_Button = 'JavaWindow("title:=Rate .* Notice Group.*").JavaButton("attached text:=Exit")' 
LIQ_Notice_RateSettingNotice_Information_Table = 'JavaWindow("title:=Rate .* Notice Group.*").JavaTree("attached text:=Drill down to mark notices")'
LIQ_Notice_RateSettingNotice_Send_Button = 'JavaWindow("title:=Rate .* Notice Group.*").JavaButton("attached text:=Send")'
LIQ_Notice_RateSettingNotice_EditHighlightedNotice_Button = 'JavaWindow("title:=Rate .* Notice Group.*").JavaButton("attached text:=Edit Highlighted Notices")'
LIQ_Notice_RateSettingNotice_Edit_Window = 'JavaWindow("title:=Rate .* Notice created.*")'
LIQ_Notice_RateSettingNotice_Edit_Email = 'JavaWindow("title:=Rate .* Notice created.*").JavaEdit("attached text:=E-mail:")'
LIQ_Notices_RateSettingNotice_Exit_Button = 'JavaWindow("title:=Rate Setting Notice.*").JavaButton("attached text:=Exit")'
LIQ_Notice_RateSettingNotice_Email = 'JavaWindow("title:=Rate .* Notice created.*").JavaEdit("attached text:=E-mail:")'

### Loan Window ###
LIQ_InitialDrawdown_FileMenu_Save = 'JavaWindow("title:=.*Loan.*Active").JavaMenu("label:=File").JavaMenu("label:=Save")'
LIQ_InitialDrawdown_FileMenu_Exit = 'JavaWindow("title:=.*Loan.*Active").JavaMenu("label:=File").JavaMenu("label:=Exit")'
LIQ_Loan_CyclesFor_Window = 'JavaWindow("title:=Cycles for.*")'
LIQ_Loan_CyclesFor_ProjectedDue_RadioButton = 'JavaWindow("title:=Cycles for.*").JavaRadioButton("attached text:=Projected Due")'
LIQ_Loan_CyclesFor_List = 'JavaWindow("title:=Cycles for.*").JavaTree("attached text:=Choose a cycle to make a payment against")'
LIQ_Loan_CyclesFor_OK_Button = 'JavaWindow("title:=Cycles for.*", "displayed:=1").JavaButton("attached text:=OK")'
LIQ_CyclesFor_Payment_Texfield = 'JavaWindow("title:=Cycles for.*", "displayed:=1").JavaEdit("attached text:=for Payment Amount:")'
LIQ_CyclesFor_Interest_Textfield = 'JavaWindow("title:=Cycles for.*", "displayed:=1").JavaEdit("attached text:=Interest Due:")'
LIQ_Loan_ActualDueDate_Textfield = 'JavaWindow("title:=.*Loan.*ctive.*").JavaEdit("attached text:=Actual Due Date:")'
LIQ_Loan_EffectiveDate_Textfield = 'JavaWindow("title:=.*Loan.*ctive.*").JavaStaticText("x:=580", "y:=117")'
LIQ_Loan_AdjustedDate_Textfield = 'JavaWindow("title:=.*Loan.*ctive.*").JavaEdit("attached text:=Adjusted Due Date:")'
LIQ_LoanInquire_Button = 'JavaWindow("title:=.*Loan.*Active").JavaButton("attached text:=Notebook in Inquiry Mode - F7.*")'
LIQ_Loan_AccrualEndDate = 'JavaWindow("title:=.*Loan.*Active").JavaEdit("attached text:=Accrual End Date:")'

### Bid Initial Drawdown Notebook ###
LIQ_BidInitialDrawdown_Window = 'JavaWindow("title:=.*Bid Initial Drawdown.*","displayed:=1")'
LIQ_BidInitialDrawdown_Requested_TextField = 'JavaWindow("title:=.*Bid Initial Drawdown.*","displayed:=1").JavaEdit("attached text:=Requested Amt:")'
LIQ_BidInitialDrawdown_EffectiveDate_TextField = 'JavaWindow("title:=.*Bid Initial Drawdown.*","displayed:=1").JavaEdit("attached text:=Effective Date:")'

### Drawdown GL Entries ###
LIQ_Drawdown_Queries_GLEntries = 'JavaWindow("title:=.* Drawdown.*").JavaMenu("label:=Queries").JavaMenu("label:=GL Entries")'
LIQ_Drawdown_GLEntries_Window = 'JavaWindow("title:=GL Entries.*")'
LIQ_Drawdown_GLEntries_Table = 'JavaWindow("title:=GL Entries.*").JavaTree("attached text:=Drill down to view details")'
LIQ_Drawdown_GLEntries_Exit_Button = 'JavaWindow("title:=GL Entries.*").JavaButton("attached text:=Exit")'

### Existing Loans Window ###
LIQ_ExistingOutstandings_Window = 'JavaWindow("title:=Existing.*")'
LIQ_ExistingOutstandings_Table = 'JavaWindow("title:=Existing.*").JavaTree("attached text:=Drill down to open the notebook")'
LIQ_ExistingOutstandings_RemainOpen_Checkbox = 'JavaWindow("title:=Existing.*").JavaCheckBox("attached text:=Remain open after.*")'

### Automatic Schedule Setup ###
LIQ_AutomaticScheduleSetup_Amount_TextField = 'JavaWindow("title:=Automatic Schedule Setup.*").JavaEdit("attached text:=Amount:")'
LIQ_AutomaticScheduleSetup_EffectiveDate_TextField = 'JavaWindow("title:=Automatic Schedule Setup.*").JavaEdit("attached text:=Effective Date:")'
LIQ_AutomaticScheduleSetup_MaturityDate_TextField = 'JavaWindow("title:=Automatic Schedule Setup.*").JavaStaticText("attached text:=Maturity Date:")'
LIQ_AutomaticScheduleSetup_InterestCycleFrequency_TextField = 'JavaWindow("title:=Automatic Schedule Setup.*").JavaStaticText("attached text:=Interest Cycle Frequency:")'
LIQ_AutomaticScheduleSetup_AllInRate_TextField = 'JavaWindow("title:=Automatic Schedule Setup.*").JavaEdit("index:=1")'
LIQ_AutomaticScheduleSetup_RateBasis_TextField = 'JavaWindow("title:=Automatic Schedule Setup.*").JavaStaticText("attached text:=Rate Basis:")'
LIQ_AutomaticScheduleSetup_FirstScheduleDate_Dropdown = 'JavaWindow("title:=Automatic Schedule Setup.*").JavaList("attached text:=First Schedule Date:")'
LIQ_AutomaticScheduleSetup_InterestTriggerDate_TextField = 'JavaWindow("title:=Automatic Schedule Setup.*").JavaStaticText("attached text:=Interest Trigger Date:")'
LIQ_AutomaticScheduleSetup_NumberOfPayments_TextField = 'JavaWindow("title:=Automatic Schedule Setup.*").JavaStaticText("attached text:=Number of Payments:")'
LIQ_AutomaticScheduleSetup_AmortizationPeriods_TextField = 'JavaWindow("title:=Automatic Schedule Setup.*").JavaEdit("attached text:=Amortization Periods:")'
LIQ_AutomaticScheduleSetup_AmortizationEndDate_TextField = 'JavaWindow("title:=Automatic Schedule Setup.*").JavaStaticText("attached text:=Amortization End Date:")'

### Automatic Schedule Setup ###
LIQ_AutomaticScheduleSetup_Window = 'JavaWindow("title:=Automatic Schedule Setup.*")'
LIQ_AutomaticScheduleSetup_Frequency_Dropdown = 'JavaWindow("title:=Automatic Schedule Setup.*").JavaList("tagname:=Combo", "labeled_containers_path:=Group:Cyclical Schedule Terms;")'
LIQ_AutomaticScheduleSetup_CyclicalAmount_Textfield = 'JavaWindow("title:=Automatic Schedule Setup.*").JavaObject("tagname:=Group", "text:=Cyclical Schedule Terms").JavaEdit("attached text:=Amount:")'
LIQ_AutomaticScheduleSetup_TriggerDate_Textfield = 'JavaWindow("title:=Automatic Schedule Setup.*").JavaEdit("attached text:=Trigger Date:")'
LIQ_AutomaticScheduleSetup_Accept_Button = 'JavaWindow("title:=Automatic Schedule Setup.*").JavaButton("attached text:=Accept")'
LIQ_AutomaticScheduleSetup_CalculatedFixedPrincipalAmount = 'JavaWindow("title:=Automatic Schedule Setup.*").JavaEdit("x:=266","y:=238")'
LIQ_AutomaticScheduleSetup_OK_Button = 'JavaWindow("title:=Automatic Schedule Setup.*").JavaButton("attached text:=OK")'
LIQ_AutomaticScheduleSetup_NumberOfPayments = 'JavaWindow("title:=Automatic Schedule Setup.*").JavaStaticText("x:=253","y:=270")'
LIQ_AutomaticScheduleSetup_Amount = 'JavaWindow("title:=Automatic Schedule Setup.*").JavaEdit("attached text:=Amount:")'

### Select Fixed Payment Amount ###
LIQ_SelectFixedPaymentAmount_Window = 'JavaWindow("title:=Select Fixed Payment Amount.*")'
LIQ_SelectFixedPaymentAmount_CalculatedFixedPayment_JavaEdit = 'JavaWindow("title:=Select Fixed Payment Amount.*").JavaEdit("to_class:=JavaEdit","x:=215","y:=25")'
LIQ_SelectFixedPaymentAmount_AcceptCalculatedFixedPayment_Checkbox = 'JavaWindow("title:=Select Fixed Payment Amount.*").JavaCheckBox("attached text:=Accept Calculated Fixed Payment")'
LIQ_Inquire_Button = 'JavaWindow("title:=.*Bid Loan.*").JavaButton("attached text:=Notebook in Inquiry Mode - F7.*")'
LIQ_SelectFixedPaymentAmount_OK_Button = 'JavaWindow("title:=Select Fixed Payment Amount.*").JavaButton("attached text:=OK")'

### Flexible Schedule ###
LIQ_FlexibleSchedule_Window = 'JavaWindow("title:=Flexible Schedule")'
LIQ_FlexibleSchedule_AddItems_Button = 'JavaWindow("title:=Flexible Schedule").JavaButton("attached text:=Add Item.*")'
LIQ_FlexibleSchedule_NonBusinessDayRule_Field = 'JavaWindow("title:=Flexible Schedule").JavaList("attached text:=Non Business Day Rule:")'
LIQ_FlexibleSchedule_JavaTree = 'JavaWindow("title:=Flexible Schedule").JavaTree("attached text:=All-In Rate:")'
LIQ_FlexibleSchedule_Type_JavaList = LIQ_FlexibleSchedule_Window + '.JavaList("attached text:=All-In Rate:")'
LIQ_FlexibleSchedule_CalculatePayments_Button = 'JavaWindow("title:=Flexible Schedule").JavaButton("attached text:=Calculate Payments")'
LIQ_FlexibleSchedule_OK_Button = 'JavaWindow("title:=Flexible Schedule").JavaButton("attached text:=OK")'
LIQ_FlexibleSchedule_RemoveItem_Button = 'JavaWindow("title:=Flexible Schedule").JavaButton("attached text:=Remove Item.*")'
LIQ_FlexibleSchedule_AllInRate_Field = 'JavaWindow("title:=Flexible Schedule").JavaEdit("attached text:=All-In Rate:")'
LIQ_FlexibleSchedule_RateBasis_Value = 'JavaWindow("title:=Flexible Schedule").JavaStaticText("labeled_containers_path:=.*Loan Interest Data.*","index:=5")'
LIQ_FlexibleSchedule_Confirmation_Yes_Button = 'JavaWindow("title:=Flexible Schedule").JavaWindow("title:=Confirmation").JavaButton("label:=Yes")'
LIQ_FlexibleSchedule_Confirmation_No_Button = 'JavaWindow("title:=Flexible Schedule").JavaWindow("title:=Confirmation").JavaButton("label:=No")'
LIQ_FlexibleSchedule_ResyncSettings_Dropdown = 'JavaWindow("title:=Flexible Schedule").JavaList("attached text:=Resync.*Settings:")'

### Flexible Schedule - Add Items Window ###
LIQ_FSched_AddItems_Window = 'JavaWindow("title:=Add Items")'
LIQ_FSched_AddItems_PayThruMaturity_CheckBox = 'JavaWindow("title:=Add Items").JavaCheckBox("attached text:=Pay Thru Maturity")'
LIQ_FSched_AddItems_AmortizeThru_Field = 'JavaWindow("title:=Add Items").JavaEdit("attached text:=Amortize Thru:")'
LIQ_FSched_AddItems_NoOFPayments_Field = 'JavaWindow("title:=Add Items").JavaEdit("attached text:=.*of Payments:")'
LIQ_FSched_AddItems_Frequency_Field = 'JavaWindow("title:=Add Items").JavaList("attached text:=Frequency:")'
LIQ_FSched_AddItems_Type_Field = 'JavaWindow("title:=Add Items").JavaList("attached text:=Type:")'
LIQ_FSched_AddItems_Date_Field = 'JavaWindow("title:=Add Items").JavaEdit("attached text:=Date:")'
LIQ_FSched_AddItems_PIAmount_Field_MaturityEnabled = 'JavaWindow("title:=Add Items").JavaEdit("index:=0")'
LIQ_FSched_AddItems_PIAmount_Field_MaturityDisabled = 'JavaWindow("title:=Add Items").JavaEdit("index:=1")'
LIQ_FSched_AddItems_PI_CheckBox = 'JavaWindow("title:=Add Items").JavaCheckBox("attached text:=P&&I Amount:")'
LIQ_FSched_AddItems_OK_Button = 'JavaWindow("title:=Add Items").JavaButton("attached text:=OK")'
LIQ_FSched_AddItems_PrincipalAmount_CheckBox = 'JavaWindow("title:=Add Items").JavaCheckBox("attached text:=Principal Amount:")'
LIQ_FSched_AddItems_PrincipaAmount_Field = 'JavaWindow("title:=Add Items").JavaEdit("x:=146","y:=184")'
LIQ_FSched_AddItems_NominalAmount_CheckBox = 'JavaWindow("title:=Add Items").JavaCheckBox("attached text:=Nominal Amt:")'
LIQ_FSched_AddItems_NominalAmount_Field = 'JavaWindow("title:=Add Items").JavaEdit("index:=4")'
LIQ_FSched_AddItems_ConsolidationType_List = 'JavaWindow("title:=Add Items").JavaList("attached text:=Consolidation Type:")'
LIQ_FSched_AddItems_BorrowRemittanceInstruction_Button = 'JavaWindow("title:=Add Items").JavaButton("attached text:=Borrower Remit\. Inst\.")'
LIQ_FSched_AddItems_PandIAmount_CheckBox = 'JavaWindow("title:=Add Items").JavaCheckBox("attached text:=P&&I Amount:")'
LIQ_FSched_AddItems_PandIAmount_NonPayThruMaturity_Field = 'JavaWindow("title:=Add Items").JavaEdit("index:=1")'
LIQ_FSched_AddItems_PandIAmount_PayThruMaturity_Field = 'JavaWindow("title:=Add Items").JavaEdit("index:=0")'
LIQ_FSched_AddItems_PandIPercentage_CheckBox = 'JavaWindow("title:=Add Items").JavaCheckBox("attached text:=Percentage:")'
LIQ_FSched_AddItems_PandIPercentage_Field = 'JavaWindow("title:=Add Items").JavaEdit("index:=3")'
LIQ_FlexSchedule_AddItems_NominalCheckbox='JavaWindow("title:=Add Items").JavaCheckBox("attached text:=Nominal Amt:")'
LIQ_FSched_AddItems_PandIAmount_Field = 'JavaWindow("title:=Add Items").JavaEdit("index:=1")'

### Flexible Schedule - Choose Remittance Instructions for [Borrower] Window ###
LIQ_FSched_ChooseRI_Window = 'JavaWindow("title:=Choose Remittance Instructions for.*")'
LIQ_FSched_ChooseRI_JavaTree = 'JavaWindow("title:=Choose Remittance Instructions for.*").JavaTree("attached text:=Drill down to view details")'
LIQ_FSched_ChooseRI_OK_Button = 'JavaWindow("title:=Choose Remittance Instructions for.*").JavaButton("attached text:=OK")'

### Outstanding WIP ###
LIQ_WIP_Outstanding_JavaTree = 'JavaWindow("title:=Transactions In Process that Satisfy the Filter").JavaTree("attached text:=Target Date:")'

### Pending Loan Drawdown ###
LIQ_PendingLoanTransactions_Window = 'JavaWindow("title:=Pending Loan Transactions.*")'
LIQ_PendingLoanTransactions_JavaTree = 'JavaWindow("title:=Pending Loan Transactions.*").JavaTree("attached text:=Drill down to view.*")'

### Initial Drawdown Notebook - Events Tab ###
LIQ_DrawdownEvents_List = 'JavaWindow("title:=.*Initial Drawdown.*").JavaTree("attached text:=Select event to view details")'
LIQ_DrawdownEvents_Comment = 'JavaWindow("title:=.*Initial Drawdown.*").JavaObject("tagname:=Group","text:=Event Details").JavaEdit("attached text:=Comment:")'

### Facility Currency F/X Rate Window ###
LIQ_FXRate_Window = 'JavaWindow("title:=.*F/X Rate.*")'
LIQ_FXRate_UseFacilityRate_Button = 'JavaWindow("title:=.*F/X Rate.*").JavaButton("label:=Use Facility.*Rate")'
LIQ_FXRate_UserSpotRate_Button ='JavaWindow("title:=.*F/X Rate.*").JavaButton("label:=Use Spot.*Rate")'
LIQ_FXRate_FacilityRate_Text = 'JavaWindow("title:=.*F/X Rate.*").JavaEdit("index:=1")'
LIQ_FXRate_SpotRate_Text = 'JavaWindow("title:=.*F/X Rate.*").JavaEdit("index:=0")'
LIQ_FXRate_Rate_Textfield = 'JavaWindow("title:=.*F/X Rate.*").JavaEdit("attached text:=.*Rate:")'
LIQ_FXRate_OK_Button = 'JavaWindow("title:=.*F/X Rate.*").JavaButton("label:=OK")'
LIQ_FXRate_Cancel_Button = 'JavaWindow("title:=.*F/X Rate.*").JavaButton("label:=Cancel")'

### Initial Drawdown Notebook - Currency Tab ###
LIQ_DrawdownCurrencyTab_Currency_StaticText = 'JavaWindow("title:=.*Initial Drawdown.*").JavaObject("tagname:=Group","text:=F/X Rate").JavaStaticText("index:=6")'
LIQ_DrawdownCurrencyTab_FacilityCurrency_StaticText = 'JavaWindow("title:=.*Initial Drawdown.*").JavaObject("tagname:=Group","text:=F/X Rate").JavaStaticText("index:=7")'
LIQ_DrawdownCurrencyTab_FXRate_StaticText = 'JavaWindow("title:=.*Initial Drawdown.*").JavaObject("tagname:=Group","text:=F/X Rate").JavaStaticText("index:=0")'
LIQ_DrawdownCurrencyTab_HistoricalFXRate_StaticText = 'JavaWindow("title:=.*Initial Drawdown.*").JavaObject("tagname:=Group","text:=F/X Rate").JavaStaticText("index:=1")'
LIQ_DrawdownCurrencyTab_Current_StaticText = 'JavaWindow("title:=.*Initial Drawdown.*").JavaObject("tagname:=Group","text:=Amounts in Facility Currency").JavaStaticText("index:=3")'
LIQ_DrawdownCurrencyTab_HostBankGross_StaticText = 'JavaWindow("title:=.*Initial Drawdown.*").JavaObject("tagname:=Group","text:=Amounts in Facility Currency").JavaStaticText("index:=4")'
LIQ_DrawdownCurrencyTab_HostBankNext_StaticText = 'JavaWindow("title:=.*Initial Drawdown.*").JavaObject("tagname:=Group","text:=Amounts in Facility Currency").JavaStaticText("index:=5")'
LIQ_DrawdownCurrencyTab_ConvertedCurrent_Textfield = 'JavaWindow("title:=.*Initial Drawdown.*").JavaObject("tagname:=Group","text:=Amounts in Euro Currency").JavaEdit("index:=1")'
LIQ_DrawdownCurrencyTab_FXRate_Button = 'JavaWindow("title:=.*Initial Drawdown.*").JavaButton("attached text:=F/X Rate")'
LIQ_FacilityCurrency_Window = 'JavaWindow("title:=Facility Currency.*","displayed:=1")'
LIQ_FacilityCurrency_FacilityAudToUsd_Button = 'JavaWindow("title:=Facility Currency.*","displayed:=1").JavaButton("attached text:=Use Facility AUD to USD Rate")'
LIQ_FacilityCurrency_Facility_Rate_Ok_Button = 'JavaWindow("title:=Facility Currency.*","displayed:=1").JavaButton("attached text:=OK")'
LIQ_FacilityCurrency_Conversion_Textfield = 'JavaWindow("title:=Facility Currency.*").JavaEdit("attached text:=${Currency_1} to ${Currency_2} Rate:")'

LIQ_Drawdown_Window = 'JavaWindow("title:=.* Drawdown .*")'
LIQ_Drawdown_Tab = 'JavaWindow("title:=.* Drawdown .*").JavaTab("tagname:=TabFolder")'
LIQ_Drawdown_WorkflowItems = 'JavaWindow("title:=.* Drawdown.*").JavaTree("attached text:=Drill down to perform Workflow item")'

### Servicing Group Selection List Window ###
LIQ_ServicingGroupSelectionList_Window = 'JavaWindow("title:=.*Servicing Group Selection List.*")'
LIQ_ServicingGroupSelectionList_Table = 'JavaWindow("title:=Servicing Group Selection List.*").JavaTree("attached text:=Drill down to access Servicing Group Details")'
LIQ_ServicingGroupSelectionList_Exit_Button = 'JavaWindow("title:=.*Servicing Group Selection List.*").JavaButton("attached text:=Exit")'

### Outstanding Servicing Group Details Window ###
LIQ_OutstandingServicingGroupDetails_Window = 'JavaWindow("title:=.*Outstanding Servicing Group Details.*")'
LIQ_OutstandingServicingGroupDetails_Add_Button = 'JavaWindow("title:=.*Outstanding Servicing Group Details.*").JavaButton("attached text:=Add")'
LIQ_OutstandingServicingGroupDetails_OK_Button = 'JavaWindow("title:=.*Outstanding Servicing Group Details.*").JavaButton("attached text:=OK")'

### MIS Codes ###
LIQ_InitialDrawdown_MISCodes_Add_Button = 'JavaWindow("title:=.*Initial Drawdown.*").JavaButton("attached text:=Add")'
LIQ_InitialDrawdown_MISCodes_JavaTree = 'JavaWindow("title:=.*Initial Drawdown.*").JavaTree("attached text:=Drill down for details")'

### MIS Code Details Window ###
LIQ_InitialDrawdown_MISCodeDetails_Window = 'JavaWindow("text:=.*Initial Drawdown MIS Code Details")'
LIQ_InitialDrawdown_MISCode_List = 'JavaWindow("title:=.*Initial Drawdown MIS Code Details").JavaList("attached text:=MIS Code:")'
LIQ_InitialDrawdown_Value_Field = 'JavaWindow("text:=.*Initial Drawdown MIS Code Details").JavaEdit("attached text:=Value:")'
LIQ_InitialDrawdown_Cancel_Button = 'JavaWindow("text:=.*Initial Drawdown MIS Code Details").JavaButton("attached text:=Cancel")'

### Discounted Loans Drawdown Notebook ###
LIQ_DiscountedLoan_LoanlDrawdown_Window = 'JavaWindow("title:=.*Discount Loan.*")'
LIQ_DiscountedLoan_LoanlDrawdown_Tab = 'JavaWindow("title:=.*Discount Loan.*","displayed:=1").JavaTab("tagname:=TabFolder")'
LIQ_DiscountedLoan_LoanlDrawdown_WorkflowAction = 'JavaWindow("title:=.*Discount Loan.*","displayed:=1").JavaTree("attached text:=Drill down to perform Workflow item")'
LIQ_IDiscountedLoan_LoanlDrawdown_Options_Cashflow = 'JavaWindow("title:=.*Discount Loan.*").JavaMenu("label:=Options").JavaMenu("label:=Cashflow")'
LIQ_DiscountedLoan_LoanlDrawdown_File_Save = 'JavaWindow("title:=.*Discount Loan.*").JavaMenu("label:=File").JavaMenu("label:=Save")'
LIQ_DiscountedLoan_LoanlDrawdown_ActualAmt_Textfield  = 'JavaWindow("title:=.*Discount Loan.*").JavaEdit("attached text:=Actual Amt:")'
LIQ_DiscountedLoan_LoanlDrawdown_RequestedAmt_Textfield  = 'JavaWindow("title:=.*Discount Loan.*").JavaEdit("attached text:=Requested:")'
LIQ_DiscountedLoan_LoanlDrawdown_EffectiveDate_Datefield  = 'JavaWindow("title:=.*Discount Loan.*").JavaEdit("attached text:=Effective Date:")'
LIQ_DiscountedLoan_LoanlDrawdown_MaturityDate_Datefield  = 'JavaWindow("title:=.*Discount Loan.*").JavaEdit("attached text:=Maturity Date:")'
LIQ_DiscountedLoan_LoanlDrawdown_BorrowerRate_Button = 'JavaWindow("title:=.*Discount Loan.*").JavaButton("attached text:=Borrower Rate:")'
LIQ_DiscountedLoan_LoanlDrawdown_BorrowerBaseRate_Textfield = 'JavaWindow("label:=Set Base Rate").JavaEdit("attached text:=Borrower Base Rate:")'
LIQ_DiscountedLoan_LoanlDrawdown_WorkflowAction = 'JavaWindow("title:=.*Discount Loan.*","displayed:=1").JavaTree("attached text:=Drill down to perform Workflow item")'
LIQ_DiscountedLoan_LoanlDrawdown_RatesTab_MatchFunding_CheckBox = 'JavaWindow("title:=.*Discount Loan.*").JavaCheckBox("class description:=check_button")'
LIQ_DiscountedLoan_LoanlDrawdown_EditHighlightedNotices_Button = 'JavaWindow("title:=.* Notice.*","displayed:=1").JavaButton("label:=Edit Highlighted Notices.*")'
LIQ_DiscountedLoan_LoanlDrawdown_NoticesCreate_Window = 'JavaWindow("title:=.*Notices created.*","displayed:=1")'
LIQ_DiscountedLoan_LoanlDrawdown_Intent_Notice_Window = 'JavaWindow("title:=.*Notice.*","displayed:=1")'
LIQ_DiscountedLoan_LoanlDrawdown_ExtOuts_RemainOpen_CheckBox = 'JavaWindow("title:=.*Discount Loan.*").JavaCheckBox("attached text:=Remain open after making selection")'

### Host Cost of Funds ###
LIQ_CostOfFunds_Window = 'JavaWindow("title:=Cost Of Funds in.*")'
LIQ_CostOfFunds_Table = 'JavaWindow("title:=Cost Of Funds in.*").JavaTree("attached text:=Drill down to set cost of funds for portfolios")'
LIQ_CostOfFunds_OK_Button = 'JavaWindow("title:=.*Cost Of Funds.*").JavaButton("attached text:=OK")'
LIQ_CostOfFunds_Cancel_Button = 'JavaWindow("title:=Cost Of Funds in.*").JavaButton("attached text:=Cancel")'
LIQ_CostOfFunds_SetAndReviewAll_Button = 'JavaWindow("title:=.*Cost Of Funds.*").JavaButton("attached text:=Set and Review All")'
LIQ_CostOfFunds_Amount = 'JavaWindow("title:=Cost Of Funds in CAD").JavaEdit("attached text:=Amount:")'
LIQ_CostofFunds_Rate = 'JavaWindow("title:=Cost Of Funds in CAD").JavaEdit("attached text:=Rate:")'
LIQ_CostofFunds_Spread = 'JavaWindow("title:=Cost Of Funds in CAD").JavaEdit("attached text:=Spread:")'
LIQ_CostofFunds_Ticket ='JavaWindow("title:=Cost Of Funds in CAD").JavaEdit("attached text:=Ticket Number:")'
LIQ_CostofFunds_Ok_Button = 'JavaWindow("title:=Cost Of Funds in CAD").JavaButton("attached text:=OK")'

### Treasury Navigation ###
LIQ_TreasuryNavigation_TreasuryReview_JavaTree = 'JavaWindow("title:=Treasury Navigation").JavaTree("attached text:=Drill down to make selection")'
LIQ_TreasuryReview_ExpandAll_JavaButton = 'JavaWindow("title:=Treasury review for the.*").JavaButton("attached text:=Expand All")'
LIQ_TreasuryReview_Exit_JavaButton = 'JavaWindow("title:=Treasury review for the.*").JavaButton("attached text:=Exit")'
LIQ_TreasuryReview_SETCOF_JavaButton = 'JavaWindow("title:=Treasury review for the.*").JavaButton("attached text:=Set COF")'
LIQ_TreasuryReview_SETCOF_ForTransaction_Window = 'JavaWindow("title:=Set COF for Transaction")'
LIQ_TreasuryReview_SETCOF_ForTransaction_OK_Button = 'JavaWindow("title:=Set COF for Transaction").JavaButton("attached text:=OK")'

### Set and Review ###
LIQ_SetAndReview_Window = 'JavaWindow("title:=Set And Review All")'
LIQ_SetAndReview_OK_Button = 'JavaWindow("title:=Set And Review All").JavaButton("attached text:=OK")'
LIQ_SetAndReview_Rate_Field = 'JavaWindow("title:=Set And Review All").JavaEdit("attached text:=Rate:")'
LIQ_SetAndReview_Cancel_Button = 'JavaWindow("title:=Set And Review All").JavaButton("attached text:=Cancel")'
LIQ_SetAndReview_UseCOFFormula_Checkbox = 'JavaWindow("title:=Set And Review All").JavaCheckBox("attached text:=Use COF Formula")'
LIQ_SetAndReview_PricingFormula_Button = 'JavaWindow("title:=Set And Review All").JavaButton("attached text:=Pricing Formula")'

### Cost Of Funds ###
LIQ_InitialDrawdown_CostOfFunds_Window = 'JavaWindow("title:=Cost Of Funds.*")'
LIQ_InitialDrawdown_CostOfFunds_OK_Button = 'JavaWindow("title:=Cost Of Funds.*").JavaButton("attached text:=OK")'
LIQ_InitialDrawdown_CostOfFunds_JavaTree = 'JavaWindow("title:=.*Cost Of Funds.*").JavaTree("attached text:=Drill down to set cost of funds for portfolios")'

### Cost Of Funds CAD ###
LIQ_InitialDrawdown_CostOfFundsCAD_Window = 'JavaWindow("title:=Cost Of Funds in CAD")'
LIQ_InitialDrawdown_CostOfFundsCAD_Rate_Field = 'JavaWindow("title:=Cost Of Funds in CAD").JavaEdit("attached text:=Rate:")'
LIQ_InitialDrawdown_CostOfFundsCAD_OK_Button = 'JavaWindow("title:=Cost Of Funds in CAD").JavaButton("attached text:=OK")'

### Set and Review ###
LIQ_SetAndReview_Window = 'JavaWindow("title:=Set And Review All")'
LIQ_SetAndReview_OK_Button = 'JavaWindow("title:=Set And Review All").JavaButton("attached text:=OK")'
LIQ_SetAndReview_Rate_Field = 'JavaWindow("title:=Set And Review All").JavaEdit("attached text:=Rate:")'
LIQ_SetAndReview_Cancel_Button = 'JavaWindow("title:=Set And Review All").JavaButton("attached text:=Cancel")'

### General - Tab ###
LIQ_InitialDrawdown_PaymentMode_List = 'JavaWindow("title:=.*Initial Drawdown.*").JavaList("attached text:=Payment Mode:")'
LIQ_InitialDrawdown_IntCycleFrequency_List = 'JavaWindow("title:=.*Initial Drawdown.*").JavaList("attached text:=Int\. Cycle Freq:")'

### Additinal Tab ###
LIQ_InitialDrawdown_LegacyID_Tree = 'JavaWindow("title:=.*Initial Drawdown.*").JavaTree("labeled_containers_path:=Tab:Additional;","tagname:=Tree")'
LIQ_InitialDrawdown_Modify_Button = 'JavaWindow("title:=.*Initial Drawdown.*").JavaButton("attached text:=Modify")'
LIQ_DiscountedLoan_LoanDrawdown_LegacyID_Tree = 'JavaWindow("title:=.*Discount Loan.*").JavaTree("labeled_containers_path:=Tab:Additional;","tagname:=Tree")'
LIQ_DiscountedLoan_LoanDrawdown_Modify_Button = 'JavaWindow("title:=.*Discount Loan.*").JavaButton("attached text:=Modify")'
LIQ_InitialDrawdown_AdditionalFields_Window = 'JavaWindow("title:=Additional Fields for.*")'
LIQ_InitialDrawdown_AdditionalFields_LegacyID = 'JavaWindow("title:=Additional Fields for.*").JavaTree("attached text:=Outstanding Legacy ID #")'
LIQ_FRO_InitialDrawdown_Window = 'JavaWindow("title:=Additional Fields for Fixed Rate Option Initial Drawdown.*")'
LIQ_FRO_InitialDrawdown_LegacyID = 'JavaWindow("title:=Additional Fields for Fixed Rate Option Initial Drawdown.*").JavaTree("attached text:=Outanding Legacy ID #")'
LIQ_FRO_InitialDrawdown_Increase_Button = 'JavaWindow("title:=Additional Fields for Fixed Rate Option Initial Drawdown.*").JavaButton("attached text:=\+")'
LIQ_FRO_InitialDradown_Ok_Button = 'JavaWindow("title:=Additional Fields for Fixed Rate Option Initial Drawdown.*").JavaButton("attached text:=OK")'

### Loan Capitilization Editor Window ###
LIQ_LoanCapitilizationEditor_Window = 'JavaWindow("title:=Loan Capitalization Editor")'
LIQ_ActivateInterestCapitilization_Checkbox = 'JavaWindow("title:=Loan Capitalization Editor").JavaCheckBox("attached text:=Activate Interest Capitalization")'
LIQ_AllowCapitilizationOver_Checkbox = 'JavaWindow("title:=Loan Capitalization Editor").JavaCheckBox("attached text:=Allow Capitalization Over Facility Limit")'
LIQ_ISTaxApplicable_Checkbox = 'JavaWindow("title:=Loan Capitalization Editor").JavaCheckBox("attached text:=IS Tax Applicable")'
LIQ_LoanCapitilizationEditor_FromDate = 'JavaWindow("title:=Loan Capitalization Editor").JavaEdit("attached text:=From Date")'
LIQ_LoanCapitilizationEditor_ToDate = 'JavaWindow("title:=Loan Capitalization Editor").JavaEdit("attached text:=To Date")'
LIQ_LoanCapitilizationEditor_Flat_RadioButton = 'JavaWindow("title:=Loan Capitalization Editor").JavaRadioButton("attached text:=Flat")'
LIQ_LoanCapitilizationEditor_PercentOfPayment_RadioButton = 'JavaWindow("title:=Loan Capitalization Editor").JavaRadioButton("attached text:=Percent of Payment")'
LIQ_LoanCapitilizationEditor_Rate_RadioButton = 'JavaWindow("title:=Loan Capitalization Editor").JavaRadioButton("attached text:=Rate")'
LIQ_LoanCapitilizationEditor_Flat_TextField = 'JavaWindow("title:=Loan Capitalization Editor").JavaEdit("index:=3")'
LIQ_LoanCapitilizationEditor_PercentOfPayment_TextField = 'JavaWindow("title:=Loan Capitalization Editor").JavaEdit("index:=4")'
LIQ_LoanCapitilizationEditor_PercentOfPayment = 'JavaWindow("title:=Loan Capitalization Editor").JavaEdit("attached text:=To Date")'
LIQ_LoanCapitilizationEditor_Rate_TextField = 'JavaWindow("title:=Loan Capitalization Editor").JavaEdit("index:=6")'
LIQ_LoanCapitilizationEditor_InitializeFrom = 'JavaWindow("title:=Loan Capitalization Editor").JavaEdit("attached text:=Capitalize From")'
LIQ_LoanCapitilizationEditor_Facility = 'JavaWindow("title:=Loan Capitalization Editor").JavaList("attached text:=To Facility")'
LIQ_LoanCapitilizationEditor_Loan = 'JavaWindow("title:=Loan Capitalization Editor").JavaList("attached text:=To Loan")'
LIQ_LoanCapitilizationEditor_PrincipalIncreaseDueToAccrualCycle_Checkbox = 'JavaWindow("title:=Loan Capitalization Editor").JavaCheckBox("attached text:=Principal Increase Due To Accrual Cycle / Event Fee Payment Is Matchfunded")'
LIQ_LoanCapitilizationEditor_CapitalizationFrequencyApplies_Checkbox = 'JavaWindow("title:=Loan Capitalization Editor").JavaCheckBox("attached text:=Capitalization Frequency Applies")'
LIQ_LoanCapitilizationEditor_Ok_Button = 'JavaWindow("title:=Loan Capitalization Editor").JavaButton("attached text:=OK")'

### Shares ###
LIQ_SharesForInitialDrawdown_Window = 'JavaWindow("title:=Shares for.*")'
LIQ_HostBankShares_JavaTree = 'JavaWindow("title:=Shares for.*").JavaTree("attached text:=Drill Down for Portfolio Shares")'
LIQ_SharesForInitialDrawdown_Comment_Button = 'JavaWindow("title:=Shares for.*").JavaButton("attached text:=Comment")'
LIQ_SharesForInitialDrawdown_Ok_Button = 'JavaWindow("title:=Shares for.*").JavaButton("attached text:=OK")'
LIQ_HostBankShare_Portolio_JavaTree = 'JavaWindow("title:=Host Bank Share for:.*").JavaTree("attached text:=Drill down to view/edit")'
LIQ_Portfolio_ExpenseCode_JavaTree = 'JavaWindow("title:=Portfolio Selection For:.*").JavaTree("attached text:=Portfolio/Expense:")'
LIQ_PortfolioShareEdit_JavaTree = 'JavaWindow("title:=Portfolio Share Edit").JavaTree("labeled_containers_path:=Group:Funding;","tagname:=Tree")'
LIQ_PortfolioShareEdit_AddMatchFunded_Button = 'JavaWindow("title:=Portfolio Share Edit").JavaButton("attached text:=Add Matchfunded")'

LIQ_InitialDrawdown_CostofFund_Window = 'JavaWindow("title:=Cost Of Funds in ${Currency}")'
LIQ_InitialDrawdown_CostofFund_OK_Button = 'JavaWindow("title:=Cost Of Funds in ${Currency}").JavaButton("attached text:=OK")'
LIQ_InitialDrawdown_CostofFund_Rate_Field = 'JavaWindow("title:=Cost Of Funds in ${Currency}").JavaEdit("attached text:=Rate:")'
LIQ_InitialDrawdown_CostofFund_Spread_Field = 'JavaWindow("title:=Cost Of Funds in ${Currency}").JavaEdit("attached text:=Spread:")'
LIQ_InitialDrawdown_CostofFund_TicketNumber_Field = 'JavaWindow("title:=Cost Of Funds in ${Currency}").JavaEdit("attached text:=Ticket Number:")'
LIQ_InitialDrawdown_CostofFund_UseCOFFormula_Checkbox = 'JavaWindow("title:=Cost Of Funds in ${Currency}").JavaCheckBox("attached text:=Use COF Formula")'

LIQ_InitialDrawdown_SetandReview_Button = 'JavaWindow("title:=Cost Of Funds.*").JavaButton("attached text:=Set and Review All")'
LIQ_InitialDrawdown_SetandReviewAll_Window = 'JavaWindow("title:=Set And Review All")'
LIQ_InitialDrawdown_SetandReview_Rate = 'JavaWindow("title:=Set And Review All").JavaEdit("attached text:=Rate:")'
LIQ_InitialDrawdown_SetandReviw_Ok_Button = 'JavaWindow("title:=Set And Review All").JavaButton("attached text:=OK")'