### Facility Interest Capitalization Window ###
LIQ_FacilityInterestCapitalization_Window = 'JavaWindow("title:=.*Interest Capitalization.*")'
LIQ_FacilityInterestCapitalization_ActivateInterestCapitalization_Checkbox = 'JavaWindow("title:=.*Interest Capitalization.*").JavaCheckBox("attached text:=Activate Interest Capitalization")'
LIQ_FacilityInterestCapitalization_FromDate_TextField = 'JavaWindow("title:=.*Interest Capitalization.*").JavaEdit("attached text:=From Date")'
LIQ_FacilityInterestCapitalization_ToDate_TextField = 'JavaWindow("title:=.*Interest Capitalization.*").JavaEdit("attached text:=To Date", "index:=0")'
LIQ_FacilityInterestCapitalization_PercentOfPayment_RadioButton = 'JavaWindow("title:=.*Interest Capitalization.*").JavaRadioButton("attached text:=Percent of Payment")'
LIQ_FacilityInterestCapitalization_PercentOfPayment_TextField = 'JavaWindow("title:=.*Interest Capitalization.*").JavaEdit("attached text:=To Date", "index:=2")'
LIQ_FacilityInterestCapitalization_OK_Button = 'JavaWindow("title:=.*Interest Capitalization.*").JavaButton("attached text:=OK")'
LIQ_FacilityInterestCapitalization_Cancel_Button = 'JavaWindow("title:=.*Interest Capitalization.*").JavaButton("attached text:=Cancel")'

### Loan Interest Capitalization Window ###
LIQ_LoanInterestCapitalization_Window = 'JavaWindow("title:=.*Loan Interest Capitalization.*")'
LIQ_LoanInterestCapitalization_ActivateInterestCapitalization_Checkbox = 'JavaWindow("title:=.*Loan Interest Capitalization.*").JavaCheckBox("attached text:=Activate Interest Capitalization")'
LIQ_LoanInterestCapitalization_FromDate_TextField = 'JavaWindow("title:=.*Loan Interest Capitalization.*").JavaEdit("attached text:=From Date")'
LIQ_LoanInterestCapitalization_ToDate_TextField = 'JavaWindow("title:=.*Loan Interest Capitalization.*").JavaEdit("attached text:=To Date", "index:=0")'
LIQ_LoanInterestCapitalization_PercentOfPayment_RadioButton = 'JavaWindow("title:=.*Loan Interest Capitalization.*").JavaRadioButton("attached text:=Percent of Payment")'
LIQ_LoanInterestCapitalization_PercentOfPayment_TextField = 'JavaWindow("title:=.*Loan Interest Capitalization.*").JavaEdit("attached text:=To Date", "index:=2")'
LIQ_LoanInterestCapitalization_OK_Button = 'JavaWindow("title:=.*Loan Interest Capitalization.*").JavaButton("attached text:=OK")'
LIQ_LoanInterestCapitalization_Cancel_Button = 'JavaWindow("title:=.*Loan Interest Capitalization.*").JavaButton("attached text:=Cancel")'
LIQ_LoanInterestCapitalization_SeparatePIKAccrual_Checkbox = 'JavaWindow("title:=.*Loan Interest Capitalization.*").JavaCheckBox("attached text:=Separate PIK Accrual")'
LIQ_LoanInterestCapitalization_ActivatePIKInterestCapitalization_Checkbox = 'JavaWindow("title:=.*Loan Interest Capitalization.*").JavaCheckBox("attached text:=Activate PIK Interest Capitalization")'
LIQ_LoanInterestCapitalization_ICPUR_Checkbox = 'JavaWindow("title:=.*Loan Interest Capitalization.*").JavaCheckBox("attached text:=ICPUR")'
LIQ_LoanInterestCapitalization_ICFUR_Checkbox = 'JavaWindow("title:=.*Loan Interest Capitalization.*").JavaCheckBox("attached text:=ICFUR")'
LIQ_LoanInterestCapitalization_ICTRF_Checkbox = 'JavaWindow("title:=.*Loan Interest Capitalization.*").JavaCheckBox("attached text:=ICTRF.*")'
LIQ_LoanInterestCapitalization_FirstPIKCapitalizationDate_TextField = 'JavaWindow("title:=.*Loan Interest Capitalization.*").JavaEdit("attached text:=First PIK Capitalization Date")'
LIQ_LoanInterestCapitalization_PIKNonBusinessDayRule_Dropdownlist = 'JavaWindow("title:=.*Loan Interest Capitalization.*").JavaList("attached text:=PIK Non-Business Day Rule")'
LIQ_LoanInterestCapitalization_AllowCapitalizationOverFacilityLimit_Checkbox = 'JavaWindow("title:=.*Loan Interest Capitalization.*").JavaCheckBox("attached text:=Allow Capitalization Over Facility Limit")'
LIQ_LoanInterestCapitalization_WithoutCommitmentIncrease_RadioButton = 'JavaWindow("title:=.*Loan Interest Capitalization.*").JavaRadioButton("attached text:=Without Commitment Increase")'
LIQ_LoanInterestCapitalization_ToFacility_Dropdownlist = 'JavaWindow("title:=.*Loan Interest Capitalization.*").JavaList("attached text:=To Facility")'
LIQ_LoanInterestCapitalization_ToLoan_Dropdownlist = 'JavaWindow("title:=.*Loan Interest Capitalization.*").JavaList("attached text:=To Loan")'
LIQ_LoanInterestCapitalization_PrincipalIncreaseDue_Checkbox = 'JavaWindow("title:=.*Loan Interest Capitalization.*").JavaCheckBox("attached text:=Principal Increase Due.*")'
LIQ_LoanInterestCapitalization_CostOfFundsRateSource_Dropdownlist = 'JavaWindow("title:=.*Loan Interest Capitalization.*").JavaList("attached text:=Cost Of Funds Rate Source")'

### PIK Rate ###
LIQ_PIKRate_Window = 'JavaWindow("title:=Set PIK Rate")'
LIQ_PIKRate_PIKRate_TextField = 'JavaWindow("title:=Set PIK Rate").JavaEdit("attached text:=PIK Rate:")'
LIQ_PIKRate_OK_Button = 'JavaWindow("title:=Set PIK Rate").JavaButton("attached text:=OK")'
LIQ_PIKRate_Cancel_Button = 'JavaWindow("title:=Set PIK Rate").JavaButton("attached text:=Cancel")'