### Repayment Paper Clip Notebook ###
LIQ_Repayment_Window = 'JavaWindow("title:=.*Repayment for.*","displayed:=1")'
LIQ_Repayment_Tab = 'JavaWindow("title:=.*Repayment for.*").JavaTab("tagname:=TabFolder")'
LIQ_Repayment_Options_Cashflow = 'JavaWindow("title:=.* Repayment.*").JavaMenu("label:=Options").JavaMenu("label:=Cashflow")'
LIQ_Repayment_Transactions_JavaTree = 'JavaWindow("title:=.*Repayment for.*").JavaTree("attached text:=Drill down to.*")'
LIQ_Repayment_Add_Button = 'JavaWindow("title:=.*Repayment for.*").JavaButton("attached text:=Add")'
LIQ_Repayment_Delete_Button = 'JavaWindow("title:=.*Repayment for.*").JavaButton("attached text:=Delete")'
LIQ_Repayment_EffectiveDate_Textfield = 'JavaWindow("title:=.*Repayment for.*").JavaEdit("attached text:=${LIQ_Currency}", "labeled_containers_path:=Tab:General;")'
LIQ_Repayment_Options_ChangeEffectiveDate = 'JavaWindow("title:=.*Repayment for.*").JavaMenu("label:=Options").JavaMenu("label:=Change Effective Date")'
LIQ_Repayment_EnterNewEffectiveDate_Textfield = 'JavaWindow("title:=Enter New Effective Date").JavaEdit("tagname:=Text")'
LIQ_Repayment_EnterNewEffectiveDate_OK_Button = 'JavaWindow("title:=Enter New Effective Date").JavaButton("attached text:=OK")'
LIQ_Repayment_WorkflowItems = 'JavaWindow("title:=.*Repayment for.*").JavaTree("attached text:=.*Workflow .*")'
LIQ_Repayment_AwaitingApproval_Status_Window = 'JavaWindow("title:=Awaiting Approval Repayment.*")'
LIQ_Repayment_Released_Status_Window = 'JavaWindow("title:=Released Repayment .*")'
LIQ_Repayment_Save_Menu = 'JavaWindow("title:=.*Repayment for.*").JavaMenu("label:=File").JavaMenu("label:=Save")'
LIQ_Repayment_ChangeEffectiveDate_Menu = 'JavaWindow("title:=.*Repayment for.*").JavaMenu("label:=Options").JavaMenu("label:=Change Effective Date")'
LIQ_Repayment_TransactionDescription_Textfield = 'JavaWindow("title:=.*Repayment for.*").JavaEdit("labeled_containers_path:=Tab:General;Group:Transaction Description:;")'
LIQ_Repayment_Amount = 'JavaWindow("title:=.*Repayment for.*").JavaEdit("attached text:=Amount:")'
LIQ_Repayment_File_Save = 'JavaWindow("title:=.*Repayment for.*").JavaMenu("label:=File").JavaMenu("label:=Save")'
LIQ_Repayment_GLEntries_Menu = 'JavaWindow("title:=Released Repayment.*").JavaMenu("label:=Queries").JavaMenu("label:=GL Entries")'

LIQ_PendingRepayment_EffectiveDate_Textfield = 'JavaWindow("title:=Enter New Effective Date").JavaEdit("tagname:=Text")'
LIQ_PendingRepayment_EffectiveDate_Ok_Button = 'JavaWindow("title:=Enter New Effective Date").JavaButton("attached text:=OK")'
LIQ_FeesandOutstandings_Upper_JavaTree = 'JavaWindow("title:=Fees and Outstandings").JavaTree("attached text:=Select a Fee or Outstanding and then add new transactions")'
LIQ_FeesandOutstandings_NewTransactions_JavaTree = 'JavaWindow("title:=Fees and Outstandings").JavaTree("labeled_containers_path:=Group:New Transactions;")'
LIQ_FeesandOutstandings_FreeFormEventFee_RadioButton = 'JavaWindow("title:=Fees and Outstandings").JavaRadioButton("attached text:=Freeform Event Fee")'
LIQ_FeesandOutstandings_Add_Button = 'JavaWindow("title:=Fees and Outstandings").JavaButton("attached text:=Add")'

LIQ_Fee_Window = 'JavaWindow("title:=.* Fee .*")'
LIQ_Fee_RequestedAmount_Textfield = 'JavaWindow("title:=.* Fee .*").JavaEdit("attached text:=Requested Amount:")'
LIQ_Fee_FeeType_DropdownList = 'JavaWindow("title:=.* Fee .*").JavaList("attached text:=Fee Type:")'
LIQ_Fee_File_Save = 'JavaWindow("title:=.* Fee .*").JavaMenu("label:=File").JavaMenu("label:=Save")' 
LIQ_Fee_ArrangerFee_Window = 'JavaWindow("title:=.* Arranger Fee.*")'

### ACTION_NOTICES ###
LIQ_Notice_PaperClipIntentNotice_Window = 'JavaWindow("title:=Paper Clip Intent Notice Group.*")'
LIQ_Notice_PaperClipIntentNotice_Exit_Button = 'JavaWindow("title:=Paper Clip Intent Notice Group.*").JavaButton("attached text:=Exit")' 
LIQ_Notice_PaperClipIntentNotice_Information_Table = 'JavaWindow("title:=Paper Clip Intent Notice Group.*").JavaTree("attached text:=Drill down to mark notices")'
LIQ_Notice_PaperClipIntentNotice_Send_Button = 'JavaWindow("title:=Paper Clip Intent Notice Group.*").JavaButton("attached text:=Send")'
LIQ_Notice_PaperClipIntentNotice_EditHighlightedNotice_Button = 'JavaWindow("title:=Paper Clip Intent Notice Group.*").JavaButton("attached text:=Edit Highlighted Notices")'
LIQ_Notice_PaperClipIntentNotice_Edit_Window = 'JavaWindow("title:=Paper Clip Intent Notice created.*")'
LIQ_Notice_PaperClipIntentNotice_Edit_Email = 'JavaWindow("title:=Paper Clip Intent Notice created.*").JavaEdit("attached text:=E-mail:")'