### Event Fee Notebook - General Tab ###
LIQ_EventFee_Window = 'JavaWindow("title:=.*Fee.*","index:=1")'
LIQ_EventFee_Javatab= 'JavaWindow("title:=.*Fee.*","index:=1").JavaTab("tagname:=TabFolder")'
LIQ_EventFee_RequestedAmount_Textfield = 'JavaWindow("title:=.*Fee.*","index:=1").JavaEdit("attached text:=Requested Amount:")'
LIQ_EventFee_General_EffectiveDate = 'JavaWindow("title:=.*Fee.*","index:=1").JavaEdit("labeled_containers_path:=Tab:General;","attached text:=Effective Date:")'
LIQ_EventFee_FeeType_Combobox = 'JavaWindow("title:=.*Fee.*","index:=1").JavaList("attached text:=Fee Type:")'
LIQ_EventFee_RecurringFee_Checkbox = 'JavaWindow("title:=.*Fee.*","index:=1").JavaCheckBox("attached text:=Recurring Fee")'
LIQ_EventFee_NoRecurrencesAfter_Datefield = 'JavaWindow("title:=.*Fee.*","index:=1").JavaEdit("x:=935","y:=190")'
LIQ_EventFee_BillingDays_Textfield = 'JavaWindow("title:=.*Fee.*","index:=1").JavaEdit("attached text:=Billing days:")'
LIQ_EventFee_Comment_Textfield = 'JavaWindow("title:=.*Fee.*","index:=1").JavaEdit("labeled_containers_path:=Tab:General;Group:Comment;")'
LIQ_EventFee_File_Save = 'JavaWindow("title:=.*Fee.*","index:=1").JavaMenu("label:=File").JavaMenu("label:=Save")'
LIQ_EventFee_File_Exit = 'JavaWindow("title:=.*Fee.*","index:=1").JavaMenu("label:=File").JavaMenu("label:=Exit")'
LIQ_EventFee_Options_Payment = 'JavaWindow("title:=.*Fee.*","index:=1").JavaMenu("label:=Options").JavaMenu("label:=Payment")'
LIQ_EventFee_Window_Updated='JavaWindow("title:=.* Fee.*")'
LIQ_EventFee_WindowTab_Updated= 'JavaWindow("title:=.*Fee.*","index:=1").JavaTab("toolkit class:=.*TabFolder")'
LIQ_EventFee_IncomeRecognitionRule_Combobox = 'JavaWindow("title:=.*Fee.*","index:=1").JavaList("x:=779","y:=127")'
LIQ_EventFee_Queries_GLEntries = 'JavaWindow("title:=.*Fee.*","index:=1").JavaMenu("label:=Queries").JavaMenu("label:=GL Entries")'
LIQ_EventFee_Queries_Cashflow = 'JavaWindow("title:=.*Fee.*","index:=1").JavaMenu("label:=Options").JavaMenu("label:=Cashflow")'
LIQ_EventFee_InquiryMode_Button = 'JavaWindow("title:=.*Fee.*","index:=1").JavaButton("attached text:=Notebook in Inquiry Mode - F7")'
LIQ_EventFee_Options_LenderShares = 'JavaWindow("title:=.*Fee.*","index:=1").JavaMenu("label:=Options").JavaMenu("label:=View / Update Lender Shares")'
LIQ_EventFee_FromBorrowerThirdParty_RadioButton = 'JavaWindow("title:=.*Fee.*","index:=1").JavaRadioButton("attached text:=From Borrower/Third Party")'
LIQ_EventFee_FeeType_Combobox_Updated = 'JavaWindow("title:=.*${Fee_Type} Fee.*","index:=1").JavaList("attached text:=Fee Type:")'
LIQ_EventFee_Currency_Combobox_Updated = 'JavaWindow("title:=.*${Fee_Type} Fee.*","index:=1").JavaList("text:=${Currency}")'
LIQ_EventFee_RequestedAmount_Textfield_Updated = 'JavaWindow("title:=.*${Fee_Type} Fee.*","index:=1").JavaEdit("attached text:=Requested Amount:")'
LIQ_EventFee_WindowTab_Updated2 = 'JavaWindow("title:=.*${Fee_Type} Fee.*","index:=1").JavaTab("tagname:=TabFolder")'


### Event Fee Notebook - General Tab - Billing Rules Section ###
LIQ_EventFee_BillBorrower_Checkbox = 'JavaWindow("title:=.*Fee.*","index:=1").JavaCheckBox("attached text:=Bill Borrower")'
LIQ_EventFee_BillCareOfContact_Checkbox = 'JavaWindow("title:=.*Fee.*","index:=1").JavaCheckBox("attached text:=Bill Care-Of Contact")'
LIQ_EventFee_DoNotPrint_Checkbox = 'JavaWindow("title:=.*Fee.*","index:=1").JavaCheckBox("attached text:=Do not Print")'
LIQ_EventFee_DoNotMail_Checkbox = 'JavaWindow("title:=.*Fee.*","index:=1").JavaCheckBox("attached text:=Do not Mail")'
LIQ_EventFee_IncludeInXMLBill_Checkbox = 'JavaWindow("title:=.*Fee.*","index:=1").JavaCheckBox("attached text:=Include In XML Bill")'

### Event Fee Notebook - Frequency Tab ###
LIQ_EventFee_Frequency_EffectiveDate = 'JavaWindow("title:=.*Fee.*","index:=1").JavaEdit("labeled_containers_path:=Tab:Frequency;","attached text:=Effective Date:")'
LIQ_EventFee_Frequency_Combobox = 'JavaWindow("title:=.*Fee.*","index:=1").JavaList("labeled_containers_path:=Tab:Frequency;","attached text:=Frequency:")'
LIQ_EventFee_NonBussDayRule_Combobox = 'JavaWindow("title:=.*Fee.*","index:=1").JavaList("labeled_containers_path:=Tab:Frequency;","attached text:=Non-Business Day Rule:")'
LIQ_EventFee_ActualNextOccurence_Datefield = 'JavaWindow("title:=.*Fee.*","index:=1").JavaEdit("attached text:=Actual Next Occurrence Date:")'
LIQ_EventFee_AdjustedNextOccurence_Datefield = 'JavaWindow("title:=.*Fee.*","index:=1").JavaEdit("attached text:=Adjusted Next Occurrence Date:")'
LIQ_EventFee_EndDate_Field = 'JavaWindow("title:=.*Fee.*","index:=1").JavaEdit("attached text:=End Date:")'
LIQ_EventFee_Rule_Combobox = 'JavaWindow("title:=.*Fee.*","index:=1").JavaList("labeled_containers_path:=Tab:Frequency;","attached text:=Rule:")'

### Event Fee Notebook - Workflow Tab ###
LIQ_EventFee_Workflow_Tree = 'JavaWindow("title:=.*Fee.*","index:=1").JavaTree("labeled_containers_path:=Tab:Workflow;","attached text:=.*Workflow item")'
LIQ_EventFeeNotebook_Window = 'JavaWindow("title:=.*Fee.*","displayed:=1")'
LIQ_EventFeeNotebook_RequestedAmount_Textfield = 'JavaWindow("title:=.*Fee.*").JavaEdit("attached text:=Requested Amount:")'
LIQ_EventFeeNotebook_EffectiveDate_Datefield = 'JavaWindow("title:=.*Fee.*").JavaEdit("attached text:=Effective Date:")'
LIQ_EventFeeNotebook_FeeType_Combobox = 'JavaWindow("title:=.*Fee.*").JavaList("attached text:=Fee Type:")'
LIQ_EventFeeNotebook_RecurringFee_Checkbox = 'JavaWindow("title:=.*Fee.*").JavaCheckBox("attached text:=Recurring Fee")'
LIQ_EventFeeNotebook_NoRecurrencesAfter_Datefield = 'JavaWindow("title:=.*Fee.*").JavaEdit("attached text:=No Recurrences After Date:")'
LIQ_EventFeeNotebook_BillingDays_Textfield = 'JavaWindow("title:=.*Fee.*").JavaObject("tagname:=Group","attached text:=Billing days:")'
LIQ_EventFeeNotebook_Comment_Textfield = 'JavaWindow("title:=.*Fee.*").JavaEdit("labeled_containers_path:=Tab:General;Group:Comment;")'
LIQ_EventFeeNotebook_FileExit_Menu = 'JavaWindow("title:=.* Fee / Released.*","displayed:=1").JavaMenu("label:=File").JavaMenu("label:=Exit")'
LIQ_PendingEventFeeNotebook_FileExit_Menu = 'JavaWindow("title:=.* Fee / Released.*","displayed:=1").JavaMenu("label:=File").JavaMenu("label:=Exit")'

### Pending Fee ###
LIQ_EventFeeNotebook_PendingTab_Window = 'JavaWindow("title:=.*Fee.*.*Pending.*","displayed:=1").JavaTab("tagname:=TabFolder")'
LIQ_EventFee_AwaitingSend_Tab= 'JavaWindow("title:=.* Fee / Awaiting Send To Approval.*","displayed:=1").JavaTab("tagname:=TabFolder")'
LIQ_EventFee_AwaitingApproval_Tab= 'JavaWindow("title:=.* Fee / Awaiting Approval.*","displayed:=1").JavaTab("tagname:=TabFolder")'
LIQ_EventFee_AwaitingRelease_Tab= 'JavaWindow("title:=.* Fee / Awaiting Release.*","displayed:=1").JavaTab("tagname:=TabFolder")'
LIQ_EventFee_Released_Tab= 'JavaWindow("title:=.* Fee / Released.*","displayed:=1").JavaTab("tagname:=TabFolder")'
LIQ_PendingEventFee_AwaitingSend_Tab= 'JavaWindow("title:=.* Awaiting Send To Approval.*","displayed:=1").JavaTab("tagname:=TabFolder")'
LIQ_PendingEventFee_AwaitingApproval_Tab= 'JavaWindow("title:=.* Awaiting Approval.*","displayed:=1").JavaTab("tagname:=TabFolder")'
LIQ_PendingEventFee_AwaitingRelease_Tab= 'JavaWindow("title:=.* Awaiting Release.*","displayed:=1").JavaTab("tagname:=TabFolder")'
LIQ_PendingEventFee_Released_Tab= 'JavaWindow("title:=.* Released.*","displayed:=1").JavaTab("tagname:=TabFolder")'
LIQ_EventFee_Pending_Window = 'JavaWindow("title:=.*Fee.*.*Pending.*","displayed:=1")'
LIQ_EventFee_AwaitingSend_Window = 'JavaWindow("title:=.* Fee / Awaiting Send To Approval.*","displayed:=1")'
LIQ_EventFee_AwaitingApproval_Window = 'JavaWindow("title:=.* Fee / Awaiting Approval.*","displayed:=1")'
LIQ_EventFee_AwaitingRelease_Window = 'JavaWindow("title:=.* Fee / Awaiting Release.*","displayed:=1")'
LIQ_EventFee_Released_Window = 'JavaWindow("title:=.* Fee / Released.*","displayed:=1")'
LIQ_PendingEventFee_AwaitingSend_Window = 'JavaWindow("title:=.* Awaiting Send To Approval.*","displayed:=1")'
LIQ_PendingEventFee_AwaitingApproval_Window = 'JavaWindow("title:=.* Fee / Awaiting Approval.*","displayed:=1")'
LIQ_PendingEventFee_AwaitingRelease_Window = 'JavaWindow("title:=.* Fee / Awaiting Release.*","displayed:=1")'
LIQ_PendingEventFee_Released_Window = 'JavaWindow("title:=.* Fee / Released.*","displayed:=1")'

### Events Tab ###
LIQ_EventFee_Events_Tree = 'JavaWindow("title:=.* Fee / Released.*","displayed:=1").JavaTree("attached text:=Select event to view details")'
LIQ_EventFee_Events_JavaTree = 'JavaWindow("title:=.* Fee .*").JavaTree("attached text:=Select event to view details")'
LIQ_PendingEventFee_Events_Tree = 'JavaWindow("title:=.* Fee / Released.*","displayed:=1").JavaTree("attached text:=Select event to view details")'
LIQ_EventFee_Events_Comment_TextField = 'JavaWindow("title:=.*Fee.*","index:=1").JavaEdit("attached text:=Comment:")'
LIQ_EventFee_Events_JavaTree_Updated = 'JavaWindow("title:=.*Fee.*","index:=1").JavaTree("attached text:=Select event to view details","labeled_containers_path:=Tab:Events;")'

### Event Fee - Workflow List ###
LIQ_EventFee_WorkflowItems_Pending_List = 'JavaWindow("title:=.*Fee.*").JavaTree("attached text:=Drill down to perform Workflow item")'
LIQ_EventFee_WorkflowItems_AwaitingSend_List = 'JavaWindow("title:=.* Fee / Awaiting Send To Approval.*","displayed:=1").JavaTree("attached text:=Drill down to perform Workflow item")'
LIQ_EventFee_WorkflowItems_AwaitingApproval_List = 'JavaWindow("title:=.* Fee / Awaiting Approval.*","displayed:=1").JavaTree("attached text:=Drill down to perform Workflow item")'
LIQ_EventFee_WorkflowItems_AwaitingRelease_List = 'JavaWindow("title:=.* Fee / Awaiting Release.*","displayed:=1").JavaTree("attached text:=Drill down to perform Workflow item")'
LIQ_PendingEventFee_WorkflowItems_AwaitingSend_List = 'JavaWindow("title:=.* Awaiting Send To Approval.*","displayed:=1").JavaTree("attached text:=Drill down to perform Workflow item")'

### Pending Event Fee - Workflow List ###
LIQ_PendingEventFee_WorkflowItems_Pending_List = 'JavaWindow("title:=.*Fee .*").JavaTree("attached text:=Drill down to perform Workflow item")'
LIQ_PendingEventFee_WorkflowItems_AwaitingApproval_List = 'JavaWindow("title:=.* Fee / Awaiting Approval.*","displayed:=1").JavaTree("attached text:=Drill down to perform Workflow item")'
LIQ_PendingEventFee_WorkflowItems_AwaitingRelease_List = 'JavaWindow("title:=.* Fee / Awaiting Release.*","displayed:=1").JavaTree("attached text:=Drill down to perform Workflow item")'

### Cashflow for Event Fee ###
LIQ_EventFee_Cashflow_Window = 'JavaWindow("title:=Cashflows For .*")'
LIQ_EventFee_Cashflow_Ok_Button = 'JavaWindow("title:=Cashflows For .*").JavaButton("attached text:=OK")'
LIQ_EventFee_Cashflows_List = 'JavaWindow("title:=Cashflows For Legal Fee Fee").JavaTree("attached text:=Drill down to view/change details")'
LIQ_EventFee_Cashflows_DoIt_Button = 'JavaWindow("title:=Cashflows For Legal Fee Fee").JavaButton("label:=Set Selected Item To .*")'
LIQ_EventFee_Cashflow_HostBankCash_JavaEdit = 'JavaWindow("title:=Cashflows .* Legal Fee Fee.*").JavaStaticText("to_class:=JavaStaticText","index:=28")'
LIQ_Reimbursement_Cashflow_Ok_Button = 'JavaWindow("title:=Cashflows For Reimbursement For.*").JavaButton("attached text:=OK")'
LIQ_EventFee_Cashflow_Cancel_Button = 'JavaWindow("title:=Cashflows For .*").JavaButton("attached text:=Cancel")'
LIQ_EventFeePayment_Window = 'JavaWindow("title:=Event Fee Payment.*","index:=1")'

### Event Fees ###
LIQ_EventFees_Window = 'JavaWindow("title:=Event Fees For.*","displayed:=1")'
LIQ_EventFees_Amount_TextField = 'JavaWindow("title:=Event Fees For.*","displayed:=1").JavaObject("text:=Assignment Recordation Fee").JavaEdit("attached text:=Amount:")'
LIQ_EventFees_FlowDownFeeFromDeal_Button = 'JavaWindow("title:=Event Fees For.*","displayed:=1").JavaButton("attached text:=Flow Down Fee From Deal")'
LIQ_EventFees_PaidByBuyer_TextField = 'JavaWindow("title:=Event Fees For.*","displayed:=1").JavaEdit("attached text:=Paid By Buyer:")'
LIQ_EventFees_PaidBySeller_TextField = 'JavaWindow("title:=Event Fees For.*","displayed:=1").JavaEdit("attached text:=Paid By Seller:")'
LIQ_EventFees_Waived_TextField = 'JavaWindow("title:=Event Fees For.*","displayed:=1").JavaEdit("attached text:=Waived:")'
LIQ_EventFees_OK_Button = 'JavaWindow("title:=Event Fees For.*","displayed:=1").JavaButton("attached text:=OK")'

### Event Fee Payment Group Window ###
LIQ_EventFeePaymentGroup_Window = 'JavaWindow("title:=Event Fee Payment Group.*")'
LIQ_EventFeePaymentGroup_MarkAll_Button = 'JavaWindow("title:=Event Fee Payment Group.*").JavaButton("attached text:=Mark all")'
LIQ_EventFeePaymentGroup_Send_Button = 'JavaWindow("title:=Event Fee Payment Group.*").JavaButton("attached text:=Send")'
LIQ_EventFeePaymentGroup_Exit_Button = 'JavaWindow("title:=Event Fee Payment Group.*").JavaButton("attached text:=Exit")'
LIQ_EventFeePaymentGroup_EditHighlightNotices = 'JavaWindow("title:=.* Payment Group created by .*","displayed:=1").JavaButton("attached text:=Edit Highlighted Notices")'
LIQ_EventFeePaymentCreated_Window = 'JavaWindow("title:=.* Payment created by .*","displayed:=1")'
LIQ_EventFeePaymentCreated_Text_Textarea = 'JavaWindow("title:=.* Payment created by .*","displayed:=1").JavaEdit("index:=1")'
LIQ_EventFeePaymentCreatedBy_File_Exit = 'JavaWindow("title:=.* Payment created by .*","displayed:=1").JavaMenu("label:=File").JavaMenu("label:=Exit")'

### Event Fee Details ###
LIQ_EventFeeDetailsTemplate_DistributeToAll_Checkbox = 'JavaWindow("title:=.*Fee Details.*").JavaCheckBox("label:=Distribute to all lenders")'    
LIQ_EventFeeDetailsTemplate_Fomula_Radiobutton = 'JavaWindow("title:=.*Fee Details.*").JavaRadioButton("label:=Formula")'    
LIQ_EventFeeDetailsTemplate_FormulaAmount_Textfield = 'JavaWindow("title:=.*Fee Details.*").JavaEdit("attached text:=Global Current x")'
LIQ_EventFeeDetailsTemplate_GlobalCurrent_Textfield = 'JavaWindow("title:=.*Fee Details.*").JavaEdit("attached text:=Global Current x")'
LIQ_EventFeeDetailsTemplate_Textfield = 'JavaWindow("title:=.*Fee Details.*").JavaEdit("tagname:=Text","index:=0")'
LIQ_EventFeeDetailsTemplate_CCY_List = 'JavaWindow("title:=.*Fee Details.*").JavaList("attached text:=CCY:")'
LIQ_EventFeeDetailsTemplate_OK_Button = 'JavaWindow("title:=.*Fee Details.*").JavaButton("label:=OK")'
LIQ_EventFeeDetailsTemplate_PrepaidLoan_RadioButton = 'JavaWindow("title:=.*Fee Details.*").JavaRadioButton("attached text:=Prepaid Loan Amount")'
LIQ_EventFeeDetailsTemplate_OriginalLoan_RadioButton = 'JavaWindow("title:=.*Fee Details.*").JavaRadioButton("attached text:=Original Loan Amount")'
LIQ_EventFeeDetailsTemplate_CurrentLoan_RadioButton = 'JavaWindow("title:=.*Fee Details.*").JavaRadioButton("attached text:=Current Loan Amount")'
LIQ_EventFeeDetailsTemplate_EventFeeType = 'JavaWindow("title:=.*Fee Details.*").JavaRadioButton("attached text:=Flat Amount")'
LIQ_EventFeeDetailsTemplate_OriginalLoan_Percent = 'JavaWindow("title:=.*Fee Details.*").JavaEdit("attached text:=Original Loan Amount x")'
LIQ_EventFeeDetailsTemplate_CurrentLoan_Percent = 'JavaWindow("title:=.*Fee Details.*").JavaEdit("attached text:=Current Loan Amount x")'
LIQ_EventFeeDetailsTemplate_PrepaidLoanPercent = 'JavaWindow("title:=.*Fee Details.*").JavaEdit("attached text:=Prepaid Loan Amount x")'
LIQ_EventFeeDetailsTemplate_PrepaidPercentage = 'JavaWindow("title:=.*Fee Details.*").JavaEdit("attached text:=Prepaid x")'

### Event Fee List ###
LIQ_EventFeeList_Window = 'JavaWindow("title:=Fee List.*")'
LIQ_EventFeeList_Tree = 'JavaWindow("title:=Fee List.*").JavaTree("attached text:=Drill down to view details")'
LIQ_EventFeeList_Released_Window = 'JavaWindow("title:=Available.*Released.*").JavaTab("tagname:=TabFolder")'
LIQ_EventFeeList_Event_JavaTree = 'JavaWindow("title:=Available.*Released.*").JavaTree("attached text:=Select event to view details")'