### Cashflows ###
LIQ_Cashflows_Window = 'JavaWindow("title:=Cashflows For.*","displayed:=1")'
LIQ_Cashflows_Tree = 'JavaWindow("title:=Cashflows For.*","displayed:=1").JavaTree("attached text:=Drill down to view/change details")'
LIQ_Cashflows_SetSelectedItemTo_Button = 'JavaWindow("title:=Cashflows For.*","displayed:=1").JavaButton("label:=Set Selected Item To.*")'
LIQ_Cashflows_SetSelectedItemToDoIt_Button = 'JavaWindow("title:=Cashflows For.*","displayed:=1").JavaButton("attached text:=Set Selected Item .*Do It.*")'
LIQ_Cashflows_OK_Button = 'JavaWindow("title:=Cashflows For.*","displayed:=1").JavaButton("label:=OK")'
LIQ_Cashflows_Cancel_Button = 'JavaWindow("title:=Cashflows For.*","displayed:=1").JavaButton("attached text:=Cancel")'
LIQ_Cashflows_Queries_GLEntries = 'JavaWindow("title:=Cashflows For.*","displayed:=1").JavaMenu("label:=Queries").JavaMenu("label:=GL Entries")'
LIQ_Cashflows_Options_SendAllToSPAP = 'JavaWindow("title:=Cashflows For.*","displayed:=1").JavaMenu("label:=Options").JavaMenu("label:=Send All To SPAP")'
LIQ_Cashflows_Options_SetAllToDoIt = 'JavaWindow("title:=Cashflows For.*","displayed:=1").JavaMenu("label:=Options").JavaMenu("label:=Set All To .*Do It.*")'
LIQ_Cashflows_Options_PrefundingApproval = 'JavaWindow("title:=Cashflows For.*","displayed:=1").JavaMenu("label:=Options").JavaMenu("label:=Prefunding Cashflow Approval Transaction")'
LIQ_Cashflows_HostBankCashNet_Text = 'JavaWindow("title:=Cashflows .*").JavaStaticText("to_class:=JavaStaticText","x:=245","y:=58")'
LIQ_Cashflows_CashToBorrower_Text = 'JavaWindow("title:=Cashflows .*").JavaStaticText("to_class:=JavaStaticText","x:=245","y:=4")'
LIQ_Cashflows_MarkSelectedItemForRelease_Button = 'JavaWindow("title:=Cashflows.*","displayed:=1").JavaButton("attached text:=Mark Selected Item For Release")'
LIQ_Cashflow_Options_MarkAllRelease = 'JavaWindow("title:=Cashflows .*").JavaMenu("label:=Options").JavaMenu("label:=Mark All To Release")'
LIQ_Cashflows_DetailsForCashflow_Window = 'JavaWindow("title:=Details for Cashflow.*")'
LIQ_Cashflows_DetailsForCashflow_SelectRI_Button = 'JavaWindow("title:=Details for Cashflow.*").JavaButton("label:=Select Remittance Instructions")'
LIQ_Cashflows_DetailsForCashflow_ViewRI_Button = 'JavaWindow("title:=Details for Cashflow.*").JavaButton("label:=View Remittance Instructions")'
LIQ_Cashflows_DetailsForCashflow_OK_Button = 'JavaWindow("title:=Details for Cashflow.*").JavaButton("label:=OK")'
LIQ_Cashflows_DetailsForCashflow_Cancel_Button = 'JavaWindow("title:=Details for Cashflow.*").JavaButton("label:=Cancel")'
LIQ_Cashflows_DetailsForCashflow_PaymentMethod_StaticText = 'JavaWindow("title:=Details for Cashflow.*").JavaObject("tagname:=Group","text:=Remittance Instruction Detail").JavaStaticText("index:=1")'
LIQ_Cashflows_DetailsforCashflow_IMTDetail_Button = 'JavaWindow("title:=Details for Cashflow.*").JavaButton("attached text:=IMT Detail")'
LIQ_Cashflows_DetailsforCashflow_Exit_Button = 'JavaWindow("title:=Details for Cashflow.*").JavaButton("attached text:=Exit")'
LIQ_Cashflows_DetailsForCashflow_SettlementCCYFXRate_Button='JavaWindow("title:=Details for Cashflow.*").JavaButton("text:=&Settlement CCY/FX Rate:")'
LIQ_Cashflows_MatchMoneyTransfers_Button = 'JavaWindow("title:=Cashflows For.*").JavaButton("attached text:=Match Money Transfers")'
LIQ_Cashflows_MatchWIPItems_Button = 'JavaWindow("title:=Cashflows For.*").JavaButton("attached text:=Match WIP Items")'

 ### Cashflows - Choose Remittance Instructions ###
LIQ_Cashflows_ChooseRemittanceInstructions_Window = 'JavaWindow("title:=Choose Remittance Instructions")'
LIQ_Cashflows_ChooseRemittanceInstructions_Tree = 'JavaWindow("title:=Choose Remittance Instructions").JavaTree("attached text:=Drill down to view details")'
LIQ_Cashflows_ChooseRemittanceInstructions_OK_Button = 'JavaWindow("title:=Choose Remittance Instructions").JavaButton("label:=OK")'
LIQ_Cashflows_ChooseRemittanceInstructions_Cancel_Button = 'JavaWindow("title:=Choose Remittance Instructions").JavaButton("label:=Cancel")'
LIQ_Cashflows_ChooseRemittanceInstructions_CustomInstructions_Checkbox = 'JavaWindow("title:=Choose Remittance Instructions").JavaCheckBox("text:=&Custom Instructions")'
LIQ_Cashflows_ChooseRemittanceInstructions_Details_Button = 'JavaWindow("title:=Choose Remittance Instructions").JavaButton("text:=&Details")'
LIQ_Cashflows_RemittanceInstructionsDetail_Window = 'JavaWindow("title:=Remittance Instructions Detail.*")'
LIQ_Cashflows_RemittanceInstructionsDetail_Description_TextField = 'JavaWindow("title:=Remittance Instructions Detail.*").JavaEdit("attached text:=Description:")'
LIQ_Cashflows_RemittanceInstructionsDetail_OK_Button = 'JavaWindow("title:=Remittance Instructions Detail.*").JavaButton("attached text:=OK")'
LIQ_Cashflows_UpdateInformation_CopyRID_Button = 'JavaWindow("title:=Update Information.*").JavaButton("attached text:=Copy RID To Clipboard")'
LIQ_Cashflows_UpdateInformation_Exit_Button =  'JavaWindow("title:=Update Information.*").JavaButton("attached text:=Exit")'

### Reimbursement ###
LIQ_Reimbursement_Pending_Window = 'JavaWindow("title:=Reimbursement For.*","displayed:=1")' 
LIQ_ReleasedFeeCashflows_Queries_GLEntries = 'JavaWindow("title:=.* Fee / Released.*","displayed:=1").JavaMenu("label:=Queries").JavaMenu("label:=GL Entries")'
LIQ_Reimbursement_GL_Entries_Window = 'JavaWindow("title:=Reimbursement For.*","displayed:=1")'   
LIQ_Reimbursement_Queries_GLEntries = 'JavaWindow("title:=Reimbursement For.*","displayed:=1").JavaMenu("label:=Queries").JavaMenu("label:=GL Entries")'
LIQ_Reimbursement_Pending_Tab= 'JavaWindow("title:=Reimbursement For.*","displayed:=1").JavaTab("tagname:=TabFolder")'
LIQ_Reimbursement_WorkflowItems_AwaitingSend_List = 'JavaWindow("title:=Reimbursement For.*","displayed:=1").JavaTree("attached text:=Drill down to perform Workflow item")'
LIQ_Reimbursement_General_EffectiveDate = 'JavaWindow("title:=Reimbursement For.*","index:=1").JavaEdit("labeled_containers_path:=Tab:General;","attached text:=Effective Date:")'
LIQ_Reimbursement_Comment_Textfield = 'JavaWindow("title:=Reimbursement For.*","index:=1").JavaEdit("labeled_containers_path:=Tab:General;Group:Comment;")'
LIQ_Reimbursement_File_Save = 'JavaWindow("title:=Reimbursement For.*","index:=1").JavaMenu("label:=File").JavaMenu("label:=Save")'
LIQ_ReimbursementExpenseFee_Window = 'JavaWindow("title:=.* Expense Fee / Released.*","displayed:=1")'
LIQ_ReimbursementExpenseFee_Tab = 'JavaWindow("title:=.* Expense Fee / Released.*","displayed:=1").JavaTab("tagname:=TabFolder")'
LIQ_ReimbursementFee_Events_Tree = 'JavaWindow("title:=.* Expense Fee / Released.*","displayed:=1").JavaTree("attached text:=Select event to view details")'
LIQ_Reimbursement_File_Preview = 'JavaWindow("title:=Event Fee Payment.*","index:=1").JavaMenu("label:=File").JavaMenu("label:=Preview")'
LIQ_Reimbursement_EventFeePay_File_Exit = 'JavaWindow("title:=Event Fee Payment.*","index:=1").JavaMenu("label:=File").JavaMenu("label:=Exit")'
LIQ_Reimbursement_File_Preview_Exit = 'JavaWindow("title:=Notice Preview.*","displayed:=1").JavaMenu("label:=File").JavaMenu("label:=Exit")'
LIQ_Reimbursement_ExpenseFee_Select = 'JavaWindow("title:=.* Expense Fee / Released.*","index:=1").JavaMenu("label:=Options").JavaMenu("label:=Reimbursement of Expense Fee")'
LIQ_PendingReimbursement_AwaitingApproval_Window = 'JavaWindow("title:=Reimbursement For.*","displayed:=1")'
LIQ_PendingReimbursement_AwaitingRelease_Window = 'JavaWindow("title:=Reimbursement For.*","displayed:=1")'
LIQ_PendingReimbursement_WorkflowItems_AwaitingApproval_List = 'JavaWindow("title:=Reimbursement For.*","displayed:=1").JavaTree("attached text:=Drill down to perform Workflow item")'
LIQ_PendingReimbursement_WorkflowItems_AwaitingRelease_List = 'JavaWindow("title:=Reimbursement For.**","displayed:=1").JavaTree("attached text:=Drill down to perform Workflow item")'
LIQ_PendingReimbursement_AwaitingApproval_Tab= 'JavaWindow("title:=Reimbursement For.*","displayed:=1").JavaTab("tagname:=TabFolder")'
LIQ_PendingReimbursement_AwaitingRelease_Tab= 'JavaWindow("title:=Reimbursement For.*","displayed:=1").JavaTab("tagname:=TabFolder")'
LIQ_PendingReimbursement_Released_Tab= 'JavaWindow("title:=Reimbursement For.*","displayed:=1").JavaTab("tagname:=TabFolder")'
LIQ_PendingReimbursement_WorkflowItems_AwaitingApproval_List = 'JavaWindow("title:=Reimbursement For.*","displayed:=1").JavaTree("attached text:=Drill down to perform Workflow item")'
LIQ_PendingReimbursement_Events_Tree = 'JavaWindow("title:=Reimbursement For.*","displayed:=1").JavaTree("attached text:=Select event to view details")'

### Change Performing Status ###
LIQ_ChangePerformingStatus_Window = 'JavaWindow("title:=Change Performing Status.*")'
LIQ_ChangePerformingStatus_PerformingStatus_Dropdown = 'JavaWindow("label:=Change Performing Status.*").JavaList("attached text:=Performing Status:")'
LIQ_ChangePerformingStatus_EffectiveDate_Textfield = 'JavaWindow("title:=Change Performing Status.*").JavaEdit("attached text:=Effective Date:")'
LIQ_ChangePerformingStatus_Comment_Textfield = 'JavaWindow("title:=Change Performing Status.*").JavaEdit("attached text:=Comment:")'
LIQ_ChangePerformingStatus_GLEntries_Button = 'JavaWindow("title:=Change Performing Status.*").JavaButton("label:=GL Entries.*")'    
LIQ_ChangePerformingStatus_OK_Button = 'JavaWindow("title:=Change Performing Status.*").JavaButton("attached text:=OK")'
LIQ_ChangePerformingStatus_ChoosePayment_Interest_RadioButton = 'JavaWindow("title:=Choose a Payment.*").JavaRadioButton("label:=Interest Payment")'
LIQ_ChangePerformingStatus_ChoosePayment_OK_Button = 'JavaWindow("title:=Choose a Payment.*").JavaButton("attached text:=OK")'

### Create Split Cashflow ###
LIQ_Cashflow_Options_SplitCashflows = 'JavaWindow("title:=Cashflows .*").JavaMenu("label:=Options").JavaMenu("label:=Split Cashflows")'
LIQ_Cashflow_Options_SetAllDOIT = 'JavaWindow("title:=Cashflows .*").JavaMenu("label:=Options").JavaMenu("label:=Set All To .*Do It.*")'
LIQ_SplitCashflows_Window = 'JavaWindow("title:=Cashflows Eligible For Splitting")'
LIQ_SplitCashflows_Add_Button = 'JavaWindow("title:=Cashflows Eligible For Splitting").JavaButton("attached text:=Add")'
LIQ_SplitCashflows_Exit_Button = 'JavaWindow("title:=Cashflows Eligible For Splitting").JavaButton("attached text:=Exit")'
LIQ_SplitCashflows_JavaTree= 'JavaWindow("title:=Cashflows Eligible For Splitting").JavaTree("labeled_containers_path:=Group:Cashflows Split From Selected Cashflow;")'
LIQ_SplitCashflows_Delete_Button = 'JavaWindow("title:=Cashflows Eligible For Splitting").JavaButton("attached text:=Delete")'

### Split Cashflow Detail ###
LIQ_SplitCashflowsDetail_Window = 'JavaWindow("title:=Split Cashflow Detail")'
LIQ_SplitCashflowsDetail_RemittanceInstruction_Button = 'JavaWindow("title:=Split Cashflow Detail").JavaButton("attached text:=Remittance Instructions:")'
LIQ_SplitCashflowsDetail_SplitPrincipal_Field = 'JavaWindow("title:=Split Cashflow Detail").JavaEdit("attached text:=Split Principal:")'
LIQ_SplitCashflowsDetail_TransactionAmount_Static = 'JavaWindow("title:=Split Cashflow Detail").JavaStaticText("labeled_containers_path:=.*Amount Available To Split.*","index:=1")'
LIQ_SplitCashflowsDetail_OK_Button = 'JavaWindow("title:=Split Cashflow Detail").JavaButton("attached text:=OK")'

### Select Remittance Instruction ###
LIQ_SelectRemittanceInstruction_Window = 'JavaWindow("title:=Select a Remittance Instruction")'
LIQ_SelectRemittanceInstruction_JavaTree = 'JavaWindow("title:=Select a Remittance Instruction").JavaTree("attached text:=Drill down to select item")'
LIQ_SelectRemittanceInstruction_OK_Button = 'JavaWindow("title:=Select a Remittance Instruction").JavaButton("attached text:=OK")'

###CashFlows Fixed rate Option###
LIQ_Cashflows_InitialDrawdown_DetailsForCashflow_Window = 'JavaWindow("title:=Details for Cashflow.*")'
LIQ_Cashflows_InitialDrawdown_DetailsForCashflow_SelectRI_Button = 'JavaWindow("title:=Cashflow.*").JavaButton("label:=Select Remittance Instructions")'
LIQ_Cashflows_InitialDrawdown_DetailsForCashflow_ViewRI_Button = 'JavaWindow("title:=Cashflow.*").JavaButton("label:=View Remittance Instructions")'
LIQ_Cashflows_InitialDrawdown_DetailsForCashflow_OK_Button = 'JavaWindow("title:=Cashflow.*").JavaButton("label:=OK")'
LIQ_Cashflows_InitialDrawdown_DetailsForCashflow_Cancel_Button = 'JavaWindow("title:=Cashflow.*").JavaButton("label:=Cancel")'
LIQ_Cashflows_InitialDrawdown_DetailsForCashflow_PaymentMethod_StaticText = 'JavaWindow("title:=Cashflow.*").JavaObject("tagname:=Group","text:=Remittance Instruction Detail").JavaStaticText("index:=1")'
LIQ_Cashflows_InitialDrawdown_DetailsforCashflow_IMTDetail_Button = 'JavaWindow(""title:=Cashflow.*").JavaButton("attached text:=IMT Detail")'
LIQ_Cashflows_InitialDrawdown_DetailsforCashflow_Exit_Button = 'JavaWindow("title:=Cashflow.*").JavaButton("attached text:=Exit")'

### Prefunding Cashflow ###
LIQ_Prefunding_Cashflows_Window = 'JavaWindow("title:=Prefunding Cashflow.*")'
LIQ_Prefunding_Cashflows_Tab = 'JavaWindow("title:=Prefunding Cashflow.*").JavaTab("tagname:=TabFolder")'
LIQ_Prefunding_Cashflows_JavaTree = 'JavaWindow("title:=Prefunding Cashflow.*").JavaTree("attached text:=Drill down to perform Workflow item")'
LIQ_Prefunding_Cashflows_InquiryMode_Button = 'JavaWindow("title:=Prefunding Cashflow.*").JavaButton("attached text:=Notebook in Inquiry Mode - F7")'
LIQ_Prefunding_Cashflows_Status_Approve_Menu = 'JavaWindow("title:=Prefunding Cashflow.*").JavaMenu("label:=Status").JavaMenu("label:=Approve")'
LIQ_Prefunding_Cashflows_File_Exit_Menu = 'JavaWindow("title:=Prefunding Cashflow.*").JavaMenu("label:=File").JavaMenu("label:=Exit")'

### Settlement CCY/FX Rate Window ###
LIQ_SettlementCCYFXRate_Cashflows_Window ='JavaWindow("title:=Set Settlement Currency/FX Rate")'
LIQ_SettlementCCYFXRate_Cashflows_JavaTree ='JavaWindow("title:=Set Settlement Currency/FX Rate").JavaTree("tagname:=Settlement Currency:")'
LIQ_SettlementCCYFXRate_Cashflows_SettlementCurrency_List ='JavaWindow("title:=Set Settlement Currency/FX Rate").JavaList("tagname:=Settlement Currency:")'
LIQ_SettlementCCYFXRate_Cashflows_OK_Button ='JavaWindow("title:=Set Settlement Currency/FX Rate").JavaButton("text:=&OK")'
LIQ_SettlementCCYFXRate_Cashflows_DefaultRate_Button ='JavaWindow("title:=Set Settlement Currency/FX Rate").JavaButton("text:=&Default to Spot Rate")'
LIQ_IncomingMoneyTransfers_Window = 'JavaWindow("title:=Cashflows For.*").JavaWindow("title:=List of Incoming Money Transfers.*","displayed:=1")'
LIQ_IncomingMoneyTransfers_Filter_Button = 'JavaWindow("title:=Cashflows For.*").JavaWindow("title:=List of Incoming Money Transfers.*","displayed:=1").JavaButton("attached text:=Filter...")'
LIQ_IncomingMoneyTransfers_JavaTree = 'JavaWindow("title:=Cashflows For.*").JavaWindow("title:=List of Incoming Money Transfers.*","displayed:=1").JavaTree("text:=")'
LIQ_IncomingMoneyTransfers_Match_Button = 'JavaWindow("title:=Cashflows For.*").JavaWindow("title:=List of Incoming Money Transfers.*","displayed:=1").JavaButton("attached text:=Match...")'
LIQ_IncomingMoneyTransfers_Exit_Button = 'JavaWindow("title:=Cashflows For.*").JavaWindow("title:=List of Incoming Money Transfers.*","displayed:=1").JavaButton("attached text:=Exit")'
LIQ_CashItemMatchingEditor_Window = 'JavaWindow("title:=Cash Item Matching Editor")'
LIQ_CashItemMatchingEditor_OK_Button = 'JavaWindow("title:=Cash Item Matching Editor").JavaButton("attached text:=OK")'
LIQ_IncomingMoneyTransfers_Filter_Window = 'JavaWindow("title:=Incoming Money Transfer Filter")'
LIQ_IncomingMoneyTransfers_Filter_LeftToMatch_TextField = 'JavaWindow("title:=Incoming Money Transfer Filter").JavaEdit("index:=0")'
LIQ_IncomingMoneyTransfers_Filter_PaymentDetailsLike_TextField = 'JavaWindow("title:=Incoming Money Transfer Filter").JavaEdit("attached text:=Payment Details like:")'
LIQ_IncomingMoneyTransfers_Filter_Branch_TextField = 'JavaWindow("title:=Incoming Money Transfer Filter").JavaList("attached text:=Branch.*")'
LIQ_IncomingMoneyTransfers_Filter_OK_Button = 'JavaWindow("title:=Incoming Money Transfer Filter").JavaButton("attached text:=OK")'
LIQ_ListOfPublicWIPItems_Window = 'JavaWindow("title:=Cashflows For.*","displayed:=1").JavaWindow("title:=List of public WIP Items")'
LIQ_ListOfPublicWIPItems_Match_Button = 'JavaWindow("title:=Cashflows For.*","displayed:=1").JavaWindow("title:=List of public WIP Items").JavaButton("attached text:=.*Match.*")'
LIQ_ListOfPublicWIPItems_Filter_Button = 'JavaWindow("title:=Cashflows For.*","displayed:=1").JavaWindow("title:=List of public WIP Items").JavaButton("attached text:=.*Filter.*")'
LIQ_ListOfPublicWIPItems_Exit_Button = 'JavaWindow("title:=Cashflows For.*","displayed:=1").JavaWindow("title:=List of public WIP Items").JavaButton("attached text:=.*Exit.*")'
LIQ_ListOfPublicWIPItems_JavaTree = 'JavaWindow("title:=Cashflows For.*","displayed:=1").JavaWindow("title:=List of public WIP Items").JavaTree("text:=")'
LIQ_WIPItemFilter_Window = 'JavaWindow("title:=WIP Item Filter")'
LIQ_WIPItemFilter_Branch_TextField = 'JavaWindow("title:=WIP Item Filter").JavaList("attached text:=.*Branch.*")'
LIQ_WIPItemFilter_WIPDescriptionLike_TextField = 'JavaWindow("title:=WIP Item Filter").JavaEdit("attached text:=WIP description like:")'
LIQ_WIPItemFilter_OK_Button = 'JavaWindow("title:=WIP Item Filter").JavaButton("attached text:=OK")'