### Commitment Fee - Ongoing Fee Payment ###  
LIQ_OngoingFeePayment_Window = 'JavaWindow("title:=.*Ongoing Fee Payment.*")'
LIQ_OngoingFeePayment_Tab = 'JavaWindow("title:=.*Ongoing Fee Payment.*").JavaTab("index:=0")'
LIQ_OngoingFeePayment_Requested_Textfield ='JavaWindow("title:=.*Ongoing Fee Payment.*").JavaObject("tagname:=Group","text:=.*Amounts.*").JavaEdit("editable:=1")'
LIQ_OngoingFeePayment_EffectiveDate_Textfield = 'JavaWindow("title:=.*Ongoing Fee Payment.*").JavaEdit("attached text:=Effective Date:")'
LIQ_OngoingFeePayment_DueDate_Text = 'JavaWindow("title:=.*Ongoing Fee Payment.*").JavaObject("tagname:=Group","text:=Cycle").JavaStaticText("index:=5")'
LIQ_OngoingFeePayment_Workflow = 'JavaWindow("title:=.*Ongoing Fee Payment.*").JavaTree("attached text:=Drill down to perform Workflow item")'
LIQ_OngoingFeePayment_UpdateMode_Button = 'JavaWindow("title:=.* Payment .*").JavaButton("attached text:=Notebook in Update Mode - F7")'
LIQ_OngoingFeePayment_InquiryMode_Button = 'JavaWindow("title:=.* Payment .*").JavaButton("attached text:=Notebook in Inquiry Mode - F7")'
LIQ_OngoingFeePayment_ViewUpdateLenderShares_Menu = 'JavaWindow("title:=.* Payment .*").JavaMenu("label:=Options").JavaMenu("label:=View/Update Lender Shares")'
LIQ_OngoingFeePayment_AwaitingReleaseWindow = 'JavaWindow("title:=.*Ongoing Fee Payment.*.*Awaiting Release.*","displayed:=1")'
LIQ_OngoingFeePayment_WorkflowItems = 'JavaWindow("title:=.*Ongoing Fee Payment.*").JavaTree("attached text:=Drill down to perform Workflow item")'

### Commitment Fee - Ongoing Fee Payment - Cashflow ### 
LIQ_PaymentNotebook_Tab = 'JavaWindow("title:=.*Payment.*").JavaTab("tagname:=TabFolder")' 
LIQ_PaymentNotebook_Workflow_Tree = 'JavaWindow("title:=.*Payment.*").JavaTree("attached text:=Drill down to perform Workflow item")' 
LIQ_PaymentNotebook_CashFlow_Window = 'JavaWindow("title:=Cashflows For.*Payment.*")' 
LIQ_PaymentNotebook_CashFlow_DrillDowntoView_CashflowList = 'JavaWindow("title:=Cashflows For.*Payment.*").JavaTree("attached text:=Drill down to view/change details")'
LIQ_PaymentNotebook_Cashflow_OK_Button = 'JavaWindow("title:=Cashflows For.*Payment.*").JavaButton("attached text:=OK")'
LIQ_PaymentNotebook_Cashflow_SettoDoIt_Button = 'JavaWindow("title:=Cashflows For.*Payment.*.*").JavaButton("attached text:=Set Selected Item To.*Do It.*")'
LIQ_PaymentNotebook_Cashflow_RemittanceDesc_DDA_StaticText = 'JavaWindow("title:=Cashflows For.*Payment.*").JavaStaticText("attached text:=.*DDA.*")'
LIQ_PaymentNotebook_Cashflow_RemittanceDesc_IMT_StaticText = 'JavaWindow("title:=Cashflows For.*Payment.*").JavaStaticText("attached text:=.*IMT.*")'
LIQ_PaymentNotebook_Cashflow_RemittanceDesc_None_StaticText = 'JavaWindow("title:=Cashflows For.*Payment.*").JavaStaticText("attached text:=None")'
LIQ_PaymentNotebook_ChooseRemittance_Window = 'JavaWindow("title:=Choose Remittance Instructions")'
LIQ_PaymentNotebook_ChooseRemittance_List = 'JavaWindow("title:=Choose Remittance Instructions").JavaTree("attached text:=Drill down to view details")'
LIQ_PaymentNotebook_ChooseRemittance_OK_Button = 'JavaWindow("title:=Choose Remittance Instructions").JavaButton("attached text:=OK")'
LIQ_PaymentNotebook_Cashflow_SettoDoIt_Undo_Button = 'JavaWindow("title:=Cashflows For.*Payment.*").JavaButton("label:=.*Undo It.*")' 
LIQ_OngoingFee_InquiryMode_Button = 'JavaWindow("title:=.*Fee /.*").JavaButton("attached text:=Notebook in Inquiry Mode - F7")'
LIQ_OngoingFee_Window = 'JavaWindow("title:=.*Fee /.*")'
LIQ_OngoingFee_Tab = 'JavaWindow("title:=.*Fee /.*").JavaTab("tagname:=TabFolder")' 
LIQ_OngoingFee_Accrual_JavaTree = 'JavaWindow("title:=.*Fee /.*").JavaTree("labeled_containers_path:=Tab:Accrual;","attached text:=Cycles:")'
LIQ_OngoingFee_CycleShareOverview_Button = 'JavaWindow("title:=.*Fee /.*").JavaButton("attached text:=Cycle Shares Adjustment")'

### Commitment Fee - Ongoing Fee Payment - Workflow ###  
LIQ_OngoingFeePaymentNotebook_Workflow_JavaTree = 'JavaWindow("title:=.*Ongoing Fee Payment.*","displayed:=1").JavaTree("tagname:=Drill down to perform.*")' 
LIQ_OngoingFeePaymentNotebook_Window = 'JavaWindow("title:=.*Ongoing Fee Payment.*")'