LIQ_Portfolio_Positions = 'JavaWindow("title:=Deal Notebook.*").JavaMenu("label:=Options").JavaMenu("label:=Portfolio Positions...")'
LIQ_Portfolio_Positions_Window = 'JavaWindow("title:=Porfolio Positions.*")'
LIQ_Portfolio_Positions_JavaTree = 'JavaWindow("title:=Portfolio Positions.*").JavaTree("tagname:=Drill down or use the.*")'
LIQ_Portfolio_Positions_Adjustment_Button = 'JavaWindow("title:=Portfolio Positions.*").JavaButton("attached text:=Adjustment.*")'
LIQ_Make_Selections_Window = 'JavaWindow("title:=Make Selection.*")'
LIQ_Make_Selections_Portfolio_Transfer_RadioButton = 'JavaWindow("title:=Make Selection.*").JavaRadioButton("attached text:=Portfolio Transfer.*")'
LIQ_Make_Selections_OK_Button = 'JavaWindow("title:=Make Selection.*").JavaButton("attached text:=OK.*")'
LIQ_Portfolio_Transfer_Released_Window = 'JavaWindow("title:=Portfolio Transfer.* Released.*")'
LIQ_Portfolio_Transfer_Window = 'JavaWindow("title:=Portfolio Transfer.*")'
LIQ_Portfolio_Transfer_Effective_Date = 'JavaWindow("title:=Portfolio Transfer.*").JavaEdit("attached text:=Effective Date:.*")'
LIQ_Portfolio_Transfer_To_Portfolio_Button = 'JavaWindow("title:=Portfolio Transfer.*").JavaButton("attached text:=Portfolio\.\.\.", "labeled_containers_path:=Tab:General;Group:To;.*")'
LIQ_Portfolio_Selections_For_Window = 'JavaWindow("title:=Portfolio Selection For.*")'
LIQ_Portfolio_Selections_For_PortfolioExpense = 'JavaWindow("title:=Portfolio Selection For.*").JavaTree("attached text:=Portfolio/Expense.*")'
LIQ_Portfolio_Selections_OK_Button = 'JavaWindow("title:=Portfolio Selection For.*").JavaButton("attached text:=OK.*")'
LIQ_Portfolio_Transfer_ExpiryDate_Textfield = 'JavaWindow("title:=Portfolio Transfer.*").JavaEdit("attached text:=Expiry Date:.*")'
LIQ_Portfolio_Transfer_Amount = 'JavaWindow("title:=Portfolio Transfer.*").JavaEdit("attached text:=Amount:.*")'
LIQ_Portfolio_Transfer_Price = 'JavaWindow("title:=Portfolio Transfer.*").JavaEdit("attached text:=Transfer Price.*")'
LIQ_Portfolio_Transfer_Save_Button = 'JavaWindow("title:=Portfolio Transfer.*").JavaMenu("label:=File").JavaMenu("label:=Save")'
LIQ_Portfolio_Transfer_Tab_Button = 'JavaWindow("title:=Portfolio Transfer.*").JavaTab("Tagname:=TabFolder")'
LIQ_Portfolio_Transfer_Workflow_Java_Tree = 'JavaWindow("title:=Portfolio Transfer.*").JavaTree("attached text:=Drill down to perform Workflow item.*")'
LIQ_Portfolio_Positions_Exit_Button = 'JavaWindow("title:=Porfolio Positions.*").JavaButton("attached text:=Exit.*")'
LIQ_Make_Selections_SettledDiscountChage_RadioButton = 'JavaWindow("title:=Make Selection.*").JavaRadioButton("attached text:=Portfolio Settled Discount Change.*")'
LIQ_Make_Selections_TradeDateDiscountChange_RadioButton = 'JavaWindow("title:=Make Selection.*").JavaRadioButton("attached text:=Portfolio Trade Date Discount Change.*")'
LIQ_Make_Selections_AssignableChange_RadioButton = 'JavaWindow("title:=Make Selection.*").JavaRadioButton("attached text:=Portfolio Assignable Change.*")'
LIQ_Make_Selections_DefferedPLChange_RadioButton = 'JavaWindow("title:=Make Selection.*").JavaRadioButton("attached text:=Portfolio Deferred P/L Change.*")'
LIQ_Make_Selections_DefferedPLIndicatorChange_RadioButton = 'JavaWindow("title:=Make Selection.*").JavaRadioButton("attached text:=Portfolio Deferred P/L Indicator Change.*")'
LIQ_Make_Selections_TransactionCostAdjustment_RadioButton = 'JavaWindow("title:=Make Selection.*").JavaRadioButton("attached text:=Portfolio Transaction Cost Adjustment.*")'
LIQ_Portfolio_Transfer_TransferPrice_Textfield = 'JavaWindow("title:=Portfolio Transfer.*").JavaEdit("attached text:=Transfer Price:")'
LIQ_PortfolioPositions_ByBranchPortfolioExpenseFac_RadioButton = 'JavaWindow("title:=Portfolio Positions.*").JavaRadioButton("attached text:=By branch/portfolio/expense/facility")'
LIQ_PortfolioPositions_ByFacBranchPortfolioExpense_RadioButton = 'JavaWindow("title:=Portfolio Positions.*").JavaRadioButton("attached text:=By facility/branch/portfolio/expense")'
LIQ_PortfolioPositions_ExcludeDormantPositions_RadioButton = 'JavaWindow("title:=Portfolio Positions.*").JavaRadioButton("attached text:=Exclude dormant positions")'
LIQ_PortfolioPositions_IncludeDormantPositions_RadioButton = 'JavaWindow("title:=Portfolio Positions.*").JavaRadioButton("attached text:=Include dormant positions")'
LIQ_MakeSelections_Choices_RadioButton = 'JavaWindow("title:=Make Selection.*").JavaRadioButton("attached text:=${MakeSelection_Choice}")'
LIQ_Portfolio_Transfer_AssignableAmount_Textfield = 'JavaWindow("title:=Portfolio Transfer.*").JavaEdit("attached text:=Assignable:")'
LIQ_Portfolio_Transfer_FundableAmount_Textfield = 'JavaWindow("title:=Portfolio Transfer.*").JavaEdit("attached text:=Fundable Amount:")'
LIQ_Portfolio_Transfer_Comment_Textfield = 'JavaWindow("title:=Portfolio Transfer.*").JavaEdit("attached text:=Comment:")'
LIQ_Portfolio_Transfer_NetAll_Textfield = 'JavaWindow("title:=Portfolio Transfer.*").JavaEdit("attached text:=Net All:")'
LIQ_PortfolioAllocationsFor_Window = 'JavaWindow("title:=Portfolio allocations for.*")'
LIQ_PortfolioAllocationsFor_DiscountSettled_Text = 'JavaWindow("title:=Portfolio Allocations for.*").JavaEdit("index:=6")'
LIQ_PortfolioAllocationsFor_Exit_Button = 'JavaWindow("title:=Portfolio Allocations for.*").JavaButton("attached text:=Exit")'
LIQ_PortfolioAllocationsFor_DiscountTrade_Text = 'JavaWindow("title:=Portfolio Allocations for.*").JavaEdit("index:=5")'

###Portfolio Settled Discount Change###
LIQ_PortfolioSettledDiscountChange_Window = 'JavaWindow("title:=.*Discount Change.*")'
LIQ_PortfolioSettledDiscountChange_EffectiveDate = 'JavaWindow("title:=.*Discount Change.*").JavaEdit("attached text:=Effective Date:")'
LIQ_PortfolioSettledDiscountChange_CurrentAmount = 'JavaWindow("title:=.*Discount Change.*").JavaEdit("attached text:=Current:")'
LIQ_PortfolioSettledDiscountChange_AdjustmentAmount = 'JavaWindow("title:=.*Discount Change.*").JavaEdit("attached text:=\+/- Adjustment:")'
LIQ_PortfolioSettledDiscountChange_NewAmount = 'JavaWindow("title:=.*Discount Change.*").JavaEdit("attached text:=New:")'
LIQ_PortfolioSettledDiscountChange_GLOffset_Button = 'JavaWindow("title:=.*Discount Change.*").JavaButton("attached text:=GL Offset\.\.\.")'
LIQ_PortfolioSettledDiscountChange_Queries_GLEntries = 'JavaWindow("title:=.*Discount Change.*","displayed:=1").JavaMenu("label:=Options").JavaMenu("label:=GL Entries")'
LIQ_PortfolioSettledDiscountChange_Comment_Textfield = 'JavaWindow("title:=.*Discount Change.*").JavaEdit("attached text:=Comment:")'
LIQ_PortfolioSettledDiscountChange_Save_Button = 'JavaWindow("title:=.*Discount Change.*").JavaMenu("label:=File").JavaMenu("label:=Save")'

###GL Offset Details Window###
LIQ_GLOffsetDetails_ExistingWIP_RadioButton = 'JavaWindow("title:=.*GL Offset Details").JavaRadioButton("attached text:=Existing WIP")'
LIQ_GLOffsetDetails_InterestIncome_RadioButton = 'JavaWindow("title:=.*GL Offset Details").JavaRadioButton("attached text:=Interest Income")'
LIQ_GLOffsetDetails_GLShortName_Dropdown = 'JavaWindow("title:=.*GL Offset Details").JavaList("attached text:=G/L Short Name:")'
LIQ_GLOffsetDetails_WIP_Button = 'JavaWindow("title:=.*GL Offset Details").JavaButton("attached text:=WIP:")'
LIQ_GLOffsetDetails_Ok_Button = 'JavaWindow("title:=.*GL Offset Details").JavaButton("attached text:=OK")'
LIQ_GLOffsetDetails_Type_RadioButton = 'JavaWindow("title:=.*GL Offset Details").JavaRadioButton("attached text:=${GLOffset_Type}")'
LIQ_GLOffsetDetails_Window = 'JavaWindow("title:=.*GL Offset Details")'
LIQ_GLOffsetDetails_Expense_Button = 'JavaWindow("title:=.*GL Offset Details").JavaButton("attached text:=Expense:")'
LIQ_GLOffsetDetails_Portfolio_Button = 'JavaWindow("title:=.*GL Offset Details").JavaButton("attached text:=Portfolio:")'
LIQ_FeesHeldAwaitingDispose_Window = 'JavaWindow("title:=Fees Held Awaiting Dispos\..*")'
LIQ_FeesHeldAwaitingDispose_List = 'JavaWindow("title:=Fees Held Awaiting Dispos\..*").JavaTree("attached text:=Drill down to view a WIP Item")'
LIQ_FeesHeldAwaitingDispose_Use_Button = 'JavaWindow("title:=Fees Held Awaiting Dispos\..*").JavaButton("attached text:=Use")'

### Approval ###
LIQ_PortfolioSettledDiscountChange_Tab = 'JavaWindow("title:=.*Discount Change.*").JavaTab("Tagname:=TabFolder")'
LIQ_PortfolioSettledDiscountChange_WorkflowItems = 'JavaWindow("title:=Portfolio Settled Discount Change.*").JavaTree("attached text:=Drill down to perform Workflow item.*")'

### Portfolio Trade Date Discount Change Details ###
LIQ_PortfolioTradeDateDiscountChange_Window = 'JavaWindow("title:=Portfolio Trade Date Discount Change.*")'
LIQ_PortfolioTradeDateDiscountChange_EffectiveDate = 'JavaWindow("title:=Portfolio Trade Date Discount Change.*").JavaEdit("attached text:=Effective Date:")'
LIQ_PortfolioTradeDateDiscountChange_CurrentAmount = 'JavaWindow("title:=Portfolio Trade Date Discount Change.*").JavaEdit("attached text:=Current:")'
LIQ_PortfolioTradeDateDiscountChange_AdjustmentAmount = 'JavaWindow("title:=Portfolio Trade Date Discount Change.*").JavaEdit("attached text:=\+/- Adjustment:")'
LIQ_PortfolioTradeDateDiscountChange_NewAmount = 'JavaWindow("title:=Portfolio Trade Date Discount Change.*").JavaEdit("attached text:=New:")'

### Portfolio Trade Date Discount Change Details Wokflow items ###
LIQ_PortfolioTradeDateDiscountChange_Tab = 'JavaWindow("title:=Portfolio Trade Date Discount Change.*").JavaTab("Tagname:=TabFolder")'
LIQ_PortfolioTradeDateDiscountChange_WorkflowItems = 'JavaWindow("title:=Portfolio Trade Date Discount Change.*").JavaTree("attached text:=Drill down to perform Workflow item")'
LIQ_PortfolioTradeDateDiscountChange_Event_JavaTree = 'JavaWindow("title:=Portfolio Trade Date Discount Change.*").JavaTree("tagname:=Tree")'

### Mark Portfolio ###
LIQ_MarkPortfolio_Window = 'JavaWindow("text:=Mark Portfolio Selections")'
LIQ_MarkPortfolio_JavaList = 'JavaWindow("text:=Mark Portfolio Selections").JavaList("attached text:=Drill down for selected function")'
LIQ_MarkPortfolio_Exit_Button = 'JavaWindow("text:=Mark Portfolio Selections").JavaButton("attached text:=Exit")'

### Available Positions For Risk/Trader Mark ###    
LIQ_MarkPortfolio_AvailablePositionsFor_Window = 'JavaWindow("title:=Available Portfolio Positions For.*")'
LIQ_MarkPortfolio_AvailablePositionsFor_Portfolio_Window = 'JavaWindow("title:=Available Portfolio Positions For.*").JavaWindow("title:=.*${Portfolio_Description}.*")'
LIQ_MarkPortfolio_AvailablePositionsFor_Portfolio_TodaysRiskMark_Button = 'JavaWindow("title:=Available Portfolio Positions For.*").JavaWindow("title:=.*${Portfolio_Description}.*").JavaEdit("index:=0")'
LIQ_MarkPortfolio_AvailablePositionsFor_Portfolio_UsePriorMark_Button = 'JavaWindow("title:=Available Portfolio Positions For.*").JavaWindow("title:=.*${Portfolio_Description}.*").JavaButton("title:=Use Prior Mark")'
LIQ_MarkPortfolio_AvailablePositionsFor_Portfolio_OK_Button = 'JavaWindow("title:=Available Portfolio Positions For.*").JavaWindow("title:=.*${Portfolio_Description}.*").JavaButton("title:=OK")'
LIQ_MarkPortfolio_AvailablePositionsFor_Portfolio_Cancel_Button = 'JavaWindow("title:=Available Portfolio Positions For.*").JavaWindow("title:=.*${Portfolio_Description}.*").JavaButton("title:=Cancel")'

### Select One or More Portfolios ###
LIQ_MarkPortfolio_SelectPortfoliosToMark_Window = 'JavaWindow("title:=.*Portfolios to Mark.*")'
LIQ_MarkPortfolio_SelectPortfoliosToMark_JavaTree = 'JavaWindow("title:=.*Portfolios to Mark.*").JavaTree("tagname:=Tree")'
LIQ_MarkPortfolio_SelectPortfoliosToMark_OK_Button = 'JavaWindow("title:=.*Portfolios to Mark.*").JavaButton("title:=OK")'
LIQ_MarkPortfolio_SelectPortfoliosToMark_Cancel_Button = 'JavaWindow("title:=.*Portfolios to Mark.*").JavaButton("title:=Cancel")'
LIQ_MarkPortfolio_SelectPortfoliosToMark_SelectAll_Button = 'JavaWindow("title:=.*Portfolios to Mark.*").JavaButton("title:=Select All")'
LIQ_MarkPortfolio_SelectPortfoliosToMark_DeselectAll_Button = 'JavaWindow("title:=.*Portfolios to Mark.*").JavaButton("title:=Deselect All")'

### Facilities For Selected Portfolios ###
LIQ_FacilitiesForSelectedPortfolio_Window = 'JavaWindow("title:=Facilities For Selected Portfolios")'
LIQ_FacilitiesForSelectedPortfolio_JavaTree = 'JavaWindow("title:=Facilities For Selected Portfolios").JavaTree("attached text:=Drill Down To Enter Facility Mark")'
LIQ_FacilitiesForSelectedPortfolio_Exit_Button = 'JavaWindow("title:=Facilities For Selected Portfolios").JavaButton("attached text:=Exit")'
LIQ_FacilitiesForSelectedPortfolio_Discrepancies_Checkbox = 'JavaWindow("title:=Facilities For Selected Portfolios").JavaCheckBox("attached text:=Discrepancies")'
LIQ_FacilitiesForSelectedPortfolio_CommonMarks_Checkbox = 'JavaWindow("title:=Facilities For Selected Portfolios").JavaCheckBox("attached text:=Common Marks")'
LIQ_FacilitiesForSelectedPortfolio_NoMarks_Checkbox = 'JavaWindow("title:=Facilities For Selected Portfolios").JavaCheckBox("attached text:=No Marks")'

### Available Portfolion Positions ###
LIQ_AvailablePortfolionPositions_Window = 'JavaWindow("text:=Available Portfolio Positions For.*")'
LIQ_AvailablePortfolionPositions_JavaTree = 'JavaWindow("text:=Available Portfolio Positions For.*").JavaTree("attached text:=Drill down to enter mark")'
LIQ_AvailablePortfolionPositions_Exit_Button = 'JavaWindow("text:=Available Portfolio Positions For.*").JavaButton("attached text:=Exit")'

### Hold For Sale ###
LIQ_HoldForSale_Window = 'JavaWindow("text:=Available Portfolio Positions For.*").JavaWindow("text:=Hold for Sale.*")'
LIQ_HoldForSale_TradersMark_Textfield = 'JavaWindow("text:=Available Portfolio Positions For.*").JavaWindow("text:=Hold for Sale.*").JavaEdit("index:=")'
LIQ_HoldForSale_UsePriorMark_Button = 'JavaWindow("text:=Available Portfolio Positions For.*").JavaWindow("text:=Hold for Sale.*").JavaButton("attached text:=Use Prior Mark")'
LIQ_HoldForSale_OK_Button = 'JavaWindow("text:=Available Portfolio Positions For.*").JavaWindow("text:=Hold for Sale.*").JavaButton("attached text:=OK")'
LIQ_HoldForSale_Cancel_Button = 'JavaWindow("text:=Available Portfolio Positions For.*").JavaWindow("text:=Hold for Sale.*").JavaButton("attached text:=Cancel")'

### Approved Mark For ###
LIQ_ApprovedMarkFor_Window = 'JavaWindow("title:=Facilities For Selected Portfolios").JavaWindow("text:=Approved Mark For.*")'
LIQ_ApprovedMarkFor_NewMark_Textfield = 'JavaWindow("title:=Facilities For Selected Portfolios").JavaWindow("text:=Approved Mark For.*").JavaEdit("attached text:=New Mark:")'
LIQ_ApprovedMarkFor_OK_Button = 'JavaWindow("title:=Facilities For Selected Portfolios").JavaWindow("text:=Approved Mark For.*").JavaButton("attached text:=OK")'
LIQ_ApprovedMarkFor_Cancel_Button = 'JavaWindow("title:=Facilities For Selected Portfolios").JavaWindow("text:=Approved Mark For.*").JavaButton("attached text:=Cancel")'
LIQ_ApprovedMarkFor_JavaTree = 'JavaWindow("title:=Facilities For Selected Portfolios").JavaWindow("text:=Approved Mark For.*").JavaTree("attached text:=Drill down to view details")'

### Mark to Market ###
LIQ_MarkToMarket_Window = 'JavaWindow("text:=Available Portfolio Positions For.*").JavaWindow("text:=Mark to Market.*")'
LIQ_MarkToMarket_Textfield = 'JavaWindow("text:=Available Portfolio Positions For.*").JavaWindow("text:=Mark to Market.*").JavaEdit("index:=")'
LIQ_MarkToMarket_UsePriorMark_Button = 'JavaWindow("text:=Available Portfolio Positions For.*").JavaWindow("text:=Mark to Market.*").JavaButton("attached text:=Use Prior Mark")'
LIQ_MarkToMarket_OK_Button = 'JavaWindow("text:=Available Portfolio Positions For.*").JavaWindow("text:=Mark to Market.*").JavaButton("attached text:=OK")'
LIQ_MarkToMarket_Cancel_Button = 'JavaWindow("text:=Available Portfolio Positions For.*").JavaWindow("text:=Mark to Market.*").JavaButton("attached text:=Cancel")'

### Portfolio Share Edit Window ###
LIQ_PortfolioShareEdit_Window = 'JavaWindow("title:=Portfolio Share Edit")'
LIQ_PortfolioShareEdit_Adjustment_TextField = 'JavaWindow("title:=Portfolio Share Edit").JavaEdit("index:=0")'
LIQ_PortfolioShareEdit_Ok_Button = 'JavaWindow("title:=Portfolio Share Edit").JavaButton("attached text:=OK")'
LIQ_PortfolioShareEdit_Funding = 'JavaWindow("title:=Portfolio Share Edit").JavaTree("labeled_containers_path:=Group:Funding;")'
LIQ_PortfolioShareEdit_Legal_Field = 'JavaWindow("title:=Portfolio Share Edit").JavaEdit("attached text:=Legal:")'
LIQ_PortfolioShareEdit_Book_Field = 'JavaWindow("title:=Portfolio Share Edit").JavaEdit("attached text:=Book:")'
LIQ_PortfolioShareEdit_NewBalance_Field = 'JavaWindow("title:=Portfolio Share Edit").JavaEdit("x:=638","y:=128")'
LIQ_PortfolioShareEdit_Cancel_Button = 'JavaWindow("title:=Portfolio Share Edit").JavaButton("label:=Cancel")'
LIQ_PortfolioShareEdit_NewBalance_Text='JavaWindow("title:=Portfolio Share Edit").JavaEdit("index:=1")'
LIQ_PortfolioShareEdit_LegalAmount_Textfield='JavaWindow("title:=Portfolio Share Edit").JavaEdit("index:=0")'
LIQ_PortfolioShareEdit_WriteoffLegalAmount_Textfield='JavaWindow("title:=Portfolio Share Edit").JavaEdit("index:=8")'

### Pending Orig Primaries - Portfolio allocations ###
LIQ_PortfolioAllocations_Facility_JavaTree = 'JavaWindow("title:=Portfolio allocations.*").JavaTree("tagname:=Tree","index:=1")'
LIQ_PortfolioAllocations_AddPortfolio_Button = 'JavaWindow("title:=Portfolio allocations for.*").JavaButton("label:=Add Portfolio/Expense Code")'
LIQ_Portfolio_OK_Button = 'JavaWindow("title:=Portfolio allocations.*").JavaButton("attached text:=OK")'
LIQ_PortfolioAllocations_OK_Button = 'JavaWindow("title:=Portfolio allocations.*").JavaButton("attached text:=OK")'
LIQ_PortfolioAllocations_Branch_List = 'JavaWindow("title:=Portfolio allocations.*").JavaList("attached text:=Branch:")'
LIQ_PortfolioAllocations_PortfolioAllocations_JavaTree = 'JavaWindow("title:=Portfolio allocations.*").JavaObject("tagname:=Group","text:=Portfolio Allocations").JavaTree("attached text:=Drill down to.*")'
LIQ_PortfolioAllocations_Window = 'JavaWindow("title:=Enter Portfolio Allocations","displayed:=1")'
LIQ_PortfolioAllocation_Portfolio_Tree = 'JavaWindow("title:=Enter Portfolio Allocations").JavaTree("index:=1")'
LIQ_PortfolioAllocation_PortfolioTree_Amount_Textfield = 'JavaWindow("title:=Enter Portfolio Allocations").JavaTree("index:=1").JavaEdit("editable:=1")'

### Portfolio Accrual Cycle Detail
LIQ_PortfolioAccrualCycleDetail_Window = 'JavaWindow("title:=Portfolio Accrual Cycle Detail")'
LIQ_PortfolioAccrualCycleDetail_CostOfFunds_Button = 'JavaWindow("title:=Portfolio Accrual Cycle Detail").JavaButton("attached text:=Cost Of Funds")'
LIQ_PortfolioAccrualCycleDetail_CostOfFunds_Window = 'JavaWindow("title:=Cost Of Funds.*")'
LIQ_PortfolioAccrualCycleDetail_CostOfFunds_Window_Tree = 'JavaWindow("title:=Cost Of Funds.*").JavaTree("attached text:=Drill down to see details")'
LIQ_PortfolioAccrualCycleDetail_CostOfFundsDetails_Window = 'JavaWindow("title:=Cost Of Funds Accrual Cycle Detail")'
LIQ_PortfolioAccuralCycleDetail_CostOfFunds_AccruedToDate_Text = 'JavaWindow("title:=Cost Of Funds Accrual Cycle Detail").JavaEdit("index:=0")'
### Portfolio Selection Window###
LIQ_PortfolioSelection_Window = 'JavaWindow("title:=Portfolio Selection For:.*")'
LIQ_PortfolioSelection_Branch_Dropdown = LIQ_PortfolioSelection_Window+'.JavaList("attached text:=Branch:")'
LIQ_PortfolioSelection_PortfolioExpense_JavaTree = LIQ_PortfolioSelection_Window+'.JavaTree("tagname:=Portfolio/Expense:")'
LIQ_PortfolioSelection_Ok_Button = LIQ_PortfolioSelection_Window+'.JavaButton("attached text:=OK")'