*** Settings ***
### BNS LIQ Resource Files - Source Keywords ###
Resource    ../BNS_Customization/ResourcesFiles/LoanIQ_Keywords/Source_Keywords/Customer_Notebook.robot
Resource    ../BNS_Customization/ResourcesFiles/LoanIQ_Keywords/Source_Keywords/Deal_Notebook.robot
Resource    ../BNS_Customization/ResourcesFiles/LoanIQ_Keywords/Source_Keywords/Facility_Notebook.robot
Resource    ../BNS_Customization/ResourcesFiles/LoanIQ_Keywords/Source_Keywords/LoanDrawdown_Notebook.robot
Resource    ../BNS_Customization/ResourcesFiles/LoanIQ_Keywords/Source_Keywords/DealChangeTransaction_Notebook.robot
Resource    ../BNS_Customization/ResourcesFiles/LoanIQ_Keywords/Source_Keywords/Cashflow.robot
Resource    ../BNS_Customization/ResourcesFiles/LoanIQ_Keywords/Source_Keywords/PrincipalPayment_Notebook.robot
Resource    ../BNS_Customization/ResourcesFiles/LoanIQ_Keywords/Source_Keywords/CommitmentFee_Notebook.robot
Resource    ../BNS_Customization/ResourcesFiles/LoanIQ_Keywords/Source_Keywords/Amendment_Notebook.robot
Resource    ../BNS_Customization/ResourcesFiles/LoanIQ_Keywords/Source_Keywords/Circle_Notebook.robot
Resource    ../BNS_Customization/ResourcesFiles/LoanIQ_Keywords/Source_Keywords/LoanDrawdown_Notebook.robot
Resource    ../BNS_Customization/ResourcesFiles/LoanIQ_Keywords/Source_Keywords/PortfolioSettledDiscountChange_Notebook.robot
Resource    ../BNS_Customization/ResourcesFiles/LoanIQ_Keywords/Source_Keywords/Portfolio_Transfer_Notebook.robot
Resource    ../BNS_Customization/ResourcesFiles/LoanIQ_Keywords/Source_Keywords/EventFee_Notebook.robot
Resource    ../BNS_Customization/ResourcesFiles/LoanIQ_Keywords/Source_Keywords/Loan_Notebook.robot
Resource    ../BNS_Customization/ResourcesFiles/LoanIQ_Keywords/Source_Keywords/LoanRepricing_Notebook.robot
Resource    ../BNS_Customization/ResourcesFiles/LoanIQ_Keywords/Source_Keywords/OutstandingChangeTransaction_Notebook.robot
Resource    ../BNS_Customization/ResourcesFiles/LoanIQ_Keywords/Source_Keywords/LiborOptionIncrease_Notebook.robot
Resource    ../BNS_Customization/ResourcesFiles/LoanIQ_Keywords/Source_Keywords/LoanChangeTransaction_Notebook.robot

### BNS Integration Resource Files - Source Keywords ###
Resource    ../BNS_Customization/ResourcesFiles/Integration_Keywords/Source_Keywords/API/MTO/API_MTO_VALIDATION.robot

### LIQ Resource Files - Source Keywords ###

Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/AccountingAndControl_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/AccrualSharesAdjustment_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/ActivityList.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/AdminFee_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/AdminFeeChangeTransaction_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/AdminFeePayment_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/Amendment_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/ApplicationOfOriginationCost_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/AvailabilityChange_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/AvailableFee_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/BankersAcceptance_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/BatchAdministration_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/Billing.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/BreakfundingFee_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/BreakfundingFeePayment_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/BusinessEventOutput.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/Cashflow.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/Circle_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/Collateral_Management.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/CommitmentFee_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/Customer_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/CustomerChangeTransaction_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/Collections_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/Deal_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/DealChangeTransaction_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/DealRestructure_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/Decrease_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/DocTracking_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/GuaranteeDrawdown_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/EssenceGL_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/EventFee_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/EventFeePayment_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/Fac_AddUnscheduled_CommitmentIncrease_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/Facility_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/FacilityChangeTransaction_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/FrontingCommitmentFee_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/FullPrepaymentPenaltyFeeSetUp_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/IncomingManualCashflow_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/IndemnityFee_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/InterestCapitalization_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/InterestPayment_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/IssuanceFeePayment_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/LiborOptionIncrease_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/LineFee_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/Loan_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/LoanChangeTransaction_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/LoanDrawdown_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/LoanDrawdown_ AnotherBankisAgentExpFacCCY_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/LoanRepricing_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/ManualCashflow_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/ManualGL_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/ManualFundsFlow_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/ManualShareAdjustment_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/MarkPortfolio.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/Notices.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/OutgoingManualCashflow_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/OutsideAssignment_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/OutstandingChangeTransaction_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/Paperclip_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/Payment_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/PortfolioSettledDiscountChange_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/PortfolioTradeDateDiscountChange_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/Portfolio_Transfer_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/PricingChangeTransaction_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/PrincipalPayment_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/RepaymentPaperClip_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/RemittanceInstructionChangeTransaction_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/RolloverConversion_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/SBLCGuarantee_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/ScheduledCommitmentDecrease_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/ShareAdjustment_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/SetUpofOriginationCostsTables_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/SwinglineSetUp_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/TableMaintenance.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/Tickler_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/TickingFee_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/TradeEntry_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/TransactionInProcess.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/TreasuryNavigation.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/UnscheduledCommitmentIncrease_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/UnscheduledPrincipalPayment_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/UnscheduledCommitmentDecrease_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/UpfrontFeePayment_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/UserAdministration_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/UpfrontFeeDistribution_Notebook.robot
Resource    ../ResourcesFiles/LoanIQ_Keywords/FusionTransform/Source_Keywords/TroubledDebtRestructuring_Notebook.robot