*** Settings ***

### BNS LoanIQ Variable Files - Locators ###
Variables    ../BNS_Customization/ObjectMap/LoanIQ_Locators/LIQ_Deal_Locators.py
Variables    ../BNS_Customization/ObjectMap/LoanIQ_Locators/LIQ_LoanDrawdown_Locators.py
Variables    ../BNS_Customization/ObjectMap/LoanIQ_Locators/LIQ_AvailableFee_Locators.py
Variables    ../BNS_Customization/ObjectMap/LoanIQ_Locators/LIQ_Customer_Locators.py
Variables    ../BNS_Customization/ObjectMap/LoanIQ_Locators/LIQ_Facility_Locators.py
Variables    ../BNS_Customization/ObjectMap/LoanIQ_Locators/LIQ_LoanDrawdown_Locators.py
Variables    ../BNS_Customization/ObjectMap/LoanIQ_Locators/LIQ_Loan_Locators.py
Variables    ../BNS_Customization/ObjectMap/LoanIQ_Locators/LIQ_Portfolio_Locators.py

### LoanIQ Variable Files - Locators ###
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_AccountingAndControl_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_AccrualSharesAdjustment_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_AdminFee_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_ActivityList_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_AdminFeeChangeTransaction_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_AlternativeReferenceRates_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_Amendment_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_AssignmentBuy_Locator.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_AssignmentSell_Locator.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_AutomaticShareAdjustment_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_AutomatedTransactionsEditor_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_AvailableFee_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_BankersAcceptances_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_BaseRateDetails_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_Batch_Administration_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_Billing_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_BreakfundingFee_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_BusinessEventOutput_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_Cashflow_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_Circle_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_Collateral_Management_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_CommitmentFee_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_CurrecyExchangeRates_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_Customer_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_Collections_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_Deal_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_DealRestructure_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_Decrease_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_DocumentTracking_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_EssenceGL_Notebook.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_EventFee_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_Facility_AddUnscheduled_CommitmentIncrease_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_Facility_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_FrontingCommitmentFee_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_FundingRates_Locator.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_Global_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_GuaranteeDrawdown_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_IncomingManualCashflow_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_Increase_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_IndemnityFee_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_InterestCapitalization_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_InterestPayments_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_Internal_Trade_Assignment_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_Issuance_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_LineFee_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_Loan_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_LoanChangeTransaction_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_LoanDrawdown_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_LoanRepricing_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_ManualCashflow_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_ManualFundFlow_Notebook.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_ManualGL_Notebook.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_ManualShareAdjustment_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_Notices_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_OpenAUserProfile_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_OutgoingManualCashflow_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_OngoingFeePayment_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_PaperClip_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_ParticipationBuy_Locator.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_PaymentApplication_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_Portfolio_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_PricingChangeTransaction_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_Primaries_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_PrincipalPayment_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_RepaymentPaperClip_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_ReverseInitialDrawdown_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_ReversePrincipalPayment_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_RolloverConversion_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_SBLC_Decrease_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_SBLCGuarantee_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_ScheduledCommitment_Locator.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_ScheduledPrincipalPayment_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_ShareAdjustment_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_TableMaintenance_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_Tickler_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_TickingFee_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_TreasuryNavigation_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_UnscheduledCommitmentDecrease_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_UnscheduledCommitmentIncrease_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_UnscheduledPrincipalPayment_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_UpfrontFeePayment_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_User_Administration_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_WorkInProcess_Locators.py
Variables    ../ObjectMap/LoanIQ_Locators/LIQ_UpfrontFeeDistribution_Locators.py